### ISSUE TITLE
Sample OPEN API Spec 3.0 and compatible Swagger UI 

### ISSUE THREAD

**Issue by kunalsmile** [OAI/OpenAPI-Specification#1024]
Hi,
We would like to migrate from Swagger 2.0 to OPEN API Spec 3.0 as per the blog 
[Read Me Blog](https://blog.readme.io/an-example-filled-guide-to-swagger-3-2)
We tried to construct OAS json and display using online petstore example, but it is not parsing 3.0 spec JSON.
Can you provide us with the sample OPEN API Specification file along with the compatible Swagger UI to host OAS.
This will help us to migrate from version 2 to 3.

Please help with us.

**Comment by ponelat** [comment]
@kunalsmile swagger-ui does not yet support OAS 3.0 It is something we'll be working on in swagger-ui/editor/js and other open source tooling.
The specification still needs to be finalized ( @webron ? what stage of the 3.0 are we in?) before the tooling catches up.

Feel free to bug the OSS projects... so that others can find out about the status of 3.0 in tooling!

**Comment by MikeRalphson** [comment]
>  @webron ? what stage of the 3.0 are we in?

Indeed, it is a little unclear if we are **at** 3.0.0-RC1 or that a kind of merge-window for 3.0.0-RC1 has begun.

**Comment by ePaul** [comment]
I think we'll be at 3.0.0-RC1 when the tag is created.

**Comment by whitlockjc** [comment]
@ponelat The OAI has released an [Implementer's Draft](https://www.openapis.org/blog/2017/03/01/openapi-spec-3-implementers-draft-released) so it's a perfect time to start looking at adding support for 3.0.

**Comment by scottmas** [comment]
A sample Petstore 3.0 would be amazing. A comprehensive example is soooo much easier to understand and follow than trying to piece together the spec.

**Comment by MikeRalphson** [comment]
@scotmas it's a work in progress, but there is a [v3 petstore example](https://github.com/OAI/OpenAPI-Specification/blob/dm/examples/examples/v3.0/petstore-expanded.yaml) on the dm/examples branch.

**Comment by SamuelMarks** [comment]
FYI: Here's the new [v3 petstore example link](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/examples/v3.0/petstore.yaml)

**Comment by danieljgmaclean** [comment]
Would you guys be able to add an example of serializing an object into say application/json into a query parameter to the v3 petstore example? You have a simpler example described here: https://swagger.io/docs/specification/describing-parameters/#schema-vs-content, but it would be nice to see one with a #ref rather than explicitly typed structures.

**Comment by fanguoguo** [comment]
https : //swagger.io/docs/specification/describing-parameters/#schema-vs-content

**Comment by handrews** [comment]
The 3.0 petstore example (and others) were added years ago, so I'm closing this as resolved.
