### ISSUE TITLE
Design discussion:  how to guide Java developers

### ISSUE THREAD

**Issue by arthurdm** [OAI/OpenAPI-Specification#1082]
I understand that OAS is language-agnostic, but wanted to see what others thought about having an official set of Java annotations, which in Java always belong at the spec level.  

For illustrative purposes, a Java spec such as JAX-RS defines the specification, the annotations and corresponding programming models.  It often has a reference implementation, and several other implementations, but all of them using the same set of interfaces (making apps portable across vendors / OSS providers).

In the Java world there are many possible frameworks that one could use:  JEE, Spring, MicroProfile, Dropwizard, the list goes on.   So if a Java developers says: "hey, there's a new official spec, the OpenAPI Specification, I want to use that!  Now, what's the programming model that I should use?".    

By far the most popular choice is the Swagger repo, but we are seeing other (competing) Java programming models emerging that work with OpenAPI v3.  

My proposal is to make the Swagger v3 annotations for OpenAPI the official (or at least recommended) interfaces from OAS.   So we could release an official package such as `io.oas.annotations`, which would indicate a clear choice for Java developers - regardless of the Java framework they are using.

We can chat about other programming models later, I thought it would be easier to keep this focused to the annotations first (golden path for most Java apps).  

Thoughts?

**Comment by ePaul** [comment]
I personally are a fan of "API first", meaning I would write the API definition first (and have it reviewed), and then the implementation (on both client and server side) based on it (usually generating the models). As such, I prefer not to use any OpenAPI/Swagger specific annotations.

For people wanting to do it the other way around (i.e. first write an implementation (likely of the server side) and then generate an OpenAPI definition document from it), annotations at the implementation classes/methods seem useful. But from what I have seen, often those annotations seem to duplicate (at least partially) what a used framework used already derives from its own annotations (or some magic in its implementation).

Therefore I would try to refrain from the idea of having "one set of annotations to rule them all" (or at least from declaring such an annotation set as "official"), instead have framework-specific adapters which add just the missing parts (likely mostly documentation bits).

**Comment by raymondfeng** [comment]
I would like to see support for bottom-up approach in addition to `API first`. Having standardized Java annotations for OpenAPI will help. The framework can infer OpenAPI related metadata from its own annotations such as JAX-RS but the OpenAPI ones can be used to express metadata that is not available otherwise.

**Comment by evanjbowling** [comment]
OpenAPI developers - is there a preferred approach for opening design discussions here? Right now I don't see any guidance in the form of a CONTRIBUTIONS.md page in the master branch.

Anyways, I have some links that may be of interest to @arthurdm and the others. Have you seen the swagger-codegen project: https://github.com/swagger-api/swagger-codegen/wiki/API-client-generator-HOWTO . It allows you to generate client/server-side stubs in many languages including a Java JAX-RS language. See a quick example repo that I made here: https://github.com/evanjbowling/swagger-codegen-java-demo

Now, regarding the Java annotations for OpenAPI. Since OpenAPI focuses on RESTful APIs in a vendor-neutral manner, we can simply reuse the JAX-RS annotations for RESTful services. The way to get more Java-focused support would be to go through the JSR process which created JAX-RS in the first place (JSR 311). See these other links for RESTful focused JSRs: https://jcp.org/en/jsr/summary?id=JAX-RS

**Comment by arthurdm** [comment]
@evanjbowling  - thanks for the links.  The issue is that this generator is one of many, and other generators could pick to generate code with different annotations.  

@ePaul - I agree with your statement that the existing popular Java frameworks (JAX-RS, Spring, etc) do have overlapping annotations with Swagger/OpenAPI.  However, as @raymondfeng correctly pointed out, these OAS annotations can augment the existing frameworks' annotations (not replace them).  

So to be clear, my proposal is to have a set of annotations inside a new repository in the OAI org (https://github.com/OAI), so something like `https://github.com/OAI/OpenAPI-Java`, which would define these interfaces/annotations.  That way, all tools and implementation (from different companies) would be using the same set of interfaces.

**Comment by darrelmiller** [comment]
The scope of the OAI project is to define a description language for HTTP APIs.  Mapping that description to other technologies, such as languages, is out of scope for this project.  

I'm sure there is value to standardizing Java annotations for OpenAPI, but that work should be done within a Java related standards organization.  Opening the door to creating language bindings for one language effectively means taking on responsibility for doing the same for all popular languages and as well as being out of scope, we don't have the capacity or expertise to do that effectively in this project.

As a TDC member I am happy to provide guidance to people in other standard groups  who are trying to create this kind of mapping, but this cannot be done under the OAI umbrella.

**Comment by arthurdm** [comment]
Thanks for the feedback @darrelmiller . It helped clarify the positioning of the OAI.

Thinking more about it, the correct place to officially endorse the OAS Java programming models will be at the MicroProfile group.
