### ISSUE TITLE
having a standard query param to display API Documentation ( Swaggger).

### ISSUE THREAD

**Issue by apoorvkapil** [OAI/OpenAPI-Specification#1110]
Hello folks,

It would be helpful to add a query param to display API Definition in swagger , and swagger should support it.
ie: WSDL : if i am publishing a soap API it's URL provides me the definition of API itself by adding query param ?wsdl , so i don't need to visit any developer portal for definition.

we should have same definition for REST API also. <http scheme><apiURI>?swagger

**Comment by MikeRalphson** [comment]
A thumbs down from me for several reasons:

* An OpenAPI definition should be able to define an existing API, i.e. one which currently **does not** serve it's own OpenAPI definition
* The OpenAPI schema object is not yet sufficiently compatible with JSON schema to allow fully expressing the schema needed to validate the returned OpenAPI definition
* What version of OpenAPI should be returned? Version 1.0/1.1/1.2 would cause additional issues
* Possible performance/storage implications for embedded (IoT) device APIs.

Given that this feature would need to be optional (and that a defined resource / path would be preferable to a common query parameter - due to the need to serve relative `$ref` URLs), and is relatively trivial to support in your own APIs today (schema restrictions notwithstanding), one possibility is suggesting for example that **by convention** a path of `/openapi` MAY be used to serve the API's OpenAPI definition.

**Comment by darrelmiller** [comment]
In addition to the reasoning provided by @MikeRalphson, creating specifications that constrain what URLs can/should used by an application is not recommended https://tools.ietf.org/html/rfc7320

**Comment by webron** [comment]
Thanks for submitting the issue, but it seems like a poor fit for what we're trying to achieve here.
