### ISSUE TITLE
Clarification on operationRef in link object specification

### ISSUE THREAD

**Issue by Alan-Cha** [OAI/OpenAPI-Specification#1152]
Could you clarify how the operationRef in the link object specification works? 

You provided some [examples](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#example-1), showcasing how operationRef and operationId can be utilized and even though I found the operationId example understandable, I thought the operationRef example was confusing. 

Here is the operationRef example you provided:
```XML
components:
  links:
    UserRepositories:
      # returns array of '#/components/schemas/repository'
      operationRef: '#paths~12.0~1repositories~1{$response.body#/username}'
```

What does "`#paths~12.0~1repositories~1`" mean? Is "`~12.0~1repositories~1`" a directory? And shouldn't the operation have an HTTP verb attached to it? 

Thanks!

**Comment by ePaul** [comment]
I guess the idea is to point to this part in the definition:

```
paths:
  /2.0/repositories/{username}:
```
The `~1` is a way of JSON pointer to replace `/` occurring in a property name (because `/` is already used as level separator).

I don't know if the `{$response.body#/username}` here is correct (I didn't read that part of the spec in detail).

**Comment by darrelmiller** [comment]
The `operationRef` examples are missing the operation and I will fix those.

**Comment by darrelmiller** [comment]
Fixed.
