### ISSUE TITLE
Where to put ancillary content

### ISSUE THREAD

**Issue by RobDolinMS** [OAI/OpenAPI-Specification#1246]
Some items should live in spec and maybe some should be in their own repo(s):
* Examples
* Example fragments
* Public-facing website
* Implementations list
* Schemas (?)
* Registries of stuff

**Comment by ChengZhengBo** [comment]
good lucky

**Comment by handrews** [comment]
* Examples / example fragments should go in OAI/learn.openapis.org
* Implementations list is already in OAI/Tooling
* Should the registries and the rest of the non-Linux Foundation-maintained public web site move over to OAI/learn.openapis.org as well?  Or is that tied to the spec enough to keep it here?
* We currently sort-of treat this repo like a JavaScript package for deploying schemas, although I don't think it's ever actually worked that way.  We also use the same JavaScript environment for PR checks and workflow automation.  Since schemas are on main and we don't make spec changes there except to fix externally-broken links, theres not much benefit to keeping them here - you can't align spec and schema PRs.  Should schemas be a separate JS package repo?

**Comment by handrews** [comment]
No one objected to my list of where stuff goes from several months ago, closing.
