### ISSUE TITLE
Example of deepObject + explode=false

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1322]
How are objects serialized when using `style: deepObject` and `explode: false`? [Style Examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples) contain a `deepObject` example only for `explode: true`.

(Related - OAI/learn.openapis.org#100)

**Comment by lornajane** [comment]
We discussed that we probably don't need exploded (or not) alternatives for deepObject; @handrews will add a clarification note but we won't add another entry for it with explode=false

**Comment by handrews** [comment]
Fix added to PR #3859.  @lornajane I know you said don't add more rows but it was just bothering the heck out of me that it's unclear in the one place people glance at the most (rather than poring over the text).  If you want me to remove them I will, but I as I look over the voluminous history of issues and complaints in this area, I think failing to address it in the table is problematic (and likewise for the other incomplete entires).

**Comment by handrews** [comment]
PR merged for 3.0.4 and ported to 3.1.1 via PR #3921!
