### ISSUE TITLE
Support scheme rtmp/rtmps

### ISSUE THREAD

**Issue by richardzembron** [OAI/OpenAPI-Specification#1408]
We are writing an API for a rtmp service. That simply means that the service is using protocol rtmp rather than http/https. In swagger.io we have set scheme to rtmp, but as soon as we save, swagger changes it to https, which of course is not valid for this API service. rtmp is the most common streaming protocol, in addition rtmps, rtsp, rtsps are commonly used.

We would like scheme to support rtmp, rtmps, rtsp and rtsps

**Comment by darrelmiller** [comment]
OpenAPI is a description format that is designed to describe HTTP interactions.  It defines operations based on HTTP URLs and has mechanisms to describe HTTP headers and media type based payloads. And it assumes a request/response interaction.

There is no generalized support for describing message based protocols, so even if we allowed the rtmp schemes, I highly doubt that the format would be appropriate for describing a real time streaming API.

**Comment by handrews** [comment]
With apologies to @darrelmiller and the OpenAPI project, @richardzembron since you don't have an email on your profile I'll hijack this to ask if you would take a look at the [about-to-be-published JSON Hyper-Schema spec](http://json-schema.org/work-in-progress/WIP-jsonschema-hyperschema.html).  While it is a media type rather than API description format, it attempts to be protocol- and uri-scheme-neutral.  If you are interested see anything that would make using it with rtmp difficult, please do file an issue in the [JSON Schema repository](https://github.com/json-schema-org/json-schema-spec/issues).  We have been looking for other real-world protocols to see how they would fit with Hyper-Schema.

**Comment by darrelmiller** [comment]
@handrews  I'm not sure even JSON schema can help here :-).  According to [Wikipedia](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol#Invoke_Message_Structure_.280x14.2C_0x11.29) rtmp uses a format called AMF that is its own format not based on JSON.

**Comment by handrews** [comment]
@darrelmiller hmm... yeah not sure that would work, I hadn't realized that :-/  If it's possible to work out a mapping from AMF into the JSON Schema data model then it could be useful, but it's not immediately clear to me how that would work.  @richardzembron if you want to explore that please open an issue at the JSON Schema repo.

**Comment by MikeRalphson** [comment]
It may be worth looking at the [AsyncAPI specification](https://www.asyncapi.com/) though that is for asynchronous message-passing protocols, not streaming ones per-se.

**Comment by darrelmiller** [comment]
@MikeRalphson  Now that's what I'm talking about.  Something that borrows from OAS where it makes sense but designed specifically for message based protocols.

**Comment by handrews** [comment]
@MikeRalphson @darrelmiller yeah looks like a better fit!

**Comment by fmvilas** [comment]
Yeah, it might be a good fit for AsyncAPI, although not yet supported. Let me know if I can help somehow.

**Comment by darrelmiller** [comment]
Currently OAI is discussing whether its scope should encompass other types of APIs and in the meanwhile we recommend you take a close look at AsyncAPI.
