### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by nelz9999** [OAI/OpenAPI-Specification#1412]
As per what I view as harassment on #1411 ...

I'd like to suggest adopting a Code of Conduct. Perhaps beg/borrow/steal the CoC from Rust: https://www.rust-lang.org/en-US/conduct.html

**Comment by darrelmiller** [comment]
@nelz9999 We actually discussed this issue on our steering committee call last Friday.  It's definitely on our todo list.  We been a bit slow because we haven't really had any incidents, but you are correct, it needs to be done.

**Comment by silkentrance** [comment]
Personally, I think that this was a lively discussion. Along with also the notion that the OP did not get what OAS is all about. It allows you to specify custom ``x-...`` properties and then have your own code generators or even modify an existing code generator's templates so that you get the result that you need. So OAS is open and free for you to implement whatever you like. And there was no harassment in the discussion. Just two people having opposite opinions and one of these not getting the gist of OAS at all.

Or should we all put on rose-colored glasses?

**Comment by tedepstein** [comment]
@silkentrance, I do think the OP leveled a personal insult in that thread, despite his attempt to claim that it wasn't an insult. Our code of conduct, when we have one, should prohibit disrespectful behavior like that.

Overall, I don't think that was an illuminating discussion, and I would not consider it healthy for the OpenAPI community to have more discussions like that, with such a low signal-to-noise ratio.  

Spirited debate is good, when the participants are in fact talking about the same thing, in language that they all understand. Or, failing that, when _all_ participants take the time to make themselves properly understood, and take the time to understand each other, so the discussion can converge towards a shared understanding.

I've read through that issue, followed the OP's links, and spent more than enough time trying to decode the message conveyed there... not for the first time. Someone wrote, "We've had this conversation before," and I can say the same. I do think there is likely something of real value there, but I don't blame myself, nor anyone on the TSC, for failing to understand it, as presented. I also think the highly unusual vocabulary, abstractions, and generalizations contained therein created a completely unnecessary barrier to understanding and constructively debating the OP's proposal.  We could have had a good discussion about the proposal without all of this "theory."

I'm not sure how much of this can or should be described in a code of conduct. "Don't insult another person's intelligence" seems like a pretty basic thing to have in a CoC, kind of generalization of "don't insult people." 

Other things seem more like kitchen table wisdom, or just good manners, that could be difficult or inappropriate to put into a CoC.  Things like, "seek first to understand, then to be understood."  I could go on, but I'll stop there.

**Comment by jimschubert** [comment]
While I'm not a member of OAI and many of the comments in the linked issue have been edited or deleted, I'd like to offer a few suggestions for the Code of Conduct.

* _Discourage passive aggressive remarks from both sides_. I see where the "insult" occurred in the thread, but I didn't read it as an insult. There is obviously a language barrier in the discussion, and it was met with curt responses which many cultures view as rude or passive aggressive. As an example, avoid telling people they're making the community "unsafe". I'm not trying to point the blame at either party, just providing details of what I've seen as an outsider (which was previously requested of me by an OAI member). I think this needs to be called out separately from being respectful, because you can still be respectful but seem aggressive.
* _Be respectful_. Again, I'm not an OAI member, but I have been a contributor to the community for over 2 years. I won't speak of my personal experiences here because they're irrelevant, so my comment is only in relation to the linked issue. I think it would be very positive to address issues such as the linked example as if the person doesn't have such an intimate understanding of the specification or best practices. I've found that a lot of times, questions and suggestion are just knowledge gaps. I think @darrelmiller did a great job offering a solution.
* _Avoid deleting comments_. The linked issue has had comments deleted. I've never deleted a GitHub comment on any repos I own, so I'm not sure if the deleted comments remain visible for repo owners. But from an outside perspective, it leads to a confusingly disconnected conversation. Also, I've seen comments edited and the edits deleted. You can't really prevent this and the fact that it has occurred is only visible to the commenter and anyone subscribed to notifications on the thread. Similar to deleting comments, deleting edits can lead to confusing the conversation if a participant is replying to an earlier version of an edit.

**Comment by MikeRalphson** [comment]
Closing as #2416 was merged. Thanks all.
