### ISSUE TITLE
Openapi 3.x : dynamic and conditional data for parameters

### ISSUE THREAD

**Issue by starinfor** [OAI/OpenAPI-Specification#1418]
Does the new version of spec support dynamic and conditional data for parameters ?

For ex: if A= 1, then B = a,b,c
if A=2, B= d,e,f 

Assuming the data resides on server.

**Comment by darrelmiller** [comment]
nope.

**Comment by silkentrance** [comment]
What you are basically asking for are parameter level validations. How would this be possible, not knowing the data on the server? Can this even be achieved considering the numerous possibilities how data is stored on the server? And would we want that, as it will impose certain architectural decisions made by the available code generators?

**Comment by handrews** [comment]
The  server side automation of this is out-of-scope for this project as described above.

For conditional validation across multiple parameters, Moonwalk uses a [single schema for all params](https://github.com/OAI/sig-moonwalk?tab=readme-ov-file#jsonschema-for-parameters), so you can specify conditional validation there.  I'm going to close this as "Moved to Moonwalk" since that is the first release where we can make that sort of change.
