### ISSUE TITLE
OAS 2.1

### ISSUE THREAD

**Issue by heldersepu** [OAI/OpenAPI-Specification#1477]
Any chance we can get an OAS 2.1 ?
Would like to see `example` on the [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject)

Just like we are doing for the [OAS 3 Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject)

Perhaps we can add a few other optional fields that will not break 2.0 backward compatibility

**Comment by webron** [comment]
@heldersepu thanks for the proposal. While it may not be too complicated to publish a 2.1 version, given that 2.0 was published a long time ago, and 3.0.0 was published in the summer, we would rather encourage users and vendors to move to that version rather than issue an intermediate version that will require additional support. We've had a discussion about it in our weekly meeting, and there's general consensus this is not the right path for the project.

**Comment by heldersepu** [comment]
I understand the push to 3.0 but that version is not backward compatible with 2.0. 
because the lack of this feature Swagger-Ui 2.x was supporting x-example
...and we have a pending requests to support it on UI 3.x:
https://github.com/swagger-api/swagger-ui/pull/3538

**Comment by webron** [comment]
But that's a tooling issue, not a spec one. Releasing a 2.1 would require more resources than we have, and it would also require additional resources from tool vendors to support 2.1 as well. This will set back support for OAS3, instead of pushing it forward.

**Comment by MikeRalphson** [comment]
For what it's worth, I have found the following https://github.com/dutradda/OpenAPI-Specification-2.1/blob/master/README.md
