### ISSUE TITLE
Aggregating the Web-Services from Swagger API documentation

### ISSUE THREAD

**Issue by sayakpaul** [OAI/OpenAPI-Specification#1492]
I have well documented the API services of my project. I was wondering if there is way in which a list of services could be exported from the Swagger doc.

**Comment by MikeRalphson** [comment]
Could you expand on your meaning of "services" in OpenAPI terms, i.e. do you mean `path Items` or `operations` etc?

If your OpenAPI document is in JSON format, you may be able to use something like [jq](https://stedolan.github.io/jq/) to extract the information you need, otherwise (or if your needs are more complex) it may be worth looking at a templated code generation tool such as [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

Either way, this repository is for the specification itself. Further questions on tooling should probably be addressed to the [groups.io](https://openapi.groups.io/g/tooling) group.

**Comment by handrews** [comment]
No reply to information requested in 2018, closing.
