### ISSUE TITLE
Host schema publicly

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#151]
In order to accomplish #103 elegantly, we should host the json schema for the 2.0 spec under the swagger.io domain. Probably something like http://swagger.io/schemas/v2.0/schema (based on json-schema's id declaration `"id": "http://json-schema.org/draft-04/schema#"`).

**Comment by handrews** [comment]
@webron I think we agreed this should be the issue tracking how/when we deploy schema updates.  Including deploying new revisions of the OAS 3.1 JSON Schema vocabulary and dialect  meta-schemas which don't currently have dates in their `$id`s.  Which I think happened because I wrote them as tentative proposals and then by the time OAS 3.1 shipped I wasn't around to catch that sort of thing.

**Comment by jdesrosiers** [comment]
I've been handling schema deployment. I don't usually prepare a deployment for every change, but tend to wait a little while in case more changes come in (they usually come in waves). There are currently two changes that have been merged but not deployed yet and one open PR.

Here's the process I've been following for deployment
1. Update release dates in
    * schema.yaml
    * schema-base.yaml (Don't forget the one in the `$ref`)
    * tests/v3.1/test.js
2. Generate the JSON versions from the YAML versions
    * The README says to only modify the YAML version, but contributors usually include changes to both. So, this step is usually just a sanity check.
3. Run the tests
    * The tests are very minimal and haven't been added to since they were first added, but I make sure that we at least don't break what we have.
3. Deploy the schemas
    * Add the schemas to the `gh-pages` branch
    * Update the `latest` symlink to point to the newest version
4. Other stuff I'm forgetting about ???

Here's an example of a deploy I've done in the past
* https://github.com/OAI/OpenAPI-Specification/pull/3042
* https://github.com/OAI/OpenAPI-Specification/pull/3043

>  Including deploying new revisions of the OAS 3.1 JSON Schema vocabulary and dialect meta-schemas which don't currently have dates in their `$ids`. Which I think happened because I wrote them as tentative proposals and then by the time OAS 3.1 shipped I wasn't around to catch that sort of thing.

Actually, I wrote those meta-schemas. I didn't include a date in the schema for the same reasons we don't include one in JSON Schema meta-schemas. The `$id`s of meta-schemas are what schemas authors use in `$schema` to indicate the version of JSON Schema their schema is using. If we version meta-schemas, users would need to update all of their schemas that declare this dialect every time we release a bugfix. There are lots of reasons that's not a good user experience.

To avoid this, at JSON Schema, any time we need to make a fix in the meta-schema, we've always just fixed it and kept the same `$id`. This has never cause a problem. I intended for these meta-schemas to be maintained the same way, but so far, there hasn't been a need to update the vocabulary/dialect meta-schemas.

Ideally, I'd think that meta-schemas probably should be versioned, but there should also be an unversioned URI that's effectively a redirect to latest version that the vast majority of users would use for `$schema` rather than the versioned URI.

I'm happy to hand the schema maintenance and deployment process over to whoever wants it. I've always just done the minimum to keep it afloat, so it would benefit from someone actually putting effort into improving this process.

**Comment by handrews** [comment]
The date-in-`$id` policy should be the same for all the OAS schemas (whether they are JSON Schema meta-schemas or not).  I'm fine with whatever policy @OAI/tsc wants (date or no date), as long as it is consistent.  Having two different policies is worse UX than either individual policy.  (Also, my apologies for mis-remembering who wrote those!)

**Comment by handrews** [comment]
I'm closing this now very long and very out-of-date (aside from the last three comments) issue as too confusing for current tracking.  Please use the following:

* #3715 contains the last three comments above for continuing the discussion of publishing schemas on our own sites
* #3716 tracks the process questions around _when_ and _why_ we update schemas
* #3677 tracks general branching policy decisions (most schema questions were split to #3716 but this is still related)
* #2400 tracks publishing schemas to NPM, which is distinct from our own site publishing in #3715
