### ISSUE TITLE
Question About Datetypes

### ISSUE THREAD

**Issue by gehnster** [OAI/OpenAPI-Specification#1513]
So started looking at swagger and was curious about how the data types work. Say you have a spec that just specifies that something is an integer. What if someone tries to use that spec for something like C# where that spec would make it auto-generate a regular int32, but really what they needed was an int64. Why does the Swagger spec just say integer and not specify what type of integer is actually needed? In my mind it makes the spec useful for generating a beginning model for a POCO in C# but you still need to test it to make sure that int in the POCO is actually valid and you don't really need a long instead. Also, this could bring up unsigned data types as well. Why not be more specific I guess is my overall question.

**Comment by darrelmiller** [comment]
The quick answer is because when you try to be precise about implementation related things in a cross platform specification you end up with a monstrous nightmare.  It is the same reason the JSON spec just defines a number.  We have the notion of ['format'](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#dataTypes) which allows more precision on the datatype and we are planning to create a registry of formats that will allow these formats to be extended to support implementation specific serializations.

**Comment by gehnster** [comment]
Doesn't allowing that ambiguity go against the idea of this being a specification though? I get you can use format if needed, but it is only an optional item and not a requirement.

**Comment by darrelmiller** [comment]
@gehnster It follows the pattern that the IETF use with regard to using registries as extension points for specifications.  https://www.ietf.org/assignments/

**Comment by gehnster** [comment]
Extension for a specification doesn't sound like a good idea to me, but I'm not going to pretend I understand what you said means so OK. Sorry to bother ya.

**Comment by cyberphone** [comment]
@darrelmiller @gehnster  I chime in on this?  If you want an `int64` that actually holds what the name says, using JSON "Number" doesn't work.  The current JSON author agrees with that: https://tools.ietf.org/html/rfc7493

In a specification I'm working on, I have taken the above as a fact:
https://cyberphone.github.io/doc/security/draft-rundgren-json-canonicalization-scheme.html#rfc.appendix.D

Apparently (and unfortunately) my statement about OpenAPI seems to be wrong :-(
