### ISSUE TITLE
conditionally nested objects?

### ISSUE THREAD

**Issue by dtirer** [OAI/OpenAPI-Specification#1555]
I have an API i'm trying to document using OpenAPI 3.0

In this API, endpoints can include objects, and those objects can conditionally include other objects, and so on.

So for example: Object A can contain Object B, and Object B can contain Object C. On endpoint 1, Object A contains Object B, and Object B contains Object C. However, on endpoint 2. Object B does NOT contain Object C

I'm trying to structure my components in the most DRY way possible, but where I also have complete flexibility as far as assembling the hierarchy of object schemas on a per-path basis.

Is it possible to accomplish this in a DRY manner using OpenAPI?

**Comment by dtirer** [comment]
wanted to follow up on this

**Comment by MikeRalphson** [comment]
Ping @handrews

**Comment by handrews** [comment]
@dtirer it's hard to answer this without knowing exactly what you mean by "contains", and whether you are using `additionalProperties` in any way.  Does "contains Object B" mean "has a property whose value is Object B"?

**Comment by dtirer** [comment]
@handrews just wanted to follow up on this

**Comment by handrews** [comment]
@dtirer actually, looking at this now, I don't see the condition?  You just want to assemble them differently in different places?  Sorry, I had a horrible cold throughout the holidays and barely remember making the above comment.

For endpoint one:
```JSON
{
  "allOf": [
    {"$ref": "#/components/schemas/objectA"},
    {
      "properties": {
        "b": {
          "allOf": [
            {"$ref": "#/components/schemas/objectB"},
            {
              "properties": {
                "c": {"$ref": "#/components/schemas/objectC"}
              }
            }
          ]
        }
      }
    }
  ]
}
```

And then for endpoint two, just have `b` directly `$ref` objectB instead of using an `allOf`.  OR, use the `allOf` but instead of adding `properties` with a `c` property, add `{"not": {"required": ["c"]}}` to prevent `c` from being present at all.

**Comment by handrews** [comment]
No further response for over a year, I'm assuming the OP figured it out.
