### ISSUE TITLE
TSC Meeting - May 21st 2018

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1585]
**NOTE: This is Monday at 9am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Update on cname for spec | @namdeirf  | In progress: Filed ticket with LF IT  |
| Review status of alternativeSchema proposal | @darrelmiller  |  |
| Update on client certificate support | @MikeRalphson  | @isamauny to provide expertise from a security perspective and provide a followup by June 4th. |
| Feedback from Gluecon | @webron | Deferred  |
| Registry Repo POC | @mikeralphson | |
| Followup on `allowEmptyValue` issue [#1573](https://github.com/OAI/OpenAPI-Specification/issues/1573)| @OAI/tsc |   |
| Merge complete PRs | @OAI/tsc | |
| Review issues with "[review](https://github.com/OAI/OpenAPI-Specification/labels/review)" tag | @OAI/tsc | | 
| Update on work related to  specification conformance tests | @tedepstein  |  |

/cc @OAI/tsc Please add items as you see fit

**Comment by namdeirf** [comment]
OpenAPI Initiative Project
Technical Steering Committee (TSC) Meeting
May 21, 2016 (9:00am - 10:30am PT)
via Zoom


| TSC Members | Participants |
|-------|---------| 
| Darrel Miller | Phil Sturgeon (WeWork) |
| Marsh Gardiner | Ted Epstein (RepreseZen) |
| Mike Ralphson | Chuck Heazel (WiSC Enterprises) |
| Uri Sarid | Isabelle Mauny (42Crunch) |
| ~Jeremy Whitlock~ | Jeff ErnstFriedman (Linux Foundation) |
| ~Ron Ratovsky~ | < unidentified, 650 phone number > |

At 9:05am Darrel Miller, called the meeting to order, with four members in attendance, quorum was achieved and the meeting moved to regular business. The meeting proceeded to consider the agenda laid out in #1585 and onto the first item.

ErnstFriedman provided an update on establishing a CNAME and has filed a ticket with LF IT. 

Miller asked to skip this issue and move to the next issue and revisit later in the meeting.

The body moved on to consider update on client certificate support, following  consideration, Mauny was tasked with providing domain expertise so that body can discuss further. The body tabled the issue until a future meeting.

The body moved on to consider supporting alternative schemas proposal #1532. After consideration the body decided to alter the proposal and moved to add a new field called alternativeSchema to the OAS Schema Object as described in this comment https://github.com/OAI/OpenAPI-Specification/issues/1532#issuecomment-390510256

Having exhausted this issue, the body moved on to consideration of Registry Repo roof of concept. TSC Member Ralphson talked about this proposal with examples found on https://github.com/MikeRalphson/registry/. Use of the tool would allow for a schema registry within the GitHub workflow. After reviewing, the body had no objection to moving and development can move forward. The body tabled the issue and moved on to consider open issues.

The body reviewed GitHub issues:

| Issue | Result |
|-------|---------| 
| #1584 | Merged |
| #1582 | Merged |
| #1568 | Merged |
| #1538 | Deferred | 
| #1576 | Deferred |

Having exhausted the allotted time, the body deferred all remaining agenda items until the next scheduled meeting.
