### ISSUE TITLE
Can a schema parameter's 'required' attribute be overridden?

### ISSUE THREAD

**Issue by cmeeren** [OAI/OpenAPI-Specification#1590]
I have a common object defined in `schemas` referenced in a couple of endpoints. However, the specific set of required fields differ between the references. For example, one endpoint requires properties `foo` and `bar`, while another endpoint requires properties `foo` and `qux`.

Is it possible to override the `required` list when referencing a schema? Is there another fairly DRY way to accomplish this? (The only workaround I can think of is inlining the schema everywhere, which leads to duplication and possibility of inconsistencies.)

If it's not possible, could this be implemented?

**Comment by handrews** [comment]
Yes, since `foo` is required in both cases, have `"required": ["foo"]` in your re-usable schema under `components`, and then use `allOf` to reference the re-usable schema and also add `"required": ["bar"]` or `"required": ["qux"]` or whatever.

https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.7.1

**Comment by cmeeren** [comment]
Brilliant, thanks! I'll have to read up some more on the possibilities of `allOf`/`anyOf`.

**Comment by emvau** [comment]
Even if the issue is closed, my question would have the same or similar title, so I decided to append it here.

I got a JSON schema which refers to other JSON schemas, which also refer to other JSON schemas and so on... so it's pretty nested.

=> Now, if I want to override the "required" attribute of one of the nested JSON schemas, would the following structure work, i.e. be valid?
And if not, is there another lean way to express what I want within the OpenAPI definition?

```json
"allOf": [
    {
        "$ref": "https://git.mercedes-benz.com/mavonge/schemas/offer.json"
    },
    {
        "properties": {
            "vehicleOffers": {
                "items": {
                    "properties": {
                        "vehicles": {
                            "items": {
                                "required": [
                                    "options"
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
]
```

**Comment by handrews** [comment]
@emvau the schemas in an `allOf` are each evaluated separately, and must all pass.  There is no "overriding" here, you just add constraints in each branch of the `allOf`.  In practical terms for `required`, this just means that you can't use `allOf` to _remove_ a requirement.

As for nesting, the 2nd schema under `allOf` in your example reads as:

* if the instance is an object, then...
* if it has a `"vehicleOffers"` property which is an array, then...
* if an entry in the array is an object with a `"vehicles"` property which is itself an array, then...
* if an entry in the `"vehicles"` array is an object, then it must have a property named `"options"`

The reason for all of the ifs is that `properties` and `items` do not force the instance to be of type object or array, respectively.  They apply only if the instance is of the appropriate type.  To force the types throughout, you need to set `type` (or maybe it is already set in the `offer.json` schema, in which case you do not need to re-set it in the other schema.  This is type-related behavior [covered in the JSON Schema specification](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-4.1).

Note that requiring `"options"` at the deepest level does not cause any higher level properties to be required.  You would need to set `required` at each level to do that (and presumably `"minItems": 1` on arrays if you want to ensure there is always at least one vehicle in a vehicle offer).

**Comment by alexlren** [comment]
just in case someone is looking for a solution to override a schema easily:

you can use [swagger-cli](https://www.npmjs.com/package/swagger-cli) and mix references

MySchema.yaml
```
type: object
properties:
  foo: 
    type: integer
  bar:
    type: integer
required:
  - foo
  - bar
```

src/spec.yaml
```
patch:      
  summary: Update something
  requestBody:
    content:                                     
      application/json:
        schema:
          type: object                                                                                                                                                                                             
          properties:
            $ref: ../components/schemas/MySchema.yaml#/properties
```


```
npx swagger-cli bundle --dereference -o ./out.yaml -t yaml src/spec.yaml
```

The reason for doing this is that it allows to have your schema properties only in a single file instead of dispatching properties everywhere (which make things complicated when adding or removing properties)
