### ISSUE TITLE
link object scope

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#1593]
am i correct to assume that currently link objects are just per response? if so, i am wondering if it might be useful to be able to support a different scope for link objects?
for example, it might be useful to be able to easily say that a `home` link (proposed in https://github.com/mnot/I-D/issues/41 and documented at https://mnot.github.io/I-D/json-home/#link-relation) should be considered present in all responses.
this would complicate the processing model because then the *effective* response of an OpenAPI -described API would be the union of the received response, plus all added link object links that apply to the context of the response. but it would be a rather powerful to support hypermedia in a way that allows OpenAPI to support links without requiring them in all responses.

**Comment by tedepstein** [comment]
@dret, I don't believe there is currently any way to specify links at the path item or API level. It's strictly response-level for now. 

However, you can define reusable [Link Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#linkObject) in `/components/links` and reference these in the response links. 

> this would complicate the processing model because then the _effective_ response of an OpenAPI -described API would be the union of the received response, plus all added link object links that apply to the context of the response.

Note that inclusion of links has no effect on the actual response payload or response headers. Links are design-time metadata, providing information that clients can use to present and/or traverse links to other resources.  The client must have access to the OpenAPI document (or to some link-aware artifact generated from the OpenAPI document) in order to comprehend these links. 

Each link is defined by a [runtime expression](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#runtime-expressions) that can include static text and/or references to information in the request or response. 

You're right to say that allowing links at API-level, path-level or method-level incurs some added complexity. But that complexity would fall on the client, who has to collect the full set of applicable links from all of the containing contexts. It wouldn't have any effect on the response sent from the server.
