### ISSUE TITLE
How to define "additionalProperties" one as string other as array under the same object

### ISSUE THREAD

**Issue by kjapati** [OAI/OpenAPI-Specification#1623]
I am looking for the json structure of the below kind using "additionalProperties" under metadata tag.

```json
{
  "ingestRequest": {
    "document": {
      "metadata": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string",
        "additionalProp1": [
          {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
          }
        ],
        "additionalProp2": [
          {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
          }
        ],
        "additionalProp3": [
          {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
          }
        ]
    }
    }
  }
}
```

using of "additonalProperties" more than once is not working as usual. Any workaround is helpful.

**Comment by MikeRalphson** [comment]
Do you really have `additionalProp1` appearing more than once in your JSON instance, once as a string and once as an array? In this case the behaviour of JSON parsers will be [undefined or 'unpredictable'](https://tools.ietf.org/html/rfc8259#section-4).

If you mean something else (e.g. that `additionalProp1` may be either a string **or** an array, or `additionalProp1` represents two different property names, could you amend your example?

As you note, use of `additionalProperties` more than once in a JSON schema will usually fail, for exactly the same reason. `additionalProperties` defines **a** single sub-schema which constrains **all** of the additional properties not already covered by the schema definition.

This is also more of a generic JSON schema question, rather than one which (as yet) relates to the OpenAPI specification.

**Comment by kjapati** [comment]
Thanks Mike. I mean to declare name:value pairs as string type and followed by array type using the additionalParameters option in the yml.

something like below :

{
  "ingestRequest": {
    "document": {
      "metadata": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string",
        "CustomerDetails": [
          {
            "CustomerNr": "12345",
            "FName": "ABC",
            "LName": "XYZ"
          }
        ],
        "CustomerDetails": [
          {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
          }
        ],
        "AddressDetails": [
          {
            "address1": "xyz",
            "address2": "pqr",
            "postcode": "12234"
          }
        ]
    }
    }
  }
}

Structure :

![image](https://user-images.githubusercontent.com/40746370/42149655-6d037416-7e1a-11e8-8975-d3dc4664b73e.png)

**Comment by kjapati** [comment]
ingestDocumentMetadataRequest
     document
          metadata
               <<name>>: <<value>> (key/value pair)
               <<name>> (array object)
                    <<name>>: <<value>> (key/value pair)

**Comment by handrews** [comment]
@kjapati in OAS 3.0, you can do something like:

```JSON
{
    "additionalProperties": {
        "oneOf": [
            {
                "type": "string"
            },
            {
                "type": "array",
                "items": {
                    ...
                }
            }
        ]
    }
}
```

If this answers your question, please close out the issue.  You are also welcome to bring JSON Schema questions to the [JSON Schema slack workspace](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg)

**Comment by MikeRalphson** [comment]
Ping @kjapati

**Comment by handrews** [comment]
It's been more than a year, closing.
