### ISSUE TITLE
Array of Polymorphic Schemas

### ISSUE THREAD

**Issue by srilman** [OAI/OpenAPI-Specification#1627]
Hi. I've seen this issue in other places (like https://stackoverflow.com/questions/41096136/define-array-of-multiple-models-in-swagger-2-0) but they are either not up to date or can not confirm their answer (because the swagger editor doesn't this feature).

So right now I currently have the following three schemas, `Pet`, `Cat`, and `Dog`, where `Cat` and `Dog` are inheriting from `Pet` using the `allOf` tag, as seen below.

```yaml
components:
  schemas:
    Pet:
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          example: Cat
          enum:
            - Cat
            - Dog
      discriminator:
        propertyName: type
      type: object
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - required:
            - sleep
          type: object
          properties:
            sleep:
              type: boolean
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - required:
            - play
          type: object
          properties:
            play:
              type: boolean
```

What I am trying to figure out is whether or not it is possible to pass in an array of both Cats and Dogs into a request body, and how I would do so. I thought because both classes inherit from Pet, I could do something like:

```yaml
openapi: 3.0.0
paths:
  /store_config/:
    put:
      summary: Modify Current Pet Config or Send New One
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - store_name
                - pets
              properties:
                store_name:
                  type: string
                pets:
                  type: array
                  items:
                    $ref: '#/components/schemas/Pet'
      tags:
        - default
```

Does an array of type Pet allow including any object that inherits from Pet or just objects that are the type Pet?

Note: In this example, the only reason the Pet schema exists because I saw in other places that this method should work (even though I am not sure). I only need the Cat and Dog schemas, so if a simpler method exists, I would rather not use an extra schema. Thanks!

**Comment by Relequestual** [comment]
`items: { anyOf: [{ $ref: cat}, {$ref: dog}] }`

I realise that's not proper JSON, but I hope that gives you enough to go with. Think of it as sudo JSOn.

**Comment by handrews** [comment]
@srilman that solution will ensure that everything in the array is a valid Pet, and since you have (correctly) ensured that all Cats and Dogs validate as Pets, that will work.

If you want to ensure that everything in the array is either a Cat or a Dog, then you need to use `oneOf` or `anyOf`, as @Relequestual suggested.

If this answers your question would you please close it out?  You are also welcome to come and discuss it further on the [JSON Schema slack workspace](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg)

While `discriminator` is not part of JSON Schema proper, we're happy to discuss OpenAPI's dialect as well.

**Comment by handrews** [comment]
Over a year since answered, closing.
