### ISSUE TITLE
Q: Specifying a Content-Type header on GET requests

### ISSUE THREAD

**Issue by lorenzleutgeb** [OAI/OpenAPI-Specification#1628]
Hello!

I would like to describe an API that requires `Content-Type: x` on a GET request. It seems that the only possibility to adjust that header is via `<path>.[post/patch].requestBody.content.<contentType>` ([example from the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operation-object-example)). It is even [explicitly excluded from parameter objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-10). However, for the case of a GET request there is no request body, so I would not have this element in my specification.

In my particular case, this restriction comes from the design guidelines of [JSON API](http://jsonapi.org/format/#content-negotiation), but I consider this not directly relevant.

Can this case not be described by OpenAPI? If not, is there a particular reason, or would it be possible to allow it in the future?

**Comment by MikeRalphson** [comment]
From the JSON API guidelines you linked to:

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.

My reading of that is that there is no **data** (certainly no JSON API formatted data) because there is no **request document**. Therefore the `Content-Type` header does not need to be sent. Is there any possibility the API does not in fact require this header, or can be changed?

You're right that this case is cannot be described by OAS 3.0, and the restriction on `GET` `requestBodies` is to avoid attempting to describe API behaviour which the HTTP spec says is undefined. The restriction on specifying `Content-Type` as a 'manually' defined header is also to ensure there is no ambiguity as to what mechanism is supposed to set this header.

**Comment by lorenzleutgeb** [comment]
OK, probably are you right. The generated client that I used was misbehaving by sending a Content-Type on a GET. Sorry to have disturbed you.

**Comment by MikeRalphson** [comment]
No problem, we're all here to help.
