### ISSUE TITLE
Grouping paths by tags

### ISSUE THREAD

**Issue by Thorgard** [OAI/OpenAPI-Specification#1642]
https://swagger.io/docs/specification/grouping-operations-with-tags/

Is this possible to set tags on paths instead of every operation? It seems more logical to me to set tag per path and not per operation. From MVC perspective tag = controller name

Wouldn't it be better to support grouping out of the box instead of using tags? It says that tags can be used for different purposes. So my tool that uses tags won't work with every specification. 

It's pretty confusing and complicated to parse it as it is now. It would be much better if paths had some groups or wrappers so they would resemble more controllers and actions from MVC pattern.

**Comment by silkentrance** [comment]
Don't paths already have a physical grouping? Why don't you use that instead of adding yet another indirection. As for the tags, they allow you to have a different view on your operations across multiple paths, say

/path1/manage (with tag: manage)
/path2/manage (with tag: manage)

Here, you can group all management related apis directly under one logical section in for example the documentation.

Or am I missing something?

**Comment by Thorgard** [comment]
@silkentrance You're right.
