### ISSUE TITLE
Body parameter in v3 has no name

### ISSUE THREAD

**Issue by xxxcodeine** [OAI/OpenAPI-Specification#1643]
https://swagger.io/docs/specification/describing-request-body/ 

> Body and form parameters are replaced with requestBody.

In v2 body parameter could have a name. In v3 there's no name at all which is a showstopper for any kind of generation tools and for whoever used the name.

**Comment by darrelmiller** [comment]
@amd64x An operation can only have one request body and parameter names are scoped to the operation, therefore a code generation tool could choose any constant name e.g. "body", "payload", "content" as the parameter name for the request body in a method.  Is there a reason why that wouldn't work for your scenario?  Is there an advantage to being able to choose a different name? For most scenarios, the path is a strong indication of what the body contains, providing another place to name it seems redundant.

**Comment by amd64x** [comment]
@darrelmiller I still think it is useful to have a name like it is in v2. In some cases, a type is not enough to understand what is it for. What if you have just some primitive type like `int` or `string`? I don't think naming it "body", "payload" or "content" would mean anything to me.

**Comment by darrelmiller** [comment]
@amd64x  If it is not clear what the intent of body is from the name of the resource (i.e. the path) then I would recommend improving the path.  When you do a GET on the resource, there is no parameter name, so if the path isn't clear, how would you know what you are GETting?

In the two years since this change was made, this is the first time someone has raised this as an issue.  I realize it requires thinking about request body a little differently, and that takes a bit of getting used to.  However, I have seen so much confusion because people try and treat bodies as "parameters" and they behave very differently in HTTP, so pretending they are like URL parameters is actually harmful.

**Comment by amd64x** [comment]
@darrelmiller 

> I have seen so much confusion because people try and treat bodies as "parameters" and they behave very differently in HTTP, so pretending they are like URL parameters is actually harmful.

It's pretty much like how all MVC frameworks work, for example in ASP.NET you have `[Body]` parameter attribute. In API clients you most probably pass body as a parameter so yes it's pretty confusing to think of it differently.

**Comment by tomchristie** [comment]
Just signalling that I'm running into this issue too.

Supporting a `name` to requestBody allows auto-generated or dynamic client libraries to use a more semantically relevant parameter name.

Being able to generate clients that can reference an operation id and a set of semantically meaningful parameter names is hugely valuable, but at the moment any information that's part of the body of the outgoing request has to be referenced obliquely as `body=`.

**Comment by fragilethoughts** [comment]
@tomchristie Honestly, I've given up on using swagger(now OpenAPI) to auto-generate client libraries. 

It's parseable but you have to define your own schema to parse to. For example, you can't describe generics and so on to generate generic types in strongly-typed languages like C# or Typescript. 

The only thing I find useful is to generate types/DTOs because there are many ways to implement communication (many HTTP libraries) and sometimes it's simply faster to write your client manually. But for that, you could also use protobuf and define your DTOs there. If you use the same language to write your client and server then it's wise to just share models instead of generating (what I do now and I'm more happy)

**Comment by GHakopian** [comment]
+1 on having the name property for auto-generated or dynamic client libraries to use a more semantically relevant parameter name.

**Comment by jokedurnez** [comment]
+1 !

**Comment by iikkamerilainen** [comment]
+1, the parameter absolutely should be nameable for auto-generated clients. My path is "document/{id}/reject", POSTing to it rejects the document, but an optional, possibly long rejection comment text is accepted as a body parameter, and now the parameter is called "body" in my auto-generated client after migrating to OpenAPI 3.

**Comment by darrelmiller** [comment]
@iikkamerilainen   Feel free to add x-Name to the RequestBody object and go write PRs to the client generator tooling to use that name.  If you have success there, then I'll be happy to consider supporting it being added to the spec.  But I'm not going to do the work to add something to the spec that I think is unnecessary and do the work to convince tooling people to implement it.

**Comment by escapin** [comment]
> I have seen so much confusion because people try and treat bodies as "parameters" and they behave very differently in HTTP, so pretending they are like URL parameters is actually harmful.

How do I explain it to the organization I'm doing consulting to?

**Comment by johnwoo-nl** [comment]
Ah yes, I'm also running into this omission in the spec.
Situation: generated server interface is dependent on the generator for giving it a name. This has a few drawbacks:

1. The name may change with a generator update or when switching to another generator, breaking API and requiring the implementation (i.e. the method parameter name) to be updated. This is one technical reason why this is not a generator-specific thing; the body parameter needs to be named in the API. Using something like an x-name which, by the `x-` standard means its generator-specific, doesn't solve it, since all generators would need to agree on the same annotation name, meaning it actually won't be generator-specific anymore, ergo needs to be an API-defined property of the body.
2. The name that my current generator picks is actually a type name, leading to warnings and confusion. You may say, update the generator, but if each one has the same issue, it's actually an API specification issue (see point 1).
3. Like others mentioned, apart from the technical issues there is also a semantic issue; the generated name does not reflect the meaning of the body as it arrives as a method parameter.

The workaround for me for now is to wrap the body in a wrapper DTO (either an inline one with a `title` or a named schema, which the generator will use as parameter type but also as its name, with lowercase first character), which is workable but really not ideal (more boilerplate just to get around a regression in the OAS compared to older versions). I'd strongly suggest listening to developers actually using your standards and the toolchains developed for them, to avoid getting overtaken by others that do [insert Ballmer "developers" chant].

> But I'm not going to do the work to add something to the spec that I think is unnecessary and do the work to convince tooling people to implement it.

That would not have been necessary if the name feature had not been dropped from v2 to v3; all generators respected the parameter names in v2, **because they were part of the spec**. I appreciate that this technical debt now is difficult to fix, but that doesn't change the fact that there is a problem in the v3 spec (and that it actually is in the spec, not the generators, since it is a crosscutting concern for all generators and other consumers of OAS spec files that need to reference the body by name, as apart from other request fields such as path or query parameters).
