### ISSUE TITLE
Specifying dynamic resources enumerating valid values for a given path element

### ISSUE THREAD

**Issue by jerstlouis** [OAI/OpenAPI-Specification#1693]
Say we wanted to list all possible tiling schemes for a given collectionID in:

    /collections/{collectionID}/tiles/{tilingSchemeID}/{zoomLevel}/{row}/{column}.{ext}

Could we somehow describe something like this in a generic API specification?

    {tilingSchemeID} : look at /collections/{collectionID}/tiles/tilingSchemes.json

**Comment by MikeRalphson** [comment]
I am assuming that the list of possible values for `tilingSchemeID` does **not** vary depending on the value of `collectionID` -(because the `collectionID` values would need to be known ahead-of-time) correct me if I'm wrong.

An `in:path` parameter's `schema` can define an `enum` property, with an array of the possible values. You can refer to an external schema object in another document using a `$ref`, but you cannot use a `$ref` in place of just the `enum` property.

You cannot use OAS parameter names as templated variables in `$ref` values or descriptions.

**Comment by jerstlouis** [comment]
@MikeRalphson , the list of possible tilingSchemeID could potentially vary depending on the value of collectionID, yes.

**Comment by MikeRalphson** [comment]
OK - then OAS currently does not have a mechanism for pointing at a dynamic resource which provides the allowable values for a parameter (potentially based on other parameters).

**Comment by jerstlouis** [comment]
Thanks for confirming this. So this is a feature request.

**Comment by handrews** [comment]
This is really a JSON Schema question, and the JSON Schema issue is https://github.com/json-schema-org/json-schema-spec/issues/855

I'm going to close this as OAS 3.1 and later now fully reference JSON Schema, so the appropriate place to discuss this is in the JSON Schema issue.
