### ISSUE TITLE
Examples with Valid Request / Response Pairs

### ISSUE THREAD

**Issue by chatelao** [OAI/OpenAPI-Specification#1742]
Goal: 
- Be able to define 1..N **vaild** request / response pairs as examples.

Use
- This pairs could be used to test the final implementation.
- This pairs could be used to generate easy a some mock for the interfaces.

```
{
  "paths": {
    "/pets": {
      "get": {
        "summary": "List all pets",
        "operationId": "listPets",
        "parameters": "...",
        "responses": "...",
        "examples": {
          "example_one": {
            "request": {
              "parameters": {
                "limit": 10
              }
            },
            "response": {
              "status": 200,
              "headers": {
                "x-next": 11
              },
              "content": {
                "application/json": {
                  "id": 55226688,
                  "category": {
                    "id": 0,
                    "name": "string"
                  },
                  "name": "doggie",
                  "photoUrls": [
                    "string"
                  ],
                  "tags": [
                    {
                      "id": 0,
                      "name": "string"
                    }
                  ],
                  "status": "available"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by MikeRalphson** [comment]
Every [Media Type Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#media-type-object) in OAS v3.0.x supports the `examples` property. Thus you can embed examples in `requestBodies`, `responses` etc. `examples` is also supported within `Parameter Objects`.

Could you see if this satisfies your requirement?

**Comment by MikeRalphson** [comment]
I'm not sure what you mean by either "consistent" or "all". Could you expand a little?

**Comment by MikeRalphson** [comment]
I'm not sure what you mean by either "consistent" or "all". Could you expand a little?

**Comment by darrelmiller** [comment]
@chatelao Correlating response bodies with request bodies within a single operation is a design smell.  It encourages coupling between client and server based on out-of-band knowledge, which reduces the evolvability of a service.  Responses should be self-descriptive.  You shouldn't need to know what the request was to understand what the response means.  The request should describe the intent of the client.  Defining a contract that says exactly how a server must respond to a client's specific request is highly problematic.  I know many people want to do it.  I generally try and discourage people from doing it because that's not HTTP is supposed to work.

**Comment by handrews** [comment]
Sounds like this was definitively answered in 2018, closing.

**Comment by ambition-consulting** [comment]
This answer is absurd, and the request still valid:
- Good testing requires Mocks, which are reallt just request/response pairs.
- Providing instances of a contract does not define the contract, but provides sample data to be used for good testing, documentation etc.. That's why it's called example, and not schema.
- Not following this request effectively stops the integration of OpenAPI into automated Unit Testing. And wouldn't it be nice to not just write down some specification, but also automatically validate that it actually also works?
