### ISSUE TITLE
Should API consumer send id_token or access_token for openIDConnect security scheme

### ISSUE THREAD

**Issue by lkgarrison** [OAI/OpenAPI-Specification#1751]
With the addition of the [openIdConnect](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object) security scheme object type in v3, I find the spec ambiguous on whether the API consumer should be sending an `id_token` or an `access token` to the API. 

From my understanding, this may not have been an issue in v2 since there was only `oauth2` instead of `oauth2` and `openIdConnect`. Since OpenIDConnect flows [can provide both id tokens and access tokens](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse), which token type should be sent to the API? Does specifying an auth type of `openIdConnect` imply that an `id_token` should be used, while `oauth2` implies that an `access_token` should be used? If so, I think this information should be explicit in the spec instead of implied. If not, could you comment on whether or not consumers should always be sending an `access_token` for both `oauth2` and `openIdConnect` security scheme types?

**Comment by lkgarrison** [comment]
Whether the consumer should be sending an `access_token` vs an `id_token` seems like an important part of the spec - can anyone comment on whether OASv3 can/does tell the consumer which token type should be sent to the API?

**Comment by pleothaud** [comment]
Hi there,

The problem is complex (is the OpenID Connect Provider also an OAuth Authorization Server for the API? Are the access token opaque tokens or JWTs? etc), but in short id_tokens are JWTs intended for Cleint Applications use, not for Resource Server (API) use. 

id_tokens are there so that the Client Application can authenticate the end-user, they contain potentially sensitive information about the end-user that you as the CLient Application developer/owner might not be allowed to transmit to the Resource Server (the API).

So don't send id_tokens but access_tokens to the API. The API can then invoke the token introspection endpoint to get information about the end-user and the scopes the client application requested.

Hope it helps,

Phil

**Comment by lkgarrison** [comment]
Thanks for the detailed reply Phil. It would be great to see this guidance appear within the spec itself to help eliminate confusion for API consumers.

**Comment by kishoreaetna** [comment]
Yes,  it would be helpful to include this guidance specs. This is an important aspect that is often not understood.

**Comment by LasneF** [comment]
Following OIDC , and oauth 2  follows the same convention , to make a call on an endpoint ( or to access an API ) , you need to provide the access token 

id token is for identity not for access , it s more or less who you are , bs access token is the actual key to open the door 

on the Identity provider will provide you both in most of the case , if you ask only for id , you cannot use it to access API
