### ISSUE TITLE
$ref value must be accessible URL for external reference?

### ISSUE THREAD

**Issue by Shulamite** [OAI/OpenAPI-Specification#1887]
Based on JSON reference spec, the $ref value is an URI, which by definition is a resource identifier only, and is independent of access.
It seems it is valid to use a well formed URI, but not an accessible URL (assuming http).
However, if it is not a valid URL for external reference, how would different tools resolve the references?

**Comment by whitlockjc** [comment]
URLs are resource locators and URIs are identifiers.  But URIs can also be locators which means they can be URLs as well.  So JSON Reference values _(`$ref`)_ being a URI allows for addressing both local _(`#/components/schemas/person`)_ resources and remote  _(`https://example.org/schemas/person.json` or `https://example.org/schemas/objects.json#/person`)_ resources.  What's the rub?

**Comment by whitlockjc** [comment]
Maybe we can document things better to say that when `$ref` **is not** a URL, we expect it to be a URI in the format of a JSON Pointer _(the URI fragment identifier representation: https://tools.ietf.org/html/rfc6901#section-6)_.

**Comment by handrews** [comment]
`$ref` takes a URI.  Some URIs are also URLs.  I don't see a contradiction here.  There is no need to call out JSON Pointers specifically for `$ref`, as fragment syntax is a function of the target resource's media type.  The OAS document media type uses JSON Pointer fragments, so that follows naturally.

**Comment by whitlockjc** [comment]
I removed my comment, I had the same thought there is no contradiction but I overthought it.

**Comment by Shulamite** [comment]
Is it accurate to say that URI must be addressable?

**Comment by handrews** [comment]
@Shulamite there are no restrictions on the value of `$ref` other than "it MUST be a URI reference" (meaning it can either be a full URI starting with a scheme, or a relative URI).  Some sorts of URIs are more convenient than others, but all are valid.

**Comment by handrews** [comment]
Some sorts of URI will also no doubt have much better tooling support.

**Comment by handrews** [comment]
@darrelmiller @webron @tedepstein I think we touched on this related to #2092.  There is a valid reading of JSON Reference that requires the value of `$ref` to be a URL rather than a URI, but in OAS 3.1 with the new JSON Schema that is relaxed, and any valid URI is legal.

So I think this should be closed as answered in 3.0 and fixed in 3.1?  Or maybe tracked under #2099 if we think we need to explain this further in OAS 3.1 and can't just fold it into #2092.

**Comment by philsturgeon** [comment]
I vote for "fixed in v3.1" and close this.

**Comment by handrews** [comment]
@Shulamite for OAS 3.0.x, the relevant language from the [JSON Reference draft](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3) is (bolding added):

> The "$ref" string value contains a URI [RFC3986], which identifies the **location** of the JSON value being referenced.

Per discussion with @darrelmiller in a recent TSC meeting, that is interpreted to require a URL, not just a URI.  So OAS 3.0.x does not allow non-URL URIs, and therefore doesn't need to explain how one might resolve them.

In OAS 3.1 that draft is no longer referenced, and we are tracking the implications of that through #2099 and related issues.
