### ISSUE TITLE
Ambiguous schema type considered harmful?

### ISSUE THREAD

**Issue by kerrykimbrough** [OAI/OpenAPI-Specification#1912]
Any place where your OpenAPI spec specifies a [Schema Object](https://swagger.io/specification/#schemaObject), the schema need not define a "type" property. In which case the type of instances that can be validated is ambiguous. Any type of instance can be accepted, so long as it matches the schema keywords that apply. Indeed, if the instance type is X and the schema doesn't define any X keywords, the instance is always accepted, no questions asked!

This seems like a risky design practice, because it makes the API contract much more complex. Any implementation that is not prepared to handle all possible valid instances could no longer rely on schema validation to screen out errors. 

But here's my question: Do you find such ambiguous type schema useful? Do you consciously exploit this feature of schema validation?  If so, how do you cope with the extra implementation complexity? Or do you consciously avoid ambiguous type schema?

I'm asking because I'm developing tools to automatically translate OpenAPI specs into test cases. Do these test cases need to verify all the possibilities allowed by an ambiguous type schema? Or should these tools flag ambiguous schema types with an error or a warning?

**Comment by philsturgeon** [comment]
We had this chat over on Stoplight support channels, did you get an answer you were looking for? 

By default anything is allowed. Validation rules are just there to limit that. Different people want different levels of strictness, some people want to allow additional properties and some do not. Some people want to be very restrictive over formats and some do not. Building tooling should respect that, and generally it is not a problem. 

Spec says something is an array? Look for the array specific validations.

Spec says its a string? Look for the string specific validations.

You just do what the spec says, and if the spec doesnt have opinions neither should your tool. 

Nothing harmful about it. People are as specific as they want to be. 

If any particular API Design Governance team has concerns, they should add [Spectral](https://github.com/stoplightio/spectral) with a rule demanding people add type. Otherwise it is a feature not a bug.

**Comment by kerrykimbrough** [comment]
@philsturgeon I recognize the validity of what you're saying. Which is actually the motivation for my question, which is of a pragmatic nature. Given the broad range of instances that can be valid w.r.t. a type-ambiguous schema, does anyone ever do that intentionally, i.e. with the intention that the system promises to accept everything in that range? 

My hypothesis: No, behind the surface contract of the type-ambiguous schema is a hidden contract w.r.t. which a much smaller subset of that range is actually valid. But for one reason or another, the API designer did not make actual contract explicit in the spec. You could say that this situation, while perhaps not "harmful", is contrary to the purpose for OAS. But does anyone do it on purpose?

**Comment by philsturgeon** [comment]
Nobody is able to answer your “does anybody do X” because nobody speaks for everybody. You can just build tooling which respects the specification, or you can build tooling which ignores the specification and does its own thing. Those are the only two options really.

Maybe just follow the spec, or push to change the spec if it’s actually a problem? To me it’s just an If statement so I’d go with the former.

**Comment by kerrykimbrough** [comment]
No further response needed
