### ISSUE TITLE
$ref a field in a referenced file

### ISSUE THREAD

**Issue by Monkleys** [OAI/OpenAPI-Specification#1927]
I can't seem to get this to work, I've tried every way I can think of. Yes, I have checked the docs, it doesn't go into this much detail. I'm starting to doubt if this is possible or not.

This is example below works perfectly.

```
api_fetch:
      $ref: './components/schemas/api_fetch.yaml'

combine:
      type: object
      properties:
        name:
          type: string
          example: just an example
      fetch:
      $ref: '#/components/schemas/api_fetch'

```

However, this does not (trying to reference a field in the file):

```
api_fetch:
      $ref: './components/schemas/api_fetch.yaml'

combine:
      type: object
      properties:
        name:
          type: string
          example: just an example
      fetch:
      $ref: '#/components/schemas/api_fetch/properties/fetch'

```

The contents of api_fetch:
```
type: object
  properties:
    fetch:
      type: string
      example: just an example
```

I have even tried this:

```
combine:
      type: object
      properties:
        name:
          type: string
          example: just an example
      fetch:
      $ref: './components/schemas/api_fetch.yaml#/properties/fetch'
```

If I put the contents of `api_fetch.yaml` into the same file and reference the field, it works perfectly. I know the suggestion would be to just put it all in the same file. However, this API file is getting very long, and it's becoming difficult to open and manage.

Is it possible to do this, or am I doing something wrong?

**Comment by tedepstein** [comment]
@Monkleys , I noticed some incorrect indentation in your examples. 

In all cases, `$ref` should be indented under `fetch`, like this: 

```
combine:
      type: object
      properties:
        name:
          type: string
          example: just an example
      fetch:
        $ref: '#/components/schemas/api_fetch'
```

Does that fix the issue for you? 

Aside from that, your first example relies on a certain order of resolution. The `api_fetch` external reference has to be resolved first, so that the JSON pointer `'#/components/schemas/api_fetch/properties/fetch` can be resolved. I'm not sure whether this behavior is standard. 

The second example is just a relative external reference with a JSON pointer fragment: 

```
$ref: './components/schemas/api_fetch.yaml#/properties/fetch'
```

I would expect this to resolve correctly. If it doesn't, it sounds like this is most likely a bug in the implementation you're working with. I would raise this question with the provider of that implementation. This project is specifically with the OpenAPI specification itself.

**Comment by Monkleys** [comment]
The indenting is just me screwing it up when I created this issue. It doesn't fix the issue. 

The external reference does precede the reference with the JSON pointer fragment. 
Thank you for confirming that this should be working, I've been trying to wrap my head around why it doesn't. It seems it might just be a bug in the Swagger Pycharm plugin.
