### ISSUE TITLE
Why can response objects have multiple schemas?

### ISSUE THREAD

**Issue by vvanpo** [OAI/OpenAPI-Specification#1960]
The `content` field of a [response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#response-object) consists of a map of media types, each media type object having it's own schema definition. This implies that for a given response, the structure of a resource could adhere to a completely different schema depending on the result of content negotiation. I won't claim to be an expert on HTTP or media types, but that doesn't make a whole lot of sense to me. A media type defines how a given resource representation should be parsed, I would think that the parsed result should be the same regardless of what media type was used to represent it.

A slightly tangential question: why do parameters allow the same `content` field? If a media type defines the format of a _resource representation_, then does it really make sense to encode a whole or partial resource representation through a resource *identifier* (i.e. a URI via query string or path segments)? Or through message metadata (headers)?

**Comment by cebe** [comment]
> This implies that for a given response, the structure of a resource could adhere to a completely different schema depending on the result of content negotiation.

If you allow to retrieve a resource in JSON or as PDF file, you can't apply the same schema you have for the JSON response to the PDF response.

If you allow JSON or XML, I would expect the schema to be the same, but there are cases where it may be different so the specification language allows that.

did not understand what you mean with the second question.

**Comment by vvanpo** [comment]
> If you allow to retrieve a resource in JSON or as PDF file, you can't apply the same schema you have for the JSON response to the PDF response.

Are you sure about that?

JSON schema *requires* that the data it is validating is compatible with the JSON data model. If your API is describing a given resource representation using JSON schema, then it is expecting the client to be able to parse it into a JSON-compatible object. If you are somehow able to parse a PDF into a JSON compatible object, and then were to re-encode it as JSON for some reason, why should that resulting document ever be different than the JSON representation of the same resource as produced by the server?

For my second question: my point is that HTTP defines semantics for passing partial or whole representations via message payloads only, there are no semantics for passing resource representations through resource identifiers or HTTP headers.

**Comment by handrews** [comment]
@vvanpo Header parameters can use media types such as `application/jwt` which works just fine with JSON Schema since it is an encoded JSON document.  Something having a schema doesn't mean it's a resource representation, it just means it's structured information.

For the multiple response media types, I've seen data offered in both JSON and CSV format, where the JSON format offers better structure but the CSV format offers the essentials.  Those would be described differently (CSV would be modeled as an array of arrays, I guess).  There are all sorts of media types, and it's entirely possible to have different structured representations with identical semantics.

I think that covers the question so I'm going to go ahead and close it, please re-open/re-file if I missed something.
