### ISSUE TITLE
3.0.2: Advertises support for JSON Schema Draft-05 despite advice to the contrary.

### ISSUE THREAD

**Issue by Capstan** [OAI/OpenAPI-Specification#2049]
re: http://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-draft-05

[schema.json](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json) correctly references Draft-04 in its `$schema` property, but the [spec's Data Types section](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types) says that they're based on [JSON Schema Specification Wright Draft 00](https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.2). [The JSON Schema org specifically advises not to implement or advertise support for this draft.](https://groups.google.com/d/msg/json-schema/CrFKUcbRd0k/qH53qdFxAAAJ)

If OpenAPI doesn't use anything specific from Draft-05, I would suggest amending the spec to just refer to Draft-04 and bring it in-line with the use from the published schema.

Related to #1032.

**Comment by Relequestual** [comment]
It says based on.
They also detail the differences.

Is there a specific problem this is causing you here or are you just thinking about semantics?

**Comment by Capstan** [comment]
Just semantics. If you want to resolve in 3.1 and close this as Won't Fix, that seems reasonable to me. I was just chasing down what seemed like disparities between the spec and its use in Kubernetes.

**Comment by Relequestual** [comment]
OK. I think this is likely to be resolved before 3.1.
Think of draft-5 as a clarification on some ambiguities in darft-4. It's meant to be functionally the same, hence we don't want anyone (now) to implement it, which would suggest there were differences.

**Comment by handrews** [comment]
@Capstan several things (I'm another of the JSON Schema editors, and I work with the OpenAPI Technical Steering Council on convergence between JSON Schema and the OpenAPI Specification):

* The correct meta-schema for `draft-wright-json-schema*-00` is the `draft-04` schema.  There are no meta-schema-level changes between the draft-04 core and validation specs and those.  There will never be a `draft-05` document on json-schema.org because if there were, someone would attempt to implement it separately, which would be bad.  Even if it worked as a redirect, that would imply that the URI was usable, and it explicitly is not.  It also expired several years ago, and everyone else who is still actively implementing JSON Schema has moved on anyway.

* The OAS Schema Object forbids `$schema`, so there is nowhere that a `draft-05` meta-schema URI could possibly be used even if it existed.

* The OpenAPI TSC is well aware of this issue, it was discussed between them and us (JSON Schema project) at the time, and was at that point the only available way to reference a non-expired IETF draft and a usable meta-schema.  It's not ideal, but it was the only thing that fit the requirements.  (I'm glossing over some things, but those things are not worth re-opening)

* The JSON Schema draft cannot be changed in an OAS 3.0.x patch release due to versioning constraints.

* OAS 3.1 will move to JSON Schema draft `2019-09` with full compatibility (the OAS 3.1 Schema Object will support a superset of JSON Schema `2019-09`, and Schema Objects that only use `2019-09` features will behave identically to regular JSON Schema).  See #1977 for details, as well as #2050 and #2046 for related work in 3.0.3 ensuring a proper migration path.

So nothing is going to be done with this that isn't already being done, and I recommend that you or the TSC close this (@Relequestual and I cannot as this is not our repo) and just keep an eye on 3.1 via the referenced issues and PRs, and the overall 3.1 tracking issue #2025.

**Comment by Capstan** [comment]
@handrews Thanks so much for the detailed reply! I'll close this out.

Wrt the OAS Schema Object, I had not thought to use it in an instance of said object, but simply in the schema.json that represents OAS itself. But that's moot given the other advice around not to use draft-5.
