### ISSUE TITLE
how to prepend xml version and encoding

### ISSUE THREAD

**Issue by bglmac** [OAI/OpenAPI-Specification#2213]
i am using swagger in golang, and here's the endpoint:
```
"/xmltest":{
      "get":{
        "produces":["application/xml"],
        "operationId":"xmltest",
        "responses":{
          "200":{
            "description":"OK",
            "schema":{
              "type":"array",
              "items":{
                "$ref":"#/definitions/Channel"
              },
              "xml":{"name":"Channels"}
            }
          }
        }
      }
    }
```
and definition:
``` 
"Channel":{
      "type":"object",
      "xml":{"name":"Channel", "version":"1.0.0", "encoding":"utf-8"},
      "properties":{
        "id":{
          "format":"int32",
          "type":"integer"
        },
        "name":{
          "type":"string"
        }
      }
    }
```

in the response, i am always get `<Channel><ID>1</ID><Name>Abc</Name></Channel>` while i am expecting `<?xml version="1.0" encoding="utf-8"?><Channel><ID>1</ID><Name>Abc</Name></Channel>`, how can i make it happen?

**Comment by MikeRalphson** [comment]
You do not state exactly which tool you're using, but I do think this is a tooling, rather than a spec. issue, so should be raised on the relevant tooling repository.

Just for clarity, the [xmlObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#xmlObject) does not support a `version` or `encoding` field, so this is not going to work.
