### ISSUE TITLE
No support for $comment available in latest JSON Schema Specification

### ISSUE THREAD

**Issue by RitwikChatterjee** [OAI/OpenAPI-Specification#2225]
Hi,
The latest OpenAPI spec doesn't seem to support [$comment core vocabulary ](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.3) available for JSON Schema.

When I have a model/component with $comment, it errors out as:

```
should NOT have additional properties
additionalProperty: $comment
```

**Comment by handrews** [comment]
@RitwikChatterjee Tooling issues (such as what kind of errors are returned) should be opened with the tool's repository.  This is only for the specification.

OAS 3.0 uses an older JSON Schema draft that does not include `$comment`, which is why you are seeing that error.

The next release of OAS (3.1 or 4.0, it's a matter of some debate) will use the latest JSON Schema including `$comment`.  It is nearing release, although of course it will then take a bit longer for tools to catch up.
