### ISSUE TITLE
Remove "nullable" in OAS 3.1?

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#2244]
Now that we have decided to discard SemVer (see PR #2243), IIRC it briefly came up on the last call that we could outright drop `nullable` instead of requiring that both `nullable` and `type: "null"` be supported.

Should we do this?  I'd be happy to write a PR.

**Comment by darrelmiller** [comment]
Now that we allow the Schema Object to allow any unknown property (to enable vocabularies) an instance of a nullable property would not fail validation rules for a 3.1 description.  Be warned thought, tooling might not work as expected because the nullable keyword might not be respected.

**Comment by rwalle61** [comment]
Thanks for this! 

To confirm, how should an openapi doc describe an object with a property 'foo' that can be string or `null`?

```yaml
type: object
properties:
  foo:
    type: string
```

I couldn't find this described anywhere, and OpenAPI 3.1.0 [barely mentions `null`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md). 

Out of interest, is there any summary of why `null` has been removed since [OpenAPI 3.0.3](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-20)?

And fyi you may want to update [this proposal about `nullable`](https://github.com/OAI/OpenAPI-Specification/blob/946f590590af84af7b90e09ecf20e0b345258ef7/proposals/2019-10-31-Clarify-Nullable.md) to clarify that it was rejected :)

(I maintain an OpenAPI tool and [a user has asked](https://github.com/openapi-library/OpenAPIValidators/issues/240) about using nullable)

Thanks again 😄

**Comment by handrews** [comment]
@rwalle61 it's not much mentioned because it's covered by JSON Schema and OAS 3.1 tries to avoid duplicating the JSON Schema spec unless it is needed to explain how JSON Schema and OAS-specific concepts interact.

What you are looking for is:

```YAML
type: object
properties:
  foo:
    type: [string, "null"]
```
That's the string `"null"`, not the value `null`.  The string `"null"` is the name of the type of the value `null`.  The values in the `type` array can be in any order.

**Comment by handrews** [comment]
@rwalle61 also, that `nullable` proposal was for 3.0, and was accepted for 3.0.3.  Subsequently, `nullable` was removed from 3.1.0.

**Comment by rwalle61** [comment]
@handrews perfect, thanks for clarifying!
