### ISSUE TITLE
Open TSC Meeting, Thursday July 2nd 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2273]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Overlays  (JMESPath vs JSONPath) | @darrelmiller / TDC | |
| Validation of overlay design through use as a generic `PATCH` media-type | @MikeRalphson | |
| Update build badge in README.md #2271 | @MikeRalphson | |
| Fix typo in USPTO example #2221 | @philb-lr | |
| Update JSON example files #2268 | @MikeRalphson | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
[JSON Schema]: Should `prefixItems` be `tupleItems`? - https://github.com/json-schema-org/json-schema-spec/issues/933

@handrews mentioned he discussed with people from here at length on the use of `prefixItems` in order to resolve [issue 864 "Split `items` into `items` and `tupleItems`"](https://github.com/json-schema-org/json-schema-spec/issues/864)

Background: [JSON Schema issue 864](https://github.com/json-schema-org/json-schema-spec/issues/864) - [Associated merged PR](https://github.com/json-schema-org/json-schema-spec/pull/925)

**Comment by philb-lr** [comment]
I can't merge #2221, as I don't have write permission.  I encourage you to merge it or close it.  Thanks!

**Comment by handrews** [comment]
> @handrews mentioned he discussed with people from here at length on the use of prefixItems in order to resolve

I think "people" in this case mostly meant @webron, although I vaguely recall running it by the usual suspects on OpenAPI slack.

**Comment by Relequestual** [comment]
In the unlikely event we have time, I'd also like to bring up https://github.com/json-schema-org/json-schema-spec/issues/821

> Clarify which regular expression production rule from the ECMA specification is intended

https://github.com/OAI/OpenAPI-Specification/pull/1987 fixed linking to the right section, but the next question is which EDITION of ECMA is the correct one to reference? is 5.1 still OK to reference? (This is mostly unknown waters for me. Hoping someone knows if this is important or not)
