### ISSUE TITLE
uploading multipart form-data is giving invalid Media Type

### ISSUE THREAD

**Issue by saravanavel891** [OAI/OpenAPI-Specification#2355]
We are using openapi as middle layer between Java REST API and Client.

Request flow: Client -> OpenAPI -> JAVA REST API
Response flow: JAVA REST API -> OpenAPI -> Client

We are getting invalid media type error while trying to upload a xlsx file through openAPI.

**Swagger requestBody configuration**

"requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }

**java is expecting as** 

Content-Disposition: form-data; name="file"; filename="test.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

can someone help us to identify the issue here?

**Comment by handrews** [comment]
@saravanavel891 this repository is for the specification.  Please raise tooling issues with the tooling vendor / repository.

But since I happened to have been working on that part of the spec this week, off the top of my head, assuming you're using OAS 3.0, while what you have probably ought to work as it expects `application/octet-stream` and literally any resource is technically a valid `application/octet-stream`, you might want to use the `contentType` field in an [Encoding Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#encodingObject) to explicitly set the file's `Content-Type` to `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
