### ISSUE TITLE
OpenAPI TSC Meeting Thursday October 1st 2020

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2358]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
3.1 release timing and JSON Schema co-ordination | @Relequestual | |
AOB | | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=org%3Aoai+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
Assuming this meeting issue will get rolled over, I'd like to address, as a priority, the timeline for OAS 3.1.
We, JSON Schema, would really like some sort of answer on this, to help guide who does work, how intesnley, and when.

A non-hard deadline is fine, but a wish is better than nothing for us right now.
It's fine if it's a "We're not sure", or "We'll we would like to publish it in Nov or at least this year".
Some sort of signal if you're willing to wait if we can show solid progress on milestones for 2020-NN.

Currently, to me, it feels like you're willing to wait for some time, but not too long, because you've said "soon".
If YOU as in OAI are willing to be flexible and for it to be a discussion, that's also great. Let's have that discussion (here or on slack DM or a new Github issue).

Communication on this, allowing us (JSON Schema) to formulate some sort of plan, will be a huge help! =]

**Comment by Relequestual** [comment]
Notes from the discussion on the call, cc @handrews, regarding JSON Schema 2020-NN

JSON Schema 2020-NN includes a number of fixes as a result of feedback from OAI team and tooling venders.
it is likely that if 2019-09 is used, ambiguitits and omissions may cause problems for OAS.

- OAI have no specific timescale requirements
- Darrel (boradly OAI) would probably be upset if JSON Schema 2020-NN wasn't released by mid December 2020. _(JSON Schema team would be equally pretty unhappy if that were the case.)_
- JSON Schema expect to realistically take 1-2 months, including 1m (maybe 2 weeks) for final reading and review

Progress on JSON Schema 2020-NN can be seen at https://github.com/json-schema-org/json-schema-spec/milestone/8

**Comment by handrews** [comment]
@darrelmiller OK I'm going to interpret this as "OAS 3.1 final is not expected to go out before mid-December 2020" and if suddenly it is going out sooner we all understand that that will quite likely cause problems.  I would like to get the draft out well before then, but given (waves at everything) it might get delayed until December, and I'm not going to stress about it as long as we can still hit mid-December.
