### ISSUE TITLE
Where is the schema instance for 3.1?

### ISSUE THREAD

**Issue by adamaltman** [OAI/OpenAPI-Specification#2371]
I left a comment [here](https://github.com/OAI/OpenAPI-Specification/pull/2370/files#r502806631), but since the pull request was already merged, I decided to open this issue.

I wonder if this URL should resolve to some content (instead of a 404): https://spec.openapis.org/oas/3.1/schema-object

I was expecting a meta schema object at that URL.

**Comment by MikeRalphson** [comment]
No, JSON Schema vocabularies are referenced by URI not URLs, so this is not expected to resolved. We can probably make this clearer in the spec.

**Comment by adamaltman** [comment]
When I go here: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.5 I can access that URI via my browser and download the meta-schema. I think this is what I find confusing.

**Comment by MikeRalphson** [comment]
The current schema **instance** for OAS 3.0 has an `id` of `https://spec.openapis.org/oas/3.0/schema/2019-04-02` (which is a URI not a URL, as required by JSON Schema). It is currently located at https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json

We can possibly do better in automatically publishing changed schema instances via our `gh-pages` branch which will cause them to show up under the `spec.openapis.org` domain. (PRs from GitHub Actions wizards gratefully received.)

There is no current schema **instance** for OAS 3.1, as that release is still a work-in-progress.

Because of this confusion between the dialect `$schema` value describing the [schemaObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#schema-object) and a schema **instance** I will propose changing the `$schema` value in an upcoming PR.

**Comment by MikeRalphson** [comment]
Linked issue #2314

**Comment by Relequestual** [comment]
> When I go here: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.5 I can access that URI via my browser and download the meta-schema. I think this is what I find confusing. - @adamaltman

Worth noting that JSON Schema 2020-12, while published, hasn't published the associated meta-schema files yet.

Meta-schemas are informative only, and we may also update them (as per the spec) to fix any issues where it doesn't match the spec.

**Comment by MikeRalphson** [comment]
Thanks to work by @jdesrosiers and @philsturgeon we have a first version here https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.1/schema.json
