### ISSUE TITLE
Open TSC Meeting, Thursday 29 October 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2373]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Reserved character issue https://github.com/OAI/OpenAPI-Specification/pull/2218 | | |
| Human vs Machine consumption of OpenAPI | | |
| OpenAPI Usage documentation to a production state?|||
AOB (see below) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=org%3Aoai+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
JSON Schema:
Does anyone understand / care about this issue? https://github.com/json-schema-org/json-schema-spec/issues/833
I personally do not.

**Comment by darrelmiller** [comment]
@Relequestual I almost managed to resist commenting but failed.

**Comment by ncaidin** [comment]
If there is time, can we see if we can come up with a plan to get the OpenAPI Usage documentation to a production state?

**Comment by darrelmiller** [comment]
Human vs Machine:

 Jonathan : 
- Managing complexity via layers
- Can overlays enable this?
- Layers:
    - Info, paths/params/requestBody
    - Responses
    - Schemas

**Comment by orubel** [comment]
Issues mentioned pertaining to 'roles' per enpoint are in #2380 

As per synchronizing your openapi files/state, see this video as to why it is important for all pieces of architecture (even if it is just one server) : https://youtu.be/A_Hozpb9gLc

**Comment by orubel** [comment]
Haven't gotten response from @darrelmiller on his solution from the issue I brought up at meeting so am posting this here...

His solution for #2380 states to put everything in URL which would dictate how the backend needs to work; OpenApi does not dictate how the backend works so this solution is not acceptable. OpenApi (like RAML and API Blueprint) is a REPRESENTATION of the state as it exists at the central version of truth. So this solution does not meet goals and needs of community at large due to:

- forcing one type of encoding for variables (URL vs HEADERS)
- lack of data types for sending variables associated with ROLES (array/list, map, etc) as it is URL encoded
- excessive verbage in that it cannot concatenate data from the 'anonymous' role (should they want to)
- requires different backend mapping/functionality; assumes [RESTFUL vs RPC](https://youtu.be/pTbS3OYWFd4)
- solution doesn't work for PUT/POST

**Thus this FAILS as a solution for issue brought up during meeting**

Even if OpenAPI WAS just a RESTFUL

**Comment by orubel** [comment]
Mr @darrelmiller just stated in ticket #2380 that I sent 'threatening emails' (his words). This needs to be removed please. I would kindly ask for an apology but removal I believe is about all I can expect at this point.
