### ISSUE TITLE
write out the date-time pattern

### ISSUE THREAD

**Issue by delanym** [OAI/OpenAPI-Specification#2374]
What exactly is the regex matching pattern for date-time?

The specification simply points to the RFC3339 page. Its not obvious from reading this page how to validate these fields. The page defers to a further ISO standard, it uses a non-machine readable ABNF notation, and it includes extra exceptions.  
https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

**Comment by karenetheridge** [comment]
Not everything can be expressed as a regular expression.

The date-time format ultimately comes from JSON Schema -- https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.1

**Comment by delanym** [comment]
How should I validate date-time values?

**Comment by ahx** [comment]
@delanym How to validate date-time format is not part of the OpenAPI specification, but it is specified in the JSON Schema specification (see link posted by @karenetheridge or [here](https://tools.ietf.org/html/rfc3339#section-5.6)).

Relying on standard JSON Schema is good, because if you are building a tool on top of OAS, you can use any standards compliant JSON Schema library to handle validation. 🚀 This even got simpler in OAS 3.1.

**Comment by delanym** [comment]
How did it get simpler in OAS 3.1?

**Comment by ahx** [comment]
@delanym Whereas before OAS used it's own flavour of JSON Schema that diverged in quite a lot of cases, OAS 3.1 (RC) uses standard JSON Schema (plus a [hand full of additional keywords](https://github.com/OAI/OpenAPI-Specification/issues/2364)).

**Comment by MikeRalphson** [comment]
Closing as answered. Thanks all.
