### ISSUE TITLE
'Content' per ROLE for API Gateway

### ISSUE THREAD

**Issue by orubel** [OAI/OpenAPI-Specification#2380]
>Per Darrel Miller (minus unhelpful commentary)
>
>- Users of OpenAPI descriptions can choose to use to them to drive infrastructure if >they wish.  Most API gateways I am aware of simply use OpenAPI descriptions to >assist in performing internal configuration.  I have yet to find an API gateway that is >limited in functionality to what OpenAPI descriptions provide.

All OAI MEMBERS use OpenAPI at their API gateway for routing. Routing without checking role related to endpoint means you are not checking 'content' for request/response (see OWASP security issues below)

>- OpenAPI allows attaching roles/scopes to operations.  This is the same security >capability offered by OAuth2 and Bearer tokens https://tools.ietf.org/html/rfc6750

This is outside of context of mentioned issue (of content and routing) for the intents of what Api Gateways (and OAI members) use it for.
 
>- Users are free to place OpenAPI descriptions behind authorization mechanisms that >do security trimming.

Again, submitted issue has nothing to do with authorization/authentication

>- Users are free to define extensions to correlate roles/scopes with schema elements.  >This is not a feature that has had significant community support to consider >standardizing.  This lack of support for this feature does not create a security >vulnerability.  

As shown above, you are misunderstanding issue by relating it to AUTHORIZATION and not ROUTING (which is the REAL ISSUE).This is a misunderstanding of said issue as it has been stated in #1411 again and again.

If you read how people are using it in API Gateway, it is being used for ROUTING TO ENDPOINT POST CHECKING OF SECURITY.

Meaning :
1. Security has been checked
2. Token has been issue
3. Api Gateway now uses OpenAPI to route to endpoint 
4. Gateway does a check for request and response data for endpoint using OPENAPI,  REGARDLESS OF WHETHER:
   - USER has multiple ROLES
   - Endpoints expect different REQUEST/RESPONSE 'content' per ROLE

OPENAPI assumes an 'anonymous' ROLE (which is issued if no token is found on most systems) and as a result, assumes everyone has this ROLE by default when ROUTING. 

This may not be the case when doing the PROCESSING but if it has no way to tell the system that different ROLES should send different request data when ROUTING, it just tells it one thing for everyone.

OPENAPI is promoted for ROUTING at the API GATEWAY both on Swaggerhub and through it many members and as a direct result is in direct violation of several of the OWASP API SECURITY TOP10 rules

- [API1:2019 Broken Object Level Authorization](https://apisecurity.io/encyclopedia/content/owasp/api1-broken-object-level-authorization.htm)
- [API3:2019 Excessive Data Exposure](https://apisecurity.io/encyclopedia/content/owasp/api3-excessive-data-exposure.htm)
- [API7:2019 Security Misconfiguration](https://apisecurity.io/encyclopedia/content/owasp/api7-security-misconfiguration.htm)

A video talking about this issue is here : https://youtu.be/bWVD6Rro04Q

OAI members have admitted on Twitter to using secondary documents at the gateway or **NOT DOING THESE CHECKS AT ALL**! These SECONDARY DOCS then create another document that needs to syncronize with the API server state (see this video : https://youtu.be/A_Hozpb9gLc ) but does not.

This approach is standard in [springboot, spring](https://www.appsdeveloperblog.com/spring-security-secured-annotation-example/) and [django](https://docs.djangoproject.com/en/3.1/topics/auth/default/#the-permission-required-decorator) and many other frameworks and languages

As an example, APIGEE shows in this example how to import an OpenAPI doc to do routing but NOT to check the data per REQUEST/RESPONSE : https://docs.apigee.com/api-platform/tutorials/create-api-proxy-openapi-spec

This is mainly because the OpenAPI doc does not provide the request/response content per ROLE so it would not be possible to check post the security check.

**Comment by orubel** [comment]
So thought I would provide an example of what I am talking about here. So say we have an endpoint where a USER role should only request their own data but an ADMIN ROLE can request anyone they want by sending the UserId.

The USER role should not send a UserId in the request; instead, we get the id from the token.

The ADMIN role can send any UserId they want in the request to get back data.

This would look like this:

```
paths:
  /user:
    get:
      summary: Returns user info.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
	    permitall: []
		application/json:
		  schema: 
                      type: array
			items: 
			  type: string
	    ROLE_ADMIN: [userId]
		application/json:
		  schema: 
                      type: array
			items: 
			  type: string
```

This however DOES NOT cover RESPONSE DATA which still needs to be defined in 'parameters' and givene a section under 'content'.

I would suggest defining a 'request' and 'response' section rather than just genberic 'content' as it is vague.

**Comment by orubel** [comment]
Another reason for doing this is that this creates a 'complete State' document.

Meaning, this document can be used to better:
- syncronize all pieces of the architecture for the request/response (requires separate mechanism at 'central version of truth')
- use to test all endpoints (integration test) from all points of the architecture fo the request/response
- cache state about all endpoints for all points of the architecture

**Comment by darrelmiller** [comment]
Thank you for providing a specific scenario that you are trying to achieve.  I'm not exactly sure what the difference is between the response from you admin vs non-admin request, but here is a description of what it appears you are trying to achieve.

```yaml
openapi: 3.0.1
info: 
  title: Example of using Roles to control access to data
  version: 1.0.0
paths:
  /user:
    get:
      responses:
        '200':    # status code
          description: User name based on userid in token
          content:
            application/json:
              schema: 
                type: string
  /user/{userId}:
    get:
      summary: Returns user name of the provided userid
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      security:
        - myScheme: [ROLE_ADMIN ]
      responses:
        '200':    # status code
          description: User name based on the provided Id
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
      myscheme: 
        type: http
        scheme: bearer
```
In the above example, it turns out that because you chose to use a path parameter to identify the user and because OpenAPI doesn't support optional path parameters, then it is necessary to describe your scenario with two distinct operations.

However, I believe you are also looking for ways to use a single operation and return different response data based on roles.  If that is correct, we can iterate on that and show examples of how that might be possible.

**Comment by orubel** [comment]
PATH does not describe USER; path describe ROUTE. I am describing routing.

You route based on role.

Per the above provided description (if you look above), it describes it as so: 
> 'In the above example, 'permitAll' is a catchall for anonymous role (users without tokens) and all other ROLES wherein 
> ROLE_ADMIN defines 'administrative role' and expects request data for that ROLE (concatenating upon permitAll).'

So as you can see, we are trying to route and send different data per role and get back different request data per role.

**Comment by orubel** [comment]
> However, I believe you are also looking for ways to use a single operation and return different response data based on roles. If that is correct, we can iterate on that and show examples of how that might be possible.

The reason this is necessary is that this one doc should mirror the state of the server and be a duplicate of it at ALL other places that need to check the state: testing, gateway, MQ, etc.

By not having this data, any routing done is passing too much or too little data with each and every request (same for the response). All that is needed is a place (like above) to put the data.

**Comment by orubel** [comment]
@darrelmiller your solution is also asking the backend to do more work when a single endpoint solution is a better engineered solution, less work, less work and less to maintain.

You are asking people to maintain more and code more due to OpenApi's lack of foresight.

**Comment by darrelmiller** [comment]
> After all everyone who has security has ROLES and they are associated with the request/response data. Why is this such a hard issue to grock?

a) That is not true. Not every API uses role based security.
b) Just because they do, doesn't mean the impact of roles needs to be detailed in the OpenAPI description to be a secure API
c) OpenAPI can associate roles to Operations, you just seem to want to ignore that fact.

> I don't need separate servers or endpoints for separate ROLES when they can use the same ones but just request with different data

I never suggested you did.  I explained why I created two operations. Your OpenAPI description was invalid for your scenario. I needed to introduce two operations to handle a resource where the UserId was passed in the path and one where it was passed in the token.
I also, acknowledged that you probably wanted a scenario with just one endpoint and multiple roles.

> OpenApi is GENERATED from the state of the API Server

Nope, that is contrary to the principal of "design first" which is what the API community generally advocates.  You're welcome to choose code first, but you will lose many of the benefits of OpenAPI, which may be why you are seeing a misalignment of our goals and yours.

I think it is quite clear to everyone that there is no security flaw, no matter how many times you post the same assertion on Twitter, LinkedIn and Reddit.  Secure APIs are written all the time without any OpenAPI description and therefore having an OpenAPI description that you consider incomplete cannot possibly introduce a security vulnerability.  An OpenAPI description, is just that. It is a description of an API.  Describing an API does not change the behaviour of the API.

**Comment by orubel** [comment]
> a) That is not true. Not every API uses role based security.
Can you show some examples as I did? ROLE based seems to be the current default in most languages.

> b) Just because they do, doesn't mean the impact of roles needs to be detailed in the OpenAPI description to be a secure API
I showed how **OWASP** disagrees with you and how **DEFCON** has shown this security issue. **Are you saying you are a more knowledgable security expert  than DEFCON and OWASP**?

> c) OpenAPI can associate roles to Operations, you just seem to want to ignore that fact.
Your example did not show that. I explained the issues with your example in detail.

> 
> > I don't need separate servers or endpoints for separate ROLES when they can use the same ones but just request with different data

> > OpenApi is GENERATED from the state of the API Server
> 
> Nope, that is contrary to the principal of "design first" which is what the API community generally advocates. You're welcome to choose code first, but you will lose many of the benefits of OpenAPI, which may be why you are seeing a misalignment of our goals and yours.

**So you are NOW saying that OpenAPI dictates the state of your code**??? That regardless of your annotations and your hardcoded data, OpenApi is the defacto state??? 

**That OpenApi generates your codes state and not the other way around????** Correct me if I am wrong here but that seems to be what you just stated.





> I think it is quite clear to everyone that there is no security flaw, no matter how many times you post the same assertion on Twitter, LinkedIn and Reddit. Secure APIs are written all the time without any OpenAPI description and therefore having an OpenAPI description that you consider incomplete cannot possibly introduce a security vulnerability. An OpenAPI description, is just that. It is a description of an API. Describing an API does not change the behaviour of the API.

**Comment by darrelmiller** [comment]
> I showed how OWASP disagrees

No, you have referenced OWASP issues that are only tangentially related.  I believe you have misunderstood the scenario what they are describing.

> DEFCON has shown this security issue

Perhaps you can find someone else who can describe the problem for you, because to-date, your arguments are unconvincing.

> The endpoint and the data associated to the endpoint is what you are mocking.

When a tool decides to use OpenAPI descriptions for mocking, then yes, OpenAPI is used for mocking.  When an OpenAPI description describes a production API, it is not being used for mocking.  My assumption has been that you are trying to describe security issues with production APIs, not mock APIs.

> So you are NOW saying that the OpenAPI doc generated by the app dictates the state of your code

No, I am not saying that at all.  I recommend that users of OpenAPI either hand write their descriptions, or use tools designed for creating OpenAPI descriptions to create those descriptions.  We recommend those descriptions be created before any implementation code is written.  OpenAPI descriptions are just as valuable an artifact during the design process as they are for augmenting the runtime experience.

> That OpenApi generates your codes state and not the other way around????

I'm not sure where you got that impression.  I don't see anything in what I wrote that would lead you to that conclusions.   Some people do use OpenAPI descriptions for scaffolding API implementations, but those are, by definition only partial implementations of an API.

> you believe that OpenApi DICTATES the state of the app

No I don't believe this and I have never said anything close to this.  While you continue to invent strawmen to tear down, I don't think we are going to make any progress.

The assertion that there is a security flaw in OpenAPI because someone can implement an insecure API that the OpenAPI describes, is equivalent to saying there is a security flaw in a programing language because it can write insecure programs.

An OpenAPI description describes a set of HTTP interactions that are possible with an API.  There is no requirement that the OpenAPI description be an exhaustive description. The API will behave in ways beyond what is described in the OpenAPI description.  The layered architecture of HTTP guarantees that.  It is also true that just because a JSON Schema model says that a property may exist in a response, does not guarantee that it will.  Security concerns, that may be based on roles could choose to exclude certain properties.  There is no requirement that OpenAPI describe this additional security.

If you build API infrastructure that depends on an API description exhaustively describing the behaviour of an HTTP API you are going to find OpenAPI is not the right tool for you.  You will probably find WSDL a better fit.

**Comment by orubel** [comment]
> No, I am not saying that at all. I recommend that users of OpenAPI either hand write their descriptions, or use tools designed for creating OpenAPI descriptions to create those descriptions. We recommend those descriptions be created before any implementation code is written. OpenAPI descriptions are just as valuable an artifact during the design process as they are for augmenting the runtime experience.

Soooo... use a 'generator' prior to writing endpoints to generate an openapi doc from...????? Oh you mean MOCKS. Write MOCKS. You can't implement MOCKS. So again... **The API Server ENDPOINTS ARE the central version of truth in a PRODUCTION SYSTEM**. OpenApi / RAML /API Blueprint were all duplicate state so as to share in a distributed architecture. 

If you are talking about MOCKS and DESIGN, they are not a PRODUCTION / WORKING SYSTEM. I hate to have to spell this out. I mean seriously, we can tell the difference between mock/design and production/working systems right? Why are you trying to have this argument? It's like you are trying to argue just to argue.

> An OpenAPI description describes a set of HTTP interactions that are possible with an API

Actually, if you want to be exact , the doc should '**enable**':
- synchronization across all architectural systems that share the request/response
- testing across all architectural systems that share the request/response
- secure call flow across all architectural system that share the request/response

I find OpenApi doesn't meet ANY of the above. But since you are pushing it as a standard for all the above, I am wanting to help you to improve it so it can be. But yopu seem to believe it already meets all these and have stated in #1411 that you refuse to work with me. So I tend to believe you are still just being argumentative.

But AGAIN... I offer to run a demo of how these flaws exist if you supply the openapi doc. I'll write all the code. Can we agree?

**Comment by darrelmiller** [comment]
>> An OpenAPI description describes a set of HTTP interactions that are possible with an API

> Actually, if you want to be exact , the doc should 'enable':

> - synchronization across all architectural systems that share the request/response
> - testing across all architectural systems that share the request/response
> - secure call flow across all architectural system that share the request/response

LOL.  I tell you what OpenAPI is designed to do.  You tell me I am wrong, despite me having worked on the spec for the last four years. Then tell me what you think it is designed to do and then tell me how bad it is at doing what you think it should do.

Owen, you are looking for an orange and we designed an apple.  I highly recommend that you stop trying to use OpenAPI for what you are trying to achieve.

Peace.

**Comment by orubel** [comment]
I'm going to point something else out that I was going to surprise you with later but may as well just get it over with now.

Take a look at the OpenApi schema for security in association to your 'uri':
```
    get:
      summary: Returns user name of the provided userid
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      security:
        - myScheme: [ROLE_ADMIN ]
```
The parameters are NOT associated with the ROLE

I could call get > security > myScheme but the parameters are NOT associated. I was TRYING to point this out when I stated you were URL encoding everything; it was implied but you didn't see that so I was just going to spring this on you later.

Now. The PROPER way to do this is to have an association with the role (even if their isn't a role):
```
"show": {
"METHOD": "GET",
    "REQUEST": {
        "permitAll":[],
        "ROLE_ADMIN":["id"]
    },
    "RESPONSE": {
        "permitAll":["firstName","oauthProvider","username","password","lastName","oauthId","avatarUrl","email"],
        "ROLE_ADMIN":["passwordExpired","accountExpired","accountLocked","enabled","id","version"]
    }
...
```

**Comment by orubel** [comment]
> > Actually, if you want to be exact , the doc should 'enable':
> 
> > * synchronization across all architectural systems that share the request/response
> > * testing across all architectural systems that share the request/response
> > * secure call flow across all architectural system that share the request/response

You shouldn't be taking offense at this. This is not a personal conversation but a technical one. Please treat it like one. I merely gave a technical response.

I think this is where you are getting off track in that this is becoming personal for you. For me this is a technical discussion and I want it to remain technical.

**Comment by orubel** [comment]
> > > An OpenAPI description describes a set of HTTP interactions that are possible with an API
> 
> > Actually, if you want to be exact , the doc should 'enable':
> 
> > * synchronization across all architectural systems that share the request/response
> > * testing across all architectural systems that share the request/response
> > * secure call flow across all architectural system that share the request/response
> 
> LOL. I tell you what OpenAPI is designed to do. You tell me I am wrong, 

I don't believe I said you were wrong... I merely added my own take. You see. And this is from studying RAML / API Blueprint AND OpenAPI. Yours is just ONE doc of many that is trying to reach an ideal of shared state and has yet to achieve it.

> ... and then tell me how bad it is at doing what you think it should do.

Um ... we are in 'issues' man. This is the place. And you cant take it personal. You have to understand that everything changes and improves. And I may be the guy NOW saying something but its not a reflection on YOU.





You shouldn't be taking offense at this. This is not a personal conversation but a technical one. Please treat it like one. I merely gave a technical response.

I think this is where you are getting off track in that this is becoming personal for you. For me this is a technical discussion and I want it to remain technical.

**Comment by darrelmiller** [comment]
>Actually, if you want to be exact , the doc should 'enable':

This statement infers that you are being exact and I wasn't.  I believe you are the one who is making this personal.

As far as I know "achieving shared state" is not a goal.

I am well aware of your desire to correlate roles with data elements.    But you keep getting distracted by the state synchronization story.

I've never disputed that correlating data elements in a payload with roles might be useful.  It is an extension that I need to investigate because I may need it for my own work..  Where we disagree and keep getting stuck on is the fact that not be able to describe that connection isn't a security flaw.

I didn't take offense, I told you that you seem to be trying to use OpenAPI for something it isn't designed to do.

If you can focus on mapping on roles to payloads, I am prepared to engage.  I'm not interested in talking about "shared state" and "state synchronization" as it isn't relevant to the OpenAPI specification.

**Comment by orubel** [comment]
> This statement infers that you are being exact and I wasn't. I believe you are the one who is making this personal.

Only if you want to interpret that way.

> As far as I know "achieving shared state" is not a goal.

So you are saying you are WANTING OpenAPI to be in a different STATE that the API Endpoints?????

**Comment by darrelmiller** [comment]
> Previously you said OpenApi handled this. I just showed that it didn't. 

I said OpenAPI can correlate roles to Operations.  OpenAPI currently doesn't have a way to correlate Roles with data elements.  It probably never will because the extension is most likely going to be an extension to JSON Schema, not OAS.  Your example is overly simplistic because it only shows simple properties in a response.  That's not going to be sufficient when the payload contains nested objects.

> Are you saying they should just all wait around until YOU DECIDE until you find it useful???

If you had read carefully you would have seen I said "extension".  Anyone can add extensions.  That's how we recommend people prototype new features.  By creating extensions that solve the problem.  Literally all you have to do is add x- in front of the property you think is missing.  If it solves the problem and tooling adopts it, then it is really easy for us to add it to the spec.

Why are you taking offense at my suggestion that one of your requests holds merit?

> So you are saying you are WANTING OpenAPI to be in a different STATE than the API Endpoints?????

That's not what I said.  You are creating another strawman.  Your use of the word state is very ambiguous. This is why we stopped talking 3 years ago.  You use words in ways that mean specific things to you, and you assume other people share that understanding.

As I said, I'm not interested in debating what "synchronizing state" means to you.  The information that is contained in an OpenAPI description should be accurate.  However, the API may have behavior that is not described in in the OpenAPI description.

**Comment by darrelmiller** [comment]
BTW, regarding this example,

```
"/show": {
    "METHOD": "GET",
    "REQUEST": {
        "permitAll":[],
        "ROLE_ADMIN":["id"]
    },
    "RESPONSE": {
        "permitAll":["firstName","oauthProvider","username","password","lastName","oauthId","avatarUrl","email"],
        "ROLE_ADMIN":["passwordExpired","accountExpired","accountLocked","enabled","id","version"]
    }
```

Here's one way you can get close to that with OpenAPI.  This example is using a POST to allow sending the different payloads based on role. Content objects can have multiple media types that differ only by parameter.

```yaml
openapi: 3.0.1
info: 
  title: Example of using media type parameters to correlate roles to payloads
  version: 1.0.0
paths:
  /show:
    post:
      requestBody:
        content:
           application/json;role=anonymous:
            schema:
              type: object
           application/json;role=admin:
            schema:
              type: object
              properties:
                id: {}
      responses:
        '200':    # status code
          description: User name based on userid in token
          content:
            application/json;role=anonymous:
              schema: 
                type: object
                properties:
                  firstName: {}
                  oauthProvider: {}
                  username: {}
                  password: {}
                  lastName: {}
                  oauthId: {}
                  avatarUrl: {}
                  email: {}
            application/json;role=admin:
              schema: 
                type: object
                properties:
                  passwordExpired: {}
                  accountExpired: {}
                  accountLocked: {}
                  enabled: {}
                  id: {}
                  version: {}
```

In theory we could do this as a GET if you used a header for the inbound role.  We have never recommended using multiple media types with a content property for a header before but I don't think we actually prevented it.

**Comment by orubel** [comment]
> That's not what I said. You are creating another strawman. Your use of the word state is very ambiguous

Ok lets look at some of the things you have stated...

> As far as I know "achieving shared state" is not a goal.

> I'm not interested in talking about "shared state" and "state synchronization" as it isn't relevant to the OpenAPI specification.

>> OpenApi is GENERATED from the state of the API Server
> Nope, that is contrary to the principal of "design first" which is what the API community generally advocates.

You are all over the place, man. Making contradictory statements. I'm waiting for you to land on something and stick to it.

This is why I said that 'state' is about:
- synchronization across all architectural systems that share the request/response
- testing across all architectural systems that share the request/response
- secure call flow across all architectural system that share the request/response

If you disagree, I think you should inform people what it is you ARE creating then. I myself am now SERIOUSLY confused as to what it is you are trying to create.

**Comment by orubel** [comment]
> application/json;role=admin

well not ideal; this means that if I'm interpretting for multiple formats, I have to now put that data in for each different format???

**Comment by darrelmiller** [comment]
Sorry Owen, I give up.  OpenAPI has the extensibility to do what you need.  There is plenty of content out there that explains what contract first or design first actually means.  I've already spent my evening trying to help and now you are gaslighting.

I hope you are able to achieve your goals.  But I'm confident you don't need my help to do that.

**Comment by orubel** [comment]
@darrelmiller During this thread I have seen you jump from one excuse to the next.

**This issue has been on your plate for close to 4 years!**

You are offering a quick fix of associating roles with formatting??? No it's not gaslighting, it's calling it what it is... a poor quick fix for something that has been on your plate for nearly 4 years!

You are frustrated because I am pointing this out? Well are you asking people NOT to point out issues in a standard?

Because this is how things improve and get better. This is how we all improve and get better.

**Comment by darrelmiller** [comment]
You do realize that nobody working on the OpenAPI specification is paid for what they do?  We all work on this in our free time.  Nobody owes you anything.

OpenAPI work is prioritized based on impact and community contributions. One person wanting a feature doesn't get a higher priority than features that many users are asking for.

Creating a smear campaign that spreads FUD and sending threatening emails, to try and pressure volunteers to do work so that your product architecture can work with OpenAPI is not the most effective way to go about achieving your goals.

**Comment by orubel** [comment]
> You do realize that nobody working on the OpenAPI specification is paid for what they do? We all work on this in our free time. 

Alot of my work is the same

> Nobody owes you anything.

True. Nobody owes ME. When we work on open source, we owe our users and become indebted to our users. And when we try to become a STADARD, it is even MORESO TRUE. This is why it is SO IMPORTANT that we ask for help when we need it.

> OpenAPI work is prioritized based on impact and community contributions. One person wanting a feature doesn't get a higher priority than features that many users are asking for.

I think you seem to be under the impression that this wasn't brought up around 2017. That we didn't have this conversation about 4 years ago??? That you are somehow suddenly surprised and unaware of this sudden interest in security.

You also seem to think that I am the only person doing this when I pointed out that this is a documented feature in Spring, Springboot, Django and others??? Talk about strawmen... geez. Right there thats thousands of developers dude.

> Creating a smear campaign that spreads FUD and sending threatening emails

Ok you need to dial back that comment before we get lawyers involved. I want to see ONE THREATENING EMAIL... or an apology.

**Comment by orubel** [comment]
And BTW, one man cannot possibly bring and entire specification to an end. I'm pleased you would give me credit for wielding so much influence but regardless of conspiracy theories, I am not that powerful.

**Comment by LikeLakers2** [comment]
Hi orubel, it's me again.

I would suggest you drop the issue, and go somewhere else. Clearly OpenAPI is not going to work how you want it to work. So stop frustrating yourself and go to another repository that enjoys your ideas more.

If you really want your API description to include what roles can produce what results, consider using [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#specificationExtensions) as has been suggested on multiple occasions. Otherwise, maybe use BeAPI as you already are since you seem to have a much better time with it, and since it already supports this mechanism.

**Comment by orubel** [comment]
I'm waiting to hear from the OpenApi Initiative about @darrelmiller statement and whether he is going to remove said statement and apologize.

**Comment by philsturgeon** [comment]
Your lawsuit sounds frivolous and stupid. Please give up and go away. You’ve been ranting at people about things that are half completely unintelligible, half provably false. I’m sure if I wasted enough time taking to you the unintelligible part would turn out to be false too.

We’ve all wasted enough time trying to be polite to you, it’s been years now, so don’t throw a wobbly when somebody calls you out as threatening. You know what you’ve done to hurt and scare people in the API community, and so do I. Drop it. Use your energy for something constructive, take your golf, doesn’t matter, just leave this community alone.

**Comment by orubel** [comment]
> Your lawsuit sounds frivolous and stupid. Please give up and go away. 
@phil I never  said there was a lawsuit. And I finally know what @darrelmiller is talking about. It was an openletter to OpenApi : https://twitter.com/BeApi_io/status/1318260623902347264

> You’ve been ranting at people about things that are half completely unintelligible, half provably false. 

And you think 'shared state' is completely unintelligible??? Ooooook. This says more about the contributors to the spec than it does about me if few of you can understand that the 'state' of the endpoints needs to be shared and synchronized in a distributed architecture.

> We’ve all wasted enough time trying to be polite to you, it’s been years now, so don’t throw a wobbly when somebody calls you out as threatening. 

You actually are doing more to show the lack of professionalism that I pointed out in the project. 

> You know what you’ve done to hurt and scare people in the API community, and so do I.  Drop it. Use your energy for something constructive, take up golf, doesn’t matter, just leave this community alone.

"First they ignore you, then they laugh at you, then they fight you, then you win." - Ghandi

**Comment by LikeLakers2** [comment]
Hi orubel. I will make my suggestion once more, and I'm hoping this time that you will listen, for your own sake.

Please leave this topic alone. If you wish to admit victory in the background, that is your own doing, but you are quite honestly making a fool of yourself... what with all the bolding, capital words, and even quotes that [you have mis-attributed](https://www.snopes.com/fact-check/first-they-ignore-you/). Not to mention that, despite having four other closed issues, you decided to open a fifth -- it's starting to become troll-like behavior, as you refuse to take "no" for an answer, and have decided to keep whining and screaming and effectively throwing a tantrum (see: when you refused to see me as anything but an OpenAPI representative because I had the *audacity* to comment on your issue).

I'd also like to suggest that if you're going to bring lawyers into the mix (even if a lawsuit isn't involved), that you keep that sort of thing in private. Your email and Darrel's email are both publicly viewable on your GitHub profiles, so use those if you need to talk lawyers (although so far, I can't truthfully feel like you have a grasp on how lawyers and the legal system actually work). Aside from that, GitHub issues is not the place to be talking legal issues anyways.

----

To any OAI members with management permissions, I really think you should lock this issue and block orubel from the OAI repositories permanently should this behavior continue, as this has gone on far too long. It's become troll-like behavior, as they refuse to take "no" for an answer -- and it's honestly surprising me that orubel hasn't been blocked already given what I've seen on other issues by orubel.

**Comment by orubel** [comment]
@LikeLakers No one has said no. **You yourself have stated that OpenApi is not for Api Gateways** if I remember accurately from the past ticket.

Most of the answers I have seen are very very questionable at best and lack an understanding of distributed architectures and shared state. You claim my questions are ambiguous but for those dealing with distributed architectures (which are 90% of API installs these days), they understand these issues quite clearly.

And I don't understand why you keep talking about lawyers. @darrelmiller is just unfortunately 'threatened' by an open letter to the openapi community posted on Twitter that I sent to the team as well as I politeness after @webron posted very rude remarks online not only to me but several others as well.

**Comment by orubel** [comment]
@LikeLakers2 @darrelmiller This ticket was opened to talk about 'Role' association to content and we went off topic talking about:

- 'shared state' (which you stated OpenApi is not concerned with)
- OpenApi is generated from a design doc not the endpoints of the API server
- the central version of truth for a running api system is NOT the api server endpoint according to you; it is a static design doc.

So if this is all true, why is OpenApi even pushing for use with Api Gateways??? Why does it have this documentation on its system? **It sounds like you are creating a static design doc... not a shared state.**

**Comment by philsturgeon** [comment]
1. you're talking about lawyers, that's threatening. 
1. repeating "since 2017" over and over again doesn't make it any more true, you've been equally wrong for a long time
1. the video you're linking to as supporting your claims of OpenAPI having a security issues does not talk about this topic.
1. you dont seem to understand anything about the design-first workflow, which is a popular alternative to the code-first / annotations approach you always talk about: https://apisyouwonthate.com/blog/api-design-first-vs-code-first/
1. OpenAPI is YAML/JSON file which describes stuff an API can do so there's literally no security concerns there. If they dont have permissions they cant do the thing.
1. wtf is "shared state" anyway, and dont just keep shouting "distributed systems" yes we all write distributed systems.

I don't really need or wnt answers to this I'm just highlighting why people are tired or talking to you about this over and over again for years.

**Comment by philsturgeon** [comment]
Yes, great, it's a static design document, there is no shared state, no need for ROLES, and we're done here.

**Comment by orubel** [comment]
> 1. you're talking about lawyers, that's threatening.

Show me where.

> 2. repeating "since 2017" over and over again doesn't make it any more true, you've been equally wrong for a long time

**Saying someone is wrong and PROVING someone is wrong are two different things.** I learned this long ago when I found that the communication logic and the business logic were bound in the 1970's api pattern creating an architectural cross cutting concern when using said pattern in distributed architectures **thus making the 1970's api pattern a single-tier pattern**. I confirmed this numerous times when being invited to speak and consult with Mashery, Mulesoft, Vmware and others.

So merely saying someone is wrong has no weight in an argument. If you cannot PROVE that someone is incorrect in a technical discussion, what you are effectively doing is throwing a tantrum for lack of understanding yourself.

> 3. the video you're linking to as supporting your claims of OpenAPI having a security issues does not talk about this topic.

You think it doesn't because you fail to see how at the API Gateway

to repeat what is posted in the beginning of this ticket, If you read how people are using OpenApi in API Gateway, it is being used for ROUTING TO ENDPOINT **POST CHECKING OF SECURITY**.

Meaning :

- Security has been checked
- Token has been issue
- Api Gateway now uses OpenAPI to route to endpoint
- Gateway does a check for request and response data for endpoint using OPENAPI, REGARDLESS OF WHETHER:
    - USER has multiple ROLES
    - Endpoints expect different REQUEST/RESPONSE 'content' per ROLE

OPENAPI assumes an 'anonymous' ROLE (which is issued if no token is found on most systems) and as a result, assumes everyone has this ROLE by default when ROUTING.

This may not be the case when doing the PROCESSING but if it has no way to tell the system that different ROLES should send different request data when ROUTING, it just tells it one thing for everyone.

So it will always send to little/too much info and return too little/too much info (most likely too much info) which is in violation of **API3:2019 Excessive Data Exposure**

I'm trying my best to baby step you through this because I understand this is hard for you to understand, so please be patient.

> 4. you dont seem to understand anything about the design-first workflow, which is a popular alternative to the code-first / annotations approach you always talk about: https://apisyouwonthate.com/blog/api-design-first-vs-code-first/

I understand design first but in a WORKING API SYSTEM, I don't care about syncronizing design docs. I care about syncronizing all the services in my architecture that share the request/response. **And that's what documents like RAML, API BLUEPRINT and OPENAPI are supposed to do.**

> 5. OpenAPI is YAML/JSON file which describes stuff an API can do so there's literally no security concerns there. If they dont have permissions they cant do the thing.

There are if it is used for routing. Routing is where you check access to that endpoint and what data to send/return. What data to send/return is based on ROLE.

> 6. wtf is "shared state" anyway, and dont just keep shouting "distributed systems" yes we all write distributed systems.

All the data about your endpoints needs to be shared with your the other services in your architecture that share the request/response (ie the api call flow). That state they share for the api call flow is 'shared state'. They all need to have the EXACT SAME STATE for all endpoints so as to not get out of sync.

> I don't really need or wnt answers to this 

Obviously you do. You should know what shared state is if you are contributing to a project of this nature.

**Comment by orubel** [comment]
> Yes, great, it's a static design document, there is no shared state, no need for ROLES, and we're done here.

*sigh* I'm trying to be serious and you're trying to be argumentative.

**Comment by darrelmiller** [comment]
I'm serious: "it's a static design document, there is no shared state, no need for ROLES, and we're done here."
