### ISSUE TITLE
Proposal: Disallow server parameters in basepath

### ISSUE THREAD

**Issue by siimsoni** [OAI/OpenAPI-Specification#2387]
Allowing server parameters in the path part of the URI creates potentially ambiguous paths.

In the following (unlikely) example, `//example.com/France/Bourgogne` could match either:
* `//example.com/{Country}`, `/Bourgogne`
* `//example.com`, `/France/{Region}`

```
openapi: 3.0.1
info:
  title: Example
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: //example.com
- url: //example.com/{Country}
  variables:
    Country:
      default: France
paths:
  /France/{Region}:
    get:
      summary: Example
      parameters:
      - name: Region
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            'text/plain':
              schema:
                type: string
  /Bourgogne:
    get:
      summary: Example
      parameters:
      - name: Region
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            'text/plain':
              schema:
                type: string
```

Motivation:

* Resolving this ambiguity would allow to create a proxy to validate requests/response against on OpenAPI schema, without knowing which server to validate against. Note that it wouldn't solve all theoretical ambiguities, which would require a different solution.
* There is no guidance when a parameter can be server parameter, and when it must be path parameter. This may lead to inappropriate use of server parameters, where path parameters would be the correct choice.

**Comment by MikeRalphson** [comment]
Removing a well-used feature to resolve something which is "potentially ambiguous" and as you say "unlikely" seems like the wrong approach here. If tooling needs to know which `server` url to proxy (or pattern of server-variables) it can be provided with that information.

There is no guidance on use of `in: path` parameters versus `server` `variables` because this is an API design decision. We could highlight the potential ambiguity if `server` `url`s have different patterns of `variables` if you think a PR is warranted.

**Comment by siimsoni** [comment]
This is enlightening as to what OpenAPI considers a server. I will close this feature request.
