### ISSUE TITLE
editorial: field not explicitly required can be considered optional

### ISSUE THREAD

**Issue by ioggstream** [OAI/OpenAPI-Specification#2470]
## I suggest

- to use a clear BCP14 terminology

## instead

> can be considered OPTIONAL

is not clear.

## note

- I'd explicitly add OPTIONAL on optional fields. "Explicit is better than implicit"

otherwise I'd state

- if a field is not explicitly REQUIRED, it is OPTIONAL

**Comment by MikeRalphson** [comment]
@jasonbstanding does this cover the issue you raised a couple of weeks ago?

**Comment by lornajane** [comment]
@ioggstream was this related to another issue or discussion? (sorry, I realise it's been a while!)

**Comment by ioggstream** [comment]
iirc it was open to suggest a more clean language in the spec 

I don't remember if expressions like the above are still present in the latest specs.

The general advise still remains.

**Comment by lornajane** [comment]
I think we could add a note about anything that isn't required being considered optional, if it would make it clearer to anyone.

**Comment by handrews** [comment]
@lornajane we already have that note at the top of the whole "Schema" (meaning structure of OAS, not JSON Schema) section ([3.0.3 §4.7](https://spec.openapis.org/oas/v3.0.3#schema); [3.1.0 §4.8](https://spec.openapis.org/oas/v3.1.0#schema)):

> In the following description, if a field is not explicitly REQUIRED or described with a MUST or SHALL, it can be considered OPTIONAL.

**Comment by lornajane** [comment]
We discussed this in a TDC meeting and since we have required fields clearly marked and an overall remark about non-required fields being optional by default, we agreed not to add optional to all other fields.

I suggested that it does not improve readability and was not contradicted. I do want to say thanks for the suggestion though - it was a good discussion and ideas are always welcome!
