### ISSUE TITLE
Pass arbitrary JSON objects in request body

### ISSUE THREAD

**Issue by tobias-schuele** [OAI/OpenAPI-Specification#2629]
How can I pass JSON objects with arbitrary structure in the body of a request? For responses, it is possible to just specify `application/json: {}` but that seems not to work for request bodies. Thanks!

**Comment by MikeRalphson** [comment]
The syntax would be:

```yaml
application/json:
  schema: {}
```

but it should work fine for `requestBody`. But, "work" may be in the context of a particularl tool?

**Comment by tobias-schuele** [comment]
Thanks, works with openapi-generator

**Comment by jdegre** [comment]
Not sure if the OP really meant "arbitrary JSON _**objects**_", as in the title of the issue.
If it was meant "JSON objects", I guess the right schema for the request body would be:

```yaml
application/json:
  schema:
    type: object
```
Otherwise, the schema mentioned above (`schema: {}`) would be satisfied by, e.g., an array, a boolean, a string... well, anything, as long as it is valid JSON.

**Comment by MikeRalphson** [comment]
Great point @jdegre !

**Comment by karenetheridge** [comment]
This raises an interesting point -- how does one specify "the body can be anything at all, including being empty"?  An empty body is not valid json. Or, as a corollary: how does one specify "there should not be a body; if there is anything, this is a violation"?  Perhaps there is a FAQ or cookbook that I have not found yet :)
