### ISSUE TITLE
Open API typemapping model -clone method erroring after model creation

### ISSUE THREAD

**Issue by Rselvaraj22** [OAI/OpenAPI-Specification#2647]
When we use typemapping to a known java class
example ---> Multipart= org.springframework.web.MultiPartfile.

The model or request Body where we use this typemapping ... The Open API generate model for them . In that processs it creates a clone method for the typemapping object and it errors out saying clone is of protected type . Please advice ..how we handle this .

**Comment by webron** [comment]
This seems like a question that's related to a specific library, not directly OpenAPI. Please file an issue with the respective project instead.

**Comment by Rselvaraj22** [comment]
No .. ron ... By default the open api is trying to provide public clone()
in the models ...If I type map any predefined java object ... It is failing
in compilation for clone() being protected in object.java

**Comment by webron** [comment]
No, OpenAPI is a specification, not a library. Any code impact you're experiencing is coming from a specific library you use within your code.

Since you're using Spring, there's a decent chance you're using Springfox. However, there are several other libraries you may be using. Find out which one, and check with them. We cannot help with any specific implementations here.
