### ISSUE TITLE
format "media-range" is used in the schema without a specification

### ISSUE THREAD

**Issue by karenetheridge** [OAI/OpenAPI-Specification#2714]
`format: media-range` appears in the JSON Schema for v3.1 (it appears to have been introduced in this version), but it is not mentioned in the spec anywhere, especially in https://spec.openapis.org/oas/v3.1.0#data-types. This should either be added to the spec as an extension to the "format" keyword, or the schema should change to using a "pattern" instead.

**Comment by karenetheridge** [comment]
cc @jdesrosiers you added this in commit b5bf761d9b4e -- perhaps you have more information?

**Comment by jdesrosiers** [comment]
"media-range" is a custom format attribute as defined here, https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.2.3. It's not really intended to be validated but it optionally could be. It's based on the "media-range" ABNF production in RFC-7231, https://datatracker.ietf.org/doc/html/rfc7231#appendix-D.

We talked about it and decided we didn't want to include some ginormous nasty regex and we didn't want a simple regex that could give a false sense of security, so we came up with this as an alternative. A standard validator will ignore it, but if you have a validator that understands the custom format attribute, you can get assertion behavior.

Specifying the format attribute in OAS wouldn't help because the dialect of the schema is draft 2020-12. The format attribute would only apply to the OAS JSON Schema dialect. I agree that there should be something in the schema that gives a hint about what "media-range" means. Maybe a `$comment` or a `description`.

**Comment by handrews** [comment]
This format has since been added to the [formats registry](https://spec.openapis.org/registry/format/).
