### ISSUE TITLE
Invalid Json in OpenAPI-Specification/schemas/v3.1/schema.json

### ISSUE THREAD

**Issue by seriousme** [OAI/OpenAPI-Specification#2723]
Hi,

my Github action to [check for new OAS versions](https://github.com/seriousme/openapi-schema-validator/blob/master/.github/workflows/checkOpenApiSpecVersions.yml) detected invalid JSON at:
https://github.com/OAI/OpenAPI-Specification/blob/917d33022a4e33f435f9fec37e14c2348e8b7a9f/schemas/v3.1/schema.json#L774-L778

Kind regards,
Hans

**Comment by tmartin-git** [comment]
Maybe missing a '{'
=> Should be:
` "^[1-5](?:[0-9]{2}|XX)$": {`

**Comment by seriousme** [comment]
Looks like it.
Issue seems to be introduced by #2706 

Kind regards,
Hans

**Comment by seriousme** [comment]
Fixed, thx!

**Comment by jdesrosiers** [comment]
@seriousme You caught us in the middle of a multi-step process of releasing a new version of the schema. I suggest changing your Github Action so it looks for new versions (from the website)[https://github.com/OAI/OpenAPI-Specification/tree/gh-pages/oas/3.1/schema] instead. When we release a new version of the schema, this is where they get published. What's in the repo can sometimes be incomplete because we don't release a new version for every PR that we get.

**Comment by seriousme** [comment]
Clear !

Few questions though: 
a) does this mean that the pre-3.1 schemes never change again ? (They don't seem to be present on the gh-pages branch.)
b) what happens if post-3.1 schemes emerge ? (e.g. will the oas/3.1 folder disappear ?)

Kind regards,
Hans

**Comment by jdesrosiers** [comment]
This is a new process that I introduced for v3.1, so that's why you don't see any 3.0 schemas published there yet. This next release will have a v3.0 update and I will be publishing that to the website. I don't plan to add older releases to website, but I can if people ask for it. The bottom line is that going forward, all schema updates will be published to the website. Once a version is published, it will not be removed. Hope that was clear.

**Comment by seriousme** [comment]
Thanks for the explanation!
Having the old versions available on the website would be nice as tools (like mine ;-)) still support the 2.0 and 3.0 version.
One "official" place to look for these versions (e.g. referred to in the FAQ) would be nice, I picked them up from `master` but I just learned that is your WIP branch ;-)

**Comment by seriousme** [comment]
Btw: ideally there would be an API(;-)) to check for new versions.

**Comment by jdesrosiers** [comment]
The process could certainly use some improvements, but with all volunteer work, you often end up with a minimal viable solution rather than an ideal solution :disappointed:.
