### ISSUE TITLE
[Question/Clarification] Is enum with empty list of values considered to be valid OAS3 schema?

### ISSUE THREAD

**Issue by lzemskov** [OAI/OpenAPI-Specification#2737]
Newbie to this, so my apologies if this is not the right format/forum please advise what would be a better way to ask/clarify.

We are building an OAS representation for an existing 20 year old API which comes with some quirks and challenges. One of the challenges is around expressing Schemas with field data types which represented on the backend as Enums/Picklist data types. The challenge is multifold:
1. The set of available values is dynamic and could get very large (up to 3K items and growing).
2. There are multiple Schemas (3K and growing) which can have multiple fields of the types above.
Combined this has a potential for blowing up the overall size of schema which we are hoping to avoid.

As one of the solutions we were considering mapping those types to an Enum with an empty set, and adding a description with a pointer to the doc/API which can be used to obtain the list of possible values. But currently looks like some of the existing validators flag this as an invalid OAS3 schema. I tried looking through the OAS3 spec documentation but it does not mention anywhere that enum must have at least one item, so was wondering if there is such limitation?

**Comment by karenetheridge** [comment]
No, the enum array may be empty:

> The value of this keyword MUST be an array. This array SHOULD have at least one element. Elements in the array SHOULD be unique.

https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.2

**Comment by lzemskov** [comment]
Thanks for the pointer @karenetheridge , however the spec says:

This array '**SHOULD**' have at least one element not '**MUST**' and there looks to be a similar discussions around this topic inside the JsonSchema repo as well which seems to indicate that an enum with the empty set should indeed be a valid JsonSchema:
https://github.com/json-schema-org/json-schema-spec/issues/717

Am i reading it correctly?

**Comment by webron** [comment]
Looks like you might have hit an edge case with validation tools. OAS3 depends on "draft 6" which was intended to be re-release of "draft 4" as "draft 4" was expired at the time. It was our understanding that those two versions were pretty much the same. Looking at the `enum` definition though, it seems that's where there's a difference between the two versions, where "draft 4" required at least one element in the array.

Interesting enough, the [migration guide](https://json-schema.org/draft-06/json-schema-release-notes.html) between those two versions doesn't even mention the difference in the `enum` definition which is likely another source for confusion. 

While less than ideal, given the amount of values you're referring to and the fact you mentioned the list is actually dynamic - you might want to consider this as an open value field instead of specifying it as an empty `enum` and then reference the list of possible values elsewhere.

**Comment by lzemskov** [comment]
Thanks again for the feedback @webron , want to make sure i understand your point.

_'the way I read an empty enum - no value is valid and validators would blow on any value to that field'_

So you are saying if i used the generated schema (which has an 'enum []' definition) and used a valid json input which has any value in that field even when the value provided is from the specified/valid set which we point a consumer to be it via info inside the description field or some other means that Json would fail validations against the schema because the enum set is empty.

**Comment by lzemskov** [comment]
Sounds good, thanks again for clarifications and input which was very helpful @webron , @karenetheridge 
Given that the original question here has been answered i will go ahead and close this 'Issue'
