### ISSUE TITLE
Internationalization 

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#274]
For Swagger.Next we need to add i18n to `description` fields. We can have two forms of `description`. It can be a string or an object that has a pair of key,value for each locale/language. We can use [ISO 639-2](http://www.loc.gov/standards/iso639-2/php/code_list.php) standard (for example *eng* for English)

For example:

```yaml
  description:
    eng: A simple API
    esp: Un simple API
    chi: 一个简单的API
```

**Comment by mohsen1** [comment]
`title` and `summary` could have i18n too

**Comment by fehguy** [comment]
This has come up a couple times, with different suggestions.  The current work around (and possible a good way to do this) is to identify sections of the spec with IDs (we're currently using vendor extensions) and map to a resource bundle, rather than jumble it all into the spec.  I don't know which is better, but that's one approach.

**Comment by noirbizarre** [comment]
Another approach is to have different specifications generated for each languages.
It's more complex to maintain when specifications are manually written but far more easy when the specification is code driven coupled with something like gettext.

**Comment by nacho4d** [comment]
I wrote this issue https://github.com/swagger-api/swagger-editor/issues/591 which is basically about internatinalization of labels and titles.  Here is what I have in mind:
this:
<img width="1440" alt="screen shot 2015-08-18 at 17 08 27" src="https://cloud.githubusercontent.com/assets/111651/9325342/8d135494-45cc-11e5-9d0d-384cb8483cab.png">

would become:

<img width="1440" alt="localized" src="https://cloud.githubusercontent.com/assets/111651/9325679/0ea5bbda-45cf-11e5-8cac-6c0bb40a91d9.png">

What had in mind is that labels (ex: Summary→概要, Description→説明, Parameters→パラメーター, Responses→リスポンス, Code→コード, Default→デフォルト, etc...) and titles will be translated without modifying the yam file. I imagine swagger will have a bunch of predefined dictionaries only with those words.

Regarding selecting the language, in addition to the url (like @noirbizarre suggested) reading header AcceptedLanguages could be an option too.

**Comment by AlbertoLeon** [comment]
Another proposal:

description-en: 'for English descriptions'
description-sp: 'for Spanish descriptions'

title-en ....

I think should be treated as different properties.

**Comment by webron** [comment]
Closed as not supported, following https://github.com/OAI/OpenAPI-Specification/pull/639.

**Comment by nacho4d** [comment]
@webron #639 and #70 Seems to be about *content* language that an API returns.
This is about the *documentation* language. I still looking forward to see swagger in other languages ;-)

**Comment by Kitanotori** [comment]
I agree with @nacho4d , API content language is totally different thing from the documentation language. There are cases when we want to have documentation language in one language and content language in other. The approach suggested by @mohsen1 seems fine: allow specifying the documentation language via ISO 639-3 language code.

**Comment by Frank591** [comment]
Hello. What about support of several languages for "description" and "summary" fields? All tasks about that problem was closed, but i don't see into specification any ways to translate API description to several languages. What standard way to translate OpenAPI3 document to several languages?

**Comment by Frank591** [comment]
Are there any news about internationalization support? We really need this functional in our project

**Comment by anticlockwise** [comment]
@webron I'm not sure if Overlays should be overloaded to solve the internationalization issue though... It's unclear to me whether the Overlay document will become a separate API or overriding things on the original API? What if I wanted to build yet another Overlay document on the API, then which of the translation Overlay document should I reference?

**Comment by webron** [comment]
That's the idea with overlays. They are meant as additional layers on top of your API and or not independent APIs. In order to get the 'result', you'd need to run the overlay with the API definition through a pre-processor. That way, you can have an English overlay, a French overlay, a Chinese overlay, and that way get different language versions after pre-processing.

**Comment by daniol** [comment]
This issue was wrongly closed by @webron as @nacho4d and @Kitanotori pointed out; it should be reopened!

**Comment by tigerinus** [comment]
Seriously, this issue should be re-opened.

Multilingual support in public documentation is almost certain required by many public policies. Maintaining two copies of OpenAPI YAML in different language is chaotic. Thanks!

**Comment by jeremyfiel** [comment]
a lot of the suggestions here are good but they seem to depend on some sort of UI generated from the OAS definition. If that's the case, the i18n should be handled by the documentation tooling rather than the specification.

**Comment by nacho4d** [comment]
There are two main problems to tackle here. Hopefully this explanation helps developers/admins so they re-open this issue. 


<img width="109" alt="Screen Shot 2022-05-25 at 0 08 34" src="https://user-images.githubusercontent.com/111651/170069549-91b3235a-fbc5-4759-bac8-c18fdce48415.png">

1. The localized strings that are hardcoded by the tooling. These are "Summary" "Description" "Parameters", etc in above screenshot. These strings should be handled by the tooling. So, regarding 1, I agree with @jeremyfiel. 

2. The localized strings for the content. (Suppose your documentation has 2 audiences, English speakers and Japanese speakers). Obviously, these cannot be hardcoded by the tooling. The tools will never know about the content. Since one single yml file will have various languages Specification should define keys to support various languages. I think @AlbertoLeon idea is accurate and extensible enough.


For example:

```
paths:
    /products:
        get:
             summary-en: 'Get all the products'
             summary-ja: '全ての商品を取得'
             description-en: 'Get all the products (Long explanation here)'
             description-ja: '全ての商品を取得(詳細な説明をここに記述)'
```

I imagine some tools might use the user-agent other tools might have a pull-down menu to trigger the language change, etc. 
If the tool needs/wants to show a yml in Japanese then the world "Description" should show as "説明" (This translation will be done by the tooling). And if there is a value for key `description-ja` then such value will be shown. 

Since 1 can/should be done by the tools it is out of scope. **HOWEVER, IMHO 2 is IN the scope of open API specification because it defines how keys should be interpreted/used.**

**Comment by karenetheridge** [comment]
or alternatively:

```yaml
paths:
  /products:
    get:
      summary:
        en: 'Get all the products'
        ja: '全ての商品を取得'
      description:
        en: 'Get all the products (Long explanation here)'
        ja: '全ての商品を取得(詳細な説明をここに記述)'
```

**Comment by ghahramani** [comment]
another suggestion to have an extension for those who uses spring boot and just read from i18n that is already supported by spring, it can be much easier to just put the property key in the OpenAPIDefinition annotation and let the spring handles the i18n for you which mean it can handle it with accept language header

**Comment by nacho4d** [comment]
Having a tool that generates 1 yaml files per language is a nice feature and if Spring has already implemented it then it is one way to go for now :)
In reality OpenAPI is used by several other tools not only Spring. In my opinion OpenAPI is tool agnostic and it should support i18n from design.

**Comment by ghahramani** [comment]
Yes, that is correct but bear in mind that agnostic tools needs to be agnostic in their core but not in their surface, the OpenAPI core can have i18n (interface) like component base structure (same as what kubernetes does) and then we can have a plugin of OpenAPI that integrates (implement the interface) with spring feature, in this case it is still agnostic but you can use the feature of both world

**Comment by minesunny** [comment]
I think it would be better if replace  with a var name in i18n resource file
```
openapi: 3.0.3
info:
  title: RuleTemplate
  description: ${rule.template.description}
  version: 1.0.0
```
<img width="855" alt="image" src="https://github.com/OAI/OpenAPI-Specification/assets/98507458/c445e9a6-192d-403a-b2f8-54f65a77ea34">

**Comment by axelsean** [comment]
The suggestion from @minesunny would be the way to go here, then it would work for all fields, and a "base" resource file would have the boilerplate translations.   This could also be extended to documentation generated from code, which right now pass the text, add functionality to add a resource key.

I don't see this, but a Right-to-Left language has other issues that possibly require a different document template

**Comment by handrews** [comment]
@axelsean @minesunny is there any reason that this couldn't be done with existing templating and localization systems?  Is there a need to handle this in a different way from I18N/L10N of any other document?  Since this seems to be about the documentation text in the OpenAPI Description and not things like using HTTP headers to access localized resources.

**Comment by axelsean** [comment]
@handrews There's two parts here, Globalization - creating the framework, and Localization actually doing it.

The spec needs to define how an implementor will provide localizable content, for example is it one of the below (stolen from earlier comments).

In either case the actual UI presentation needs to be able to localize the header for description (as others have noted), in some sites this is a language drop down in the UI - that would work here.

`
description:
    en: A simple API
    fr: Un simple API
`
or - note this needs resource files per supported language
`
languages: [en, fr]
...   
description: {my.description.tag}
`

Personally I favor the resource files approach:

- it is much easier to support when generating documentation from code - which is the way we do this.
- Right-to-Left is supportable easily

**Comment by iseki0** [comment]
It's not out of scope. Besides machine-reading, documentation is designed to read by human. Human using different languages around the world. Why do you think that's "out of scope"? @lornajane

**Comment by handrews** [comment]
@iseki0 Lorna's comment does not mean that I18N/L10N is out-of-cope for the OpenAPI Initiative, just out-of-scope for the OpenAPI Specification.  It is, however, in-scope for the Overlay Specification, and is mentioned in an issue in that repo:

* https://github.com/OAI/Overlay-Specification/issues/31#issuecomment-2188308337

The Overlay spec is about to get an official 1.0 release blessing the current state of the draft which has a few implementations already, followed by a 2.0 effort based on the feedback so far and changes in technology since 1.0 started.
