### ISSUE TITLE
Examples ReUse

### ISSUE THREAD

**Issue by Mastahh** [OAI/OpenAPI-Specification#2937]
Hello,

I have two endpoinds
1 - Returns single Object
2 - Returns arrays of objects
![image](https://user-images.githubusercontent.com/10340023/171875622-b20cb456-a88f-4bf7-9dd2-dd37e06be62e.png)

I would like to use same SearchResultResponseExample for both endpoints, but in code above example shown as single object example not as array objects
Is there way to do this using exising example definition?
The easier way to copy-paste and modify existing example, but I do now like this way

**Comment by handrews** [comment]
An example cannot be both a single item and an array at the same time.  You'll need to make two examples.

Since an example can be literally anything, it's not possible to do referencing inside of it (sometimes an example will need to show `$ref` as part of the example, not a reference).

I'm goint to close this as answered, but if I have missed part of your question please comment and I can re-open.
