### ISSUE TITLE
[REQ] Improve definition of parameters, avoid collisions using maps

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#3040]
Endpoint parameters are defined as an array of Parameter and

A unique parameter is defined by a combination of a [name](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterName) and [location](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterIn)

So how about
defining endpoint parameters as a map of 
`{in_location: typing.literal["query", "cookie", "header", etc]: {param_name: str: Parameter object}}`
Where Parameter lacks
- in information
- name information

Note: With this change, Parameter is the same as the v3.0.0-3.1.0 response header definition
components/parameters/someParam could contain a Parameter object
and this would allow the same component Parameter to be $refed from a request parameter and a response parameter

This would:
- ensure via spec that parameter names and in locations do not collide
- potentially collapse components.Parameters and components.Headers into one entry, components.Parameters

**Comment by rafalkrupinski** [comment]
#2930

**Comment by handrews** [comment]
While we can't do this sort of backwards-incompatible structural change in 3.x, this sort of thing is being discussed for 4.0 over in the [Moonwalk repository](/OAI/sig-moonwalk/discussions).  Specifically:

* the [original proposal](https://github.com/OAI/sig-moonwalk?tab=readme-ov-file#jsonschema-for-parameters) treats parameters as objects and [applies one schema](https://github.com/OAI/sig-moonwalk/blob/main/examples/parameterSchema.yaml) to them
* https://github.com/OAI/sig-moonwalk/discussions/32 proposes moving everything to arrays instead

I'm going to mark this as "Moved to Moonwalk" since even though the proposal is a bit different there, it is also moving to objects rather than arrays.  Please feel free to join the discussions in that repo!
