### ISSUE TITLE
Openapi discriminator without propertyname

### ISSUE THREAD

**Issue by Foxyus8** [OAI/OpenAPI-Specification#3220]
I need inheritance only with one field in super class, so propertyName is no need. Is anyway to ignore propertyName?
```java
Base:
      type: object
      discriminator:
        propertyName: useless
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 1
``` 
Response like
```java
"useless":"subtype", "id":1
``` 
And throws error like
```java
Unrecognized field "useless"
``` 
I need inheritance only with id, without field propertyName, is anyway to do it?

**Comment by MikeRalphson** [comment]
If I understand correctly, all you need is an `allOf` with two sub-schemas (or `$ref`s), you don't need a `discriminator` if there is no property which tells you the sub-type.

**Comment by Foxyus8** [comment]
Thank you for help but I have to use discriminator because I need parent-child schema for generics in my API

**Comment by LasneF** [comment]
@Foxyus8  your answer is not as clear , 

looking on the oas Laws "The discriminator object is legal only when using one of the composite keywords oneOf, anyOf, allOf.
" 

this is breaking the laws  , so i would rather go to @MikeRalphson  solution  either with allOf , or anyOf ... depending on the constrains 

@MikeRalphson  you migh close the case if no reply #houseKeeping :)

**Comment by handrews** [comment]
@LasneF there is a clear example of using `discriminator` with `allOf` (where the two keywords are _**not**_ in the same schema object) in [the specification](https://spec.openapis.org/oas/v3.1.0#fixed-fields-20) (you need to scroll down a bit from where that link lands).

**Comment by LasneF** [comment]
thanks @handrews ; got it , a story of cat & dog 🐱 🐶 and 🦎
got the spirit meaning that petType is mandatory and must be 'kind of extensible' enum that would fill the name of its child 

I feel that it would be quite challenging to have the miror in an UML modelization / for code generation  
that is still a goal for OAS  (aka model / api / codegen / test ). 

let you close or keep it open

**Comment by handrews** [comment]
@LasneF I find `discriminator` vexing on so many levels.  It was a good effort at solving a real problem, but was done when OAS and JSON Schema weren't talking to each other much which led to it not fitting well in the better-defined modern JSON Schema model.

No major changes will be made in 3.x, but I'm certain we'll revisit `discriminator` (and schema modeling in general) in Moonwalk (4.0).  Since we haven't decided how to collect issue as input to the Moonwalk repository, I'll leave this open for now.  It's got the `discriminator` label already so we'll be able to find it when we need it.

**Comment by handrews** [comment]
@Foxyus8 if a tool is requiring `discriminator` where it is not needed, that is a problem with the tool and not (I think) with the specification.  The specification does not mandate `discriminator` for inheritance, it is just a feature that _can_ be used to support inheritance.

Since the remaining concern is a tooling problem and there hasn't been further discussion for over a month, I'm going to close this.  Please comment if I missed something and I can re-open.
