### ISSUE TITLE
Disallow ? , space and # in paths

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#330]
Per [URL specs](http://www.w3.org/Addressing/URL/url-spec.txt)  `?`, ` `and`#`should not be part of the path. 
I'm not sure about`=`.

**Comment by earth2marsh** [comment]
`=` is use in matrix parameters, which live in the path; however, I'm not sure whether the Swagger spec specifically supports matrix parameters. Generally, matrix parameters act as a filter at the specific level of the hierarchy where they are declared rather than query parameters that act on the entire resource, so I expect they don't impact the operation signature and therefore seem compatible with Swagger. 

It looks like #69 rejected the idea of explicit support for matrix params in the spec, but the fact that they exist seem to argue that `=` is permissible in the path.

**Comment by webron** [comment]
It's true, @earth2marsh - at least for now we decided not to support matrix params (it was part of the discussion in 2.0). Also, as explained [here](https://github.com/apigee-127/swagger-tools/issues/194#issuecomment-93893636), I'm not entirely sure we should restrict it at all in the schema. 

I'm still glad the issue exists here, as it'll force me to consider it :)

**Comment by mohsen1** [comment]
Because the URL and path are well specified in the standard, it's safe to restrict them. Disallowing `?` for example gives users the hint that they need to specify a query param instead of having query string in their paths.

**Comment by webron** [comment]
Mime types are also well defined (in format). I get what issue you're trying to avoid here, which is more 'sever' than the problems that can occur in mime types, so it can be a good idea in this case.

**Comment by RobDolinMS** [comment]
@mohsen1 Based on this discussion and the current OpenAPI Spec v3, do you believe there is more work needed to address this issue ?

**Comment by handrews** [comment]
The syntax for path templates in the Paths Object is derived from the RFC, which already forbids `?` and `#` in the part of the URL that can appear there.  Whether or not any given tool enforces this correctly should be taken up with the specific tool provider.

As noted above, we do not plan to forbid `=` as it has valid use cases and is allowed by the RFC (even if the OAS is not directly supporting those use cases).  So this seems like it can be closed.
