### ISSUE TITLE
Support for type: number, format: decimal

### ISSUE THREAD

**Issue by kamikazekip** [OAI/OpenAPI-Specification#3335]
In order to support currency / money, doubles and floats are inaccurate, they lead to rounding errors whereas Decimals do not. Therefore I propose to add the type: number, format: Decimal to the specification.

See also: https://medium.com/@tzvieira/currency-representations-in-computer-systems-fb789dee97c6

**Comment by handrews** [comment]
@kamikazekip additional formats are defined in a [registry maintained by OAI](https://spec.openapis.org/registry/format/).  This is not a normative part of the specification, but tooling vendors willing to support additional formats should use these in order to provide consistent behavior.

Note that `"format"` cannot compensate for floating-point inaccuracies inherent in parsing JSON to a machine representation (JSON Schema operates on the parsed mathematical number, not the JSON text), which is why some numeric formats can also be used with strings.  Storing numbers as strings guarantees working with the same numeric representation by bypassing whatever the JSON parsing library / underlying hardware offers.

**Comment by handrews** [comment]
@kamikazekip if neither of the existing defined decimal formats suit your needs, please reopen or open a new issue with more specifics on your use case.
