### ISSUE TITLE
$ref doesn't work when referencing a property in models which use 'allOf' keyword.

### ISSUE THREAD

**Issue by bsarchana** [OAI/OpenAPI-Specification#3403]
Below is a sample model.

```
ABC:
  allOf:
    - $ref: '#/BasePayload'
    - type: object
      properties:
        failingAlertSeries:
          type: array
          items:
            $ref: '#/AlertSeriesItem'
        recoveredAlertSeries:
          type: array
          items:
            $ref: '#/AlertSeriesItem'
        newlyFailingAlertSeries:
          type: array
          items:
            $ref: '#/AlertSeriesItem'
        alertType:
           type: string

```

And, I'm trying to refer 'alertType' property present in the above model and it doesn't seem to work. 

```
facets:
      type: object
      properties:
        v_info:
          type: object
          properties:
            vc_size:
              type: string
        manifest_info:
          type: object
          properties:
            cycle_id:
              $ref: '#/components/schemas/ABC/properties/alertType'
```

Can we reference a parameter in a model which uses 'allOf' keyword in another model?

Please help here. Thanks.

**Comment by handrews** [comment]
@bsarchana this looks like a tooling question.  This repository is only about the specification itself.

From a specification perspective, `$ref: '#/components/schemas/ABC/properties/alertType'` should work fine assuming the JSON pointer is correct (and it looks like it is).  It is generally considered good practice to put all of your `$ref` targets directly under `#/components/schemas` rather than `$ref`-ing subschemas, but you are allowed to reference any Schema Object, whether it's a direct component or a subschema of some sort.

If this is not working with your tools, you should raise an issue with the tooling vendor.
