### ISSUE TITLE
Clarification regarding the  type for the schema which has infinite recursion

### ISSUE THREAD

**Issue by lnash94** [OAI/OpenAPI-Specification#3433]
Hi Team,

Once I processed the OpenAPI definition, I observed the existence of infinite recursion within the component schema. I would appreciate clarification on whether this approach is deemed acceptable for OpenAPI specification. 

If this is a valid approach, could you please assist me in determining the default value type behavior for the 'JToken' schema?
I'm using OpenAPI specification version 3.0.1

Yaml example for **JToken**
```yml
component {
  schemas{
    ....
   "JToken": {
      "type": "array",
      "items": {
             "$ref": "#/components/schemas/JToken"
       }
}
```

**Comment by handrews** [comment]
Yes ,this is valid and describes a recursive array structure (basically a tree).  The reason that it is valid is that the `"items"` keyword means that each time you return to the component, you are another level down in the array nesting.  When validating a finite JSON instance with this schema, you are guaranteed to terminate the recursion because you will eventually reach the deepest level of the nested arrays.

**Comment by lnash94** [comment]
@handrews, Thank you very much for your insightful explanation.

I have a small concern about the JSON schema type for 'JToken.' I would like to understand how the 'JToken' type aligns with the OpenAPI Specification (OAS). Since OAS distinguishes between primitive schemas and structural schemas, I'm curious about the type that this schema represents in OAS.
For instance, is it an array schema with 'items' of type 'object schemas?

**Comment by handrews** [comment]
> OAS distinguishes between primitive schemas and structural schemas

I'm not quite sure what you mean by this.  This might be a tool-specific distinction?  Or do you just mean that schemas of `type: object` and `type: array` are "structural" and schemas of any other single type are primitive?  (Note that in OAS 3.1 you can have things like `"type": ["array", "string"]` which can be either an array or a string, although such constructs are unusual).

Since your "JToken" schema is a recursive array (the items reference back to the same schema), it is an array schema at all levels.  At least that's how I'm reading it.  Is there something specific in the schema that you think would introduce an object type?

**Comment by lnash94** [comment]
> > OAS distinguishes between primitive schemas and structural schemas
> 
> I'm not quite sure what you mean by this. This might be a tool-specific distinction? Or do you just mean that schemas of `type: object` and `type: array` are "structural" and schemas of any other single type are primitive? (Note that in OAS 3.1 you can have things like `"type": ["array", "string"]` which can be either an array or a string, although such constructs are unusual).
> 
> Since your "JToken" schema is a recursive array (the items reference back to the same schema), it is an array schema at all levels. At least that's how I'm reading it. Is there something specific in the schema that you think would introduce an object type?

@handrews, I apologize for the late reply and any confusion caused, and thank you very much for the insightful explanation. I received the answer by referencing this: `Since your 'JToken' schema is a recursive array (the items reference back to the same schema), it is an array schema at all levels.`
