### ISSUE TITLE
consider adding a CODEOWNERS file to this repository

### ISSUE THREAD

**Issue by baywet** [OAI/OpenAPI-Specification#3473]
A common challenge on pull requests is to know who needs to approve, and have them receive notifications to the pull request moves forward.
Adding a codeowners file and updating the branch policies would help resolve this.
I'll need a bit more input from the team here, but here are the notes from the meeting:

2 TSC members should approve anything for the "versions" directory.
2 people with the contrib permission should approve anything anywhere else.

Do we have github teams for those two populations today?
Any other rule I might be missing here?

Thanks for the input @earth2marsh @lornajane @darrelmiller @handrews

**Comment by darrelmiller** [comment]
We have "@OAI/tsc" and "@OAI/triage" teams that I think fit those two groups.

**Comment by lornajane** [comment]
We might want to rename the not-TSC team since "triage" describes the GitHub role that these people have. Alternatively: Introduce a "maintainers" team for the people who have that level of access, which I think we discussed giving to more people - and this allows us to keep the triage team as a starter role for people who want to help but might not be ready for merge commit rights yet.

**Comment by darrelmiller** [comment]
Agreed. I tried creating a maintainers team but the Teams mechanism in GitHub seems to be a hierarchy.  Seems like we need to think about how we want to organize the structure to make it manageable.

**Comment by baywet** [comment]
@darrelmiller meaning you're not able to create `@OAI/maintainers` ?

**Comment by lornajane** [comment]
Fixed by #3489
