### ISSUE TITLE
Github Create Issue button need refactoring

### ISSUE THREAD

**Issue by LasneF** [OAI/OpenAPI-Specification#3517]
currently the button new issue  

lead to this page 
![image](https://github.com/OAI/OpenAPI-Specification/assets/12461661/71b57e2f-464f-4f96-99fa-18ed873c66f6)

that does contains plenty of links to the documentation but not a visible way to "open" an issue 

this is due to this files 
https://github.com/OAI/OpenAPI-Specification/blob/main/.github/ISSUE_TEMPLATE/config.yml

i would suggest to leverage several files , and a keep it simple approach

- Bug Report
- Feature Request
- Question

associating a dedicated label automatically 

following for instance for bug report 
```
---
name: Bug report
about: Create a report to help us improve
labels: bug
---

**Describe the bug**

**Expected behavior**

**Additional context**

```

we could also mentionned the version of OAS affected

**Comment by handrews** [comment]
Thanks, @LasneF!  I have added this to the clean-up meta-issue task list.

_Warning: stream-of-consciousness ramble ahead..._

Some of these are intended to route folks to _other_ places for some of the most common ways people misunderstand this repo, which I think is a good thing.  But they need to be clearer, preferably by linking to another issue-filing form (e.g. the tooling one should actually open an issue on the OAI/Tooling repo).  Any that cannot link to an issue-filing form need to have their text clarified as to why the button goes where it goes, so folks don't just come right back and file a blank issue.

For example, we should direct people to the Slack to ask questions because it's much easier to answer them there than to manage them as GitHub issues, so that one wouldn't go to an issue form.

We should definitely keep the registries as their own template, even though I think it is also in this repo (as part of the gh-pages branch).  The workflow for those is quite different from specification issues.

We should also link off to the Moonwalk repository discussions, with an explanation that if something requires a major change, it is better opened as a discussion there.  Only minor or patch-level feature requests and bugfixes (as defined by semver) go in this repository.  Requesting the OAS version that they're talking about will help with this (and can also be an opportunity to clarify that no work will be done on the 2.x line).
