### ISSUE TITLE
Webhooks and Inheriting Schemas

### ISSUE THREAD

**Issue by alexphelps** [OAI/OpenAPI-Specification#3563]
I've been working on building webhook documentation for our project that uses Open API Spec 3.1 (built using DRF Spectacular). 

**Background**
We have versioned webhooks that follow our API schemas. The idea is simple, if you subscribe to a order.created webhook, we'll send you the same data in a webhook as you would get from calling /api/orders/123/ to retrieve it. Our structure is similar to what you see at stripe. 

**Webhook structure goes as follows:**
```
{
    "object": "<object>",  // ie order/cart/user etc so you know what type of object 
    "data": "<object data>", // object data (the api schema...)
    "event_id": "<unique event id>", 
    "event_type": "<event type>", // ie order.created
    "webhook": "<webhook info>",  // basic webhook info
    "api_version": "webhook api version" // schema structure of the data following API
}
```
The schemas (serializers) for this are powered by DRF serializers which are the base for the all schemas. This has worked wonderfully for us, gives us versioned webhooks and provides an upgrade path following our API schemas and relatively clean/clear consistent architecture with not a lot inconsistency issues. 

### Attempt to Document Webhooks using Open API Spec 3.1

Initially, I thought I could use the schema of the objects to inherit from the base schemas for the "data", and would be easy, but that's not the case. 

Using `{ "$ref": "#/components/schemas/XYZ }` does not actually pull in all of the schema elements. I tried all of the variations but "readOnly" properties don't show and there are many nested schemas that use these. 

I've also tried many ways of making a "deep copy" of the base schema and copying it over the webhook, removing "readOnly", etc but just looks like a deeper and deeper rabbit hole of the wrong way to go about this.

First attempt at a [webhook schema generator here](https://github.com/29next/developer-docs/blob/main/tools/webhooks.py).

**A way to reference a Response schema, or entire schema as readOnly?**
It turns out, I actually need a link to the full response format of a schema or just the entire schema and nested schemas as readOnly.

Is that possible or antithetical to core concepts?

Links to our schemas
- https://github.com/29next/developer-docs/tree/main/static/api/admin

Any guidance or can see where I might be going wrong?

**Comment by handrews** [comment]
@alexphelps `readOnly` was one of the few keywords that changed between 3.0 and 3.1 in order to align with JSON Schema.  In 3.0 it was recommended to strip `readOnly: true` fields from responses, but this violated the REST principle of GET/modify/PUT cycles and was burdensome for clients.  So in 3.1 `readOnly` follows the more vague definition in JSON Schema, and 3.1 tools should **not** strip fields.  It is only an error if you try to _change_ the field's value.

`writeOnly` fields, of course, do need to be stripped from responses since you're not supposed to be able to read them at all.  The only changes to `writeOnly` in 3.1 (which also apply to `readOnly`) is removing the restrictions on how these keywords are used with `required`.

You might need to file an issue with your tooling provider if it is striping out `readOnly` fields, as that is incorrect in 3.1.

**Comment by alexphelps** [comment]
@handrews thanks for getting back to me. I believe I might need to clarify that we are using Stoplight Elements and `readOnly: rue` is working correctly for responses of standard requests. In my scenario/question, I'm unable to inherit/reference my core object schemas that use `readOnly:true` for webhooks because webhooks are `post` requests which follow the logic you've described. 

### Scenario with a `Cart`  that has nested `lines` and `user` objects

```yaml
components:
  schemas:
    Cart:
      properties:
        checkout_url:
          format: uri
          readOnly: true
        lines:
          items:
            $ref: '#/components/schemas/CartLine'
          readOnly: true
          type: array
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
``` 

The rest `/carts/` endpoints use the the `Cart` schema, it works well, the responses are generated correctly. 


### Using Rest Schemas for Webhooks

For webhooks, I was hoping that I could reference the `Cart` schema so I wouldn't need to duplicate the Cart schema itself, example below:

```yaml
webhooks:
  cart.abandoned:
    post:
      description: Triggers when a cart is marked as abandoned.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  allOf:
                     $ref: '#/components/schemas/Cart'
                event_id:
                  description: Unique id associated with this webhook event.
                  format:
                  - uuid
                  type:
                  - string
                object:
                  description: Object data type.
                  examples:
                  - cart
                  type:
                  - string
      security: []
      tags:
      - carts
    responses:
      '200':
        description: Return a 200 status to indicate that the data was received successfully.
```

### Issue
What I found is that because webhooks are `requests` they don't show `readOnly: true` fields in the generated webhook request examples. 

In the example above, the `checkout_url` is a simple field controlled by backend application that shows in the `Cart` response. When trying to `ref` the `Cart` schema for the webhook, it's expected that `checkout_url` should show in the webhook request, but it doesn't because it's marked as `readOnly: true`. 

### Webhooks Aren't Restful Endpoints
 Webhooks are more akin to `responses` than they are the `requests` by their very nature. Webhook requests themselves are a different context than restful endpoints because the webhook "receiver" has no control over the `request` data, webhook receivers are subscribing to the request data instead of providing the request data.  

I expect that `readOnly: true` fields would normally present in webhook requests due to the nature/context of webhooks. 

### Question
 Is it possible to forcefully override and include all `readOnly: true` fields (and nested readOnly:true) for webhook requests examples?  This would allow the reuse/reference of the core rest endpoint schemas for webhooks. 

Or is it expected that we need to create Webhook specific schemas to work around any `readOnly:true` fields that show in webhooks but aren't able to write to in the restful schemas?

I've written a script that recursively copies nested schemas and removes `readOnly: true` for webhooks and is working. 

However, I'm sure that I'm not alone in wanting to reuse schemas for webhooks and include `readOnly: true` in webhook examples. 

- Example script [here](https://github.com/29next/developer-docs/blob/main/tools/webhooks.py) 
- Example schemas [here](https://github.com/29next/developer-docs/tree/main/static/api/admin) (webhooks at bottom)
- Working docs [here](https://developers.29next.com/docs/api/admin/reference/#/)


Looking forward to hear your thoughts. I understand that webhooks are new in OAS 3.1 and expect there will be lots of feedback as more systems document their webhooks with OAS, thanks again.

**Comment by handrews** [comment]
@alexphelps my apologies again, I mistyped and wrote the opposite of what I meant with requests and responses.  I was also careless distinguishing REST and HTTP.  The correct statement would be:

> 1n 3.0 it was recommended to strip `readOnly: true` fields from ***requests*** but this violated the ***HTTP*** principle of GET/modify/PUT cycles and was burdensome for clients. So in 3.1 `readOnly` follows the more vague definition in JSON Schema, and 3.1 tools should not strip fields. It is only an error if you try to change the field's value.

So regardless of how we think of webhooks in terms of requests and responses, a compliant 3.1 implementation should _never_ strip `readOnly` fields.  Validation of read-only / write-only behavior is outside of the schemas, and those fields are just annotations that can inform code that is (unlike JSON Schema) aware of the direction of the operation what it should look for.

**Comment by alexphelps** [comment]
@handrews 

> Validation of read-only / write-only behavior is outside of the schemas, and those fields are just annotations

So, in your mind, all the `readOnly: true` fields of referenced schemas (and nested schemeas) should actually show in webhook request body samples?

You're suggesting that Stoplight has an issue with `webhooks` here?

**Comment by handrews** [comment]
@alexphelps it's not just "in my mind," it's a topic that we spent a great deal of effort on in the last stages of deciding how to handle `readOnly`, `writeOnly`, and JSON Schema compatibility in OAS 3.1.  It was one of the thorniest issues and generated a lot of discussion and debate.  It even got a mention in the [3.1 RC0 announcement](https://www.openapis.org/blog/2020/06/18/openapi-3-1-0-rc0-its-here), with a link to the longest discussion issue (which I don't recommend reading as it goes through many tangents and it's hard to see what we decided - the rest of the conversations happened in weekly calls.)

That said, the nature of the requirements in this area make it hard to say absolute things like "Stoplight is wrong on this."  The formal requirements in this area, for both 3.0 and 3.1, are SHOULDs and MAYs, and not MUSTs.

* 3.0 had SHOULDs around stripping `readOnly` and `writeOnly` fields in various directions (the parts about interactions withe `required` don't have normative language at all, and just way that things "will" be done)
* We [removed all of that](https://github.com/OAI/OpenAPI-Specification/pull/1977/files#diff-46ec063651641c099025333707cf648e00c20a50483d7103e8ccfda5e7ac2b34L2324) in 3.1, which doesn't mention `readOnly` or `writeOnly` anywhere, at all
* For 3.1, it's JSON Schema draft 2020-12 that governs those keywords, which (for `readOnly`) [says](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#autoid-61) _"attempts by an application to modify the value of this property are expected to be ignored or rejected by that owning authority"_, which also lacks normative requirement wording, but the key part is that "attempts... to **modify**" are what matter here

I could go into a lot more detail slogging through RFC 9110's sections on the PUT method and more generally on resource semantics.  But the upshot is:

* whether any particular API uses it or not, the GET/modify/PUT HTTP pattern ought to be describable in any spec that describes HTTP APIs
* PUT-ing (or writing with any other HTTP method) a field only runs afoul of `readOnly` if it is a _modification_, not just because it is there
* for many resource designs, stripping a field from a PUT request is interpreted as a deletion of the field, so tools that always do that for `readOnly` are significantly limiting resource design - as you have discovered with your webhooks

So... is Stoplight "wrong"?  Well, there are no normative mandatory requirements of which I'm aware that it is violating.  So in that sense, no.  But there is guidance that it is contradicting, and that guidance was provided in the context of the 3.1 change (many changes in JSON Schema 2019-09 and 2020-12, including, IIRC, a rewording of the `readOnly`/`writeOnly` text, were driven by the OAS 3.1 process).  So in that sense, yes, it's disregarding guidance and limiting what sort of resource design can be used with its tooling.

**Comment by alexphelps** [comment]
@handrews thanks for your detailed thoughts and context on the history of spec changes as OAS iterates forward. 

At this time, I was able to create a working solution to my webhook documentation issue by copying/modifying the source schemas while generating the webhook request specs. 

Will circle back and see how this changes as the tools we're using ([DRF Spectacular ](https://github.com/tfranzel/drf-spectacular)and [Stoplight Elements](https://github.com/stoplightio/elements)) continue updating.

**Comment by dontic** [comment]
@handrews sorry to refloat this thread but we've been having an interesting discussion over in:

- https://github.com/tfranzel/drf-spectacular/issues/1280

For more context please see the issue I opened in SwaggerUI where I link multiple issues describing this confusion across different tools:

- https://github.com/swagger-api/swagger-ui/issues/10114

First of all, thanks for breaking down the history and complexity of `readOnly` and `writeOnly` properties in OpenAPI. It's clear a lot of thought went into balancing flexibility and standardization.

I get the value of flexibility, but I've found it creates some real headaches when it comes to webhooks. Different tools interpreting these properties in their own way leads to inconsistent (and sometimes flat-out misleading) API docs.

Webhooks are a bit of a special child - many agree that the data flow should be flipped compared to regular endpoints. The current specs don't really address this, which leaves everyone guessing how to handle webhook payloads. This does not happen on normal API specs due to everyone being clearly aware of how `GET` and `POST` requests work.

An example:
> 3 UIs - 2 interpretations.
> 
> - SwaggerUI: webhook request as WRITE
> - Redoc: webhook request as READ
> - Stoplight Elements: webhook request as WRITE

I'm not advocating for super rigid standards across the board, but I think webhooks could really benefit from some clearer guidelines. Maybe something like:

- Some specific recommendations for dealing with `readOnly` and `writeOnly` in webhook contexts.
- A new property that flags the direction of data flow, so tools can be adjusted accordingly.
- Some best practices for documenting webhook payloads to keep things clear for API users.

This kind of guidance could help tool developers such as those over SwaggerUi, Redoc, etc., get on the same page, which would prevent confusion. It'd keep things flexible where needed, while solving this specific webhook documentation puzzle.

Would it be possible to add some webhook-specific guidance in the next round of OpenAPI specs, or maybe in a supplementary best practices doc? Though I'm no expert, I'd be happy to contribute to the discussion if that's helpful.

**Comment by alexphelps** [comment]
@handrews This [standard webhooks](https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md) doc is a good read. 

I too believe it's time for more formalized "webhook best practices" that are reinforced by tooling (ie open api spec and renderers). 

At this time, I've settled on a custom tool that generates the webhook payloads for the open api spec docs used in our [public documentation](https://developers.29next.com/docs/api/admin/reference/?v=2024-04-01) (docusaurus + stoplight), see [here](https://github.com/29next/developer-docs/blob/main/tools/update_api_docs.py).

**Comment by handrews** [comment]
@alexphelps Since webhooks are only part of OAS 3.1 (when used in 3.0, they are an extension and therefore not controlled by us), there's not but so much to say here.  The only thing that seems unusual is the confusion over read/write direction, but I don't really understand that because whichever side receives HTTP requests and sends HTTP responses (regardless of whether those requests and responses are considered part of a webhook) is the owner of the resource per the HTTP RFCs.

Read and write are always relative to the resource owner, so that tells you the direction.

I'm really not sure what we should do here.  It seems to me like existing standards (JSON Schema, HTTP) cover this.  It doesn't really have anything to do with OAS proper (e.g. everything except JSON Schema)

**Comment by alexphelps** [comment]
@handrews Sorry, I mean't to reply to @dontic 

 I agree, this is probably no action at this time. The REST object schema re-use structure that @dontic and I are aiming for I believe is a higher level than just pure HTTP. Just like HTTP APIs weren't always "Restful" like we tend to think of them today, webhooks are still in their infancy in terms of standardization. I'm on a project that is integrating with a large fintech platform with  webhooks that:
- settings toggle data prodvided in webhooks 
- webhooks for objects/events that don't have accompanying restful GET methods

It's quite a differen't experience than building on top of Stripe who has great webhooks. 

Zapier coined the term ["Rest Hooks"](https://github.com/zapier/resthooks?tab=readme-ov-file) years ago that I believe are more akin to what we're aiming for with the reuse of schemas across both restful http endpoints and webhook events.

**Comment by handrews** [comment]
@alexphelps got it, thanks!  The underlying problem here is that JSON Schema was not really designed with HTTP-aware validation in mind, so any choice we make here will be somewhat sub-optimal because of that.
