### ISSUE TITLE
Meaning of the term API in the operationId context.

### ISSUE THREAD

**Issue by bachp** [OAI/OpenAPI-Specification#381]
In the context of an [`operationId`](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject). the spec says:

> The id [operationId] MUST be unique among all operations described in the API

What is the definition of API in this context?
Does it mean all operations defined in the same file?
All operations used by an application?

Did I just miss the definition or should this be clarified?

**Comment by webron** [comment]
That's a fair question and needs to be clarified.

The 'basic' limitation would be within the same Swagger description. The real challenge is how it would behave when referencing external files.

**Comment by jfiala** [comment]
If I understand this correctly, the operationId currently has to be unique for each API endpoint an application provides. If it provides multiple API endpoints, the operationId is only required to be unique per API endpoint.

Currently I use Swagger Springfox/Codegen to generate code and I get one API class for each controller class (tag). IMHO in fact, it would be totally sufficient to demand that the operationId is unique per RequestMapping path/tag/controller/API class.

What the current interpretation of the specification leads to is that the operationId is suffixed with numbers to guarantee its uniqueness.

Request Paths:
/pet/find
/category/find
/person/find

Generated API definition (provided by Swagger Springfox):
"/pet/find": operationId: findUsingGET
"/category/find": operationId: findUsingGET_1
"/person/find": operationId: findUsingGET_2

The generated code using Swagger Codegen then looks like this:
PetAPI.findUsingGET()
CategoryAPI.findUsingGET_1()
PersonAPI.findUsingGET_2()

So in fact, although IMHO it would be totally sufficient to scope the uniqueness of the operationId per tag/API class, it is now suffixed and generates hardly understandable client code with lots of suffixes.

The current solution to this is to use nicknames for the operations and name them uniquely:
"/pet/find": operationId: pet_findUsingGET
"/category/find": operationId: category_findUsingGET
"/person/find": operationId: person_findUsingGET

This solution is unsatisfying so far that it adds a scoping to methods that are already scoped:
PetAPI.pet_findUsingGET()
CategoryAPI.category_findUsingGET()
PersonAPI.person_findUsingGET()

Wouldn't it be sufficient to demand that the operationId is unique per tag it is associated to (or per Request Path)?

**Comment by MikeRalphson** [comment]
> what if I simply get rid of the OperationId? It isn't mandatory, is it?

No. And if present, they can be anything you wish, including unique integers, hashes etc.

**Comment by RobThree** [comment]
Exactly, that's what I gathered. But I guess my question is: is it used "in the field"? Is there tooling or whatever that's dependent on the OperationId? Is it better to provide an OperationId (be it a hash or integer or string like `GetPetByName`) to better assist tooling or should leaving it out have negligible effects? And _should_ I choose anything other than the, what seems to be commonly used, `GetPetByName`-like operation ID's, what will the consequences be of having non-descriptive "ID's"?

But so far I'm heavily considering removing OperationID's alltogether from my swagger document.

**Comment by MikeRalphson** [comment]
Yes, I would *personally* recommend providing a descriptive `operationId` if you can, in case your OpenAPI document is ever used for code-generation. The consequence would be less readable generated code / debugging / errors etc.

**Comment by handrews** [comment]
@MikeRalphson Operation IDs are primarily for use in Link Objects, right?

**Comment by MikeRalphson** [comment]
I'd not say primarily, as they predate the presence of links in the spec., but that is another use as a shorthand for path + method.

**Comment by darrelmiller** [comment]
Tooling uses OperationId fairly extensively.  Readable OperationIds are generally preferred as it makes it easier to hand edit documents.

**Comment by bobvanderlinden** [comment]
I personally think the `operationId` has its use (unique identifier for operations). However, I think it is being misused in many cases.

One tool that is misusing it is the codegen. It uses the `operationId` for method name and uses the tag(s) for classname. The method names do not need to be unique across all classes. This becomes especially awkward when the `operationId` is generated from existing code (like Java) where methods do not need to be unique across all classes. Perfectly reasonable looking Java code is incorrect because methods names are now suddenly unique across classes.

For codegen it would be nice if we could just specify what the classname and methodname should be, separate from the `operationId`.

For Swagger-UI the operationId is correctly used IMO. It isn't being shown as a kind of 'short name'. It is actually a unique identifier _just_ to reference a specific operation. The operation can be referenced using the `#` in the URL and (from what I gathered) is used internally to reference JS/HTML elements.

A UUID in this case makes perfect sense and seems more stable than a user-defined Id that needs to look good in order to use it as a method name.

**Comment by joanjames-zebra** [comment]
Besides codegen and apigee SmartDocs, which tools actually use the operationId? 

We started with title case and spaces between words in the operationId for SmartDocs rendering which uses the operationId for titles. Now it seems the spaces may cause trouble in other tools. According to the OpenAPI Spec definition of the operationId ' .. it is RECOMMENDED to follow common programming naming conventions'. 

Now I am wondering if we should convert the operationId to Camel Case or hyphenated words?  The operationId is being ignored by our current rendering. The summary and description are being used. 

What is the best practice for the operationId?

**Comment by bobvanderlinden** [comment]
What we are doing is create operationIds from classname and method name. For instance something like: `UserController.byId`. That way it is unique and human-readable. However, when we're passing the specs to a codegen, then we're transforming the specs so that the tag of the operation becomes `User` and the operationId becomes `byId`.

This results in general use we have a valid specification. For codegen we have an invalid specification (`byId` is not unique), but it will at least work for the codegen.

I wouldn't call it 'best practice', but it is how we're coping with this issue.

**Comment by rkishchenko** [comment]
The issue I am seeing is auto-generated `operationIds` is that in its attempt to enforce uniqueness the generator produces random permutations of the ids. So, for example, for a given method, say, in a class `UserController.updateUser()` the generator produces either `updateUser` or `updateUser_1`, etc each time the generator is run. Clearly, this non-deterministic behavior is a bug. A trivial fix is to generate those IDs using fully qualified class name + method.

**Comment by handrews** [comment]
Fixed by #3823 and #3906
