### ISSUE TITLE
The `paths` property pattern is wrong in v3.1

### ISSUE THREAD

**Issue by Gorniaky** [OAI/OpenAPI-Specification#4124]
The current pattern is considering any `/path` entry as an error, when it shouldn't.

![image](https://github.com/user-attachments/assets/0d2abb22-80c8-4cd8-bcab-7c4dea768432)

**Comment by handrews** [comment]
@Gorniaky `$schema` is a JSON Schema keyword, not an OpenAPI Specification field.  You cannot use it outside of the Schema Object.  The JSON Schema for an OpenAPI Description is implied by the `openapi` field.

**Comment by Gorniaky** [comment]
> @Gorniaky `$schema` is a JSON Schema keyword, not an OpenAPI Specification field. You cannot use it outside of the Schema Object. The JSON Schema for an OpenAPI Description is implied by the `openapi` field.

I use `$schema` to have autocomplete, but that has nothing to do with the issue.

**Comment by handrews** [comment]
@Gorniaky regardless of how you are using `$schema`, what you have posted in this issue is not a valid OpenAPI document, so I don't know how else to address it.  We also cannot provide tooling support, so if you expect a specific tool to work with what you have posted, you will need to take that up with your tooling provider.

**Comment by Gorniaky** [comment]
> @Gorniaky regardless of how you are using `$schema`, what you have posted in this issue is not a valid OpenAPI document, so I don't know how else to address it. We also cannot provide tooling support, so if you expect a specific tool to work with what you have posted, you will need to take that up with your tooling provider.

Is this serious? You didn't even analyze the problem, it's not an external problem, it's within the v3.1 standard that has a bug in the regexp pattern in the `paths` keyword.

**Comment by Gorniaky** [comment]
I analyzed the problem, and I came to this conclusion:

You cannot write other specifications next to the `$ref` keyword, the `$ref` keyword overrides the other specifications, causing a bug in the schema.

![image](https://github.com/user-attachments/assets/fc4a3327-3e88-428b-984e-06c0b253534d)

**Comment by Gorniaky** [comment]
The most amazing thing is that they wrote this bug in other keywords in the scheme

**Comment by jdesrosiers** [comment]
The schema is correct. This schema is written for JSON Schema 2020-12. In a previous version (2019-09), the way `$ref` works was changed in a way that means keywords next to `$ref` don't get ignored.

The actual problem is that your editor doesn't support JSON Schema 2020-12. Unfortunately, vscode has not chosen not to update their JSON Schema support for over 5 years despite multiple community requests.

Anyway, instead of messaging the user that the schema might not work properly, it ignores the version and evaluates it as if it were a draft-07 schema. Then you end up with the kind of issues you're encountering.

**Comment by Gorniaky** [comment]
> The schema is correct. This schema is written for JSON Schema 2020-12. In a previous version (2019-09), the way `$ref` works was changed in a way that means keywords next to `$ref` don't get ignored.
> 
> The actual problem is that your editor doesn't support JSON Schema 2020-12. Unfortunately, vscode has chosen not to update their JSON Schema support for over 5 years despite multiple community requests.
> 
> Anyway, instead of messaging the user that the schema might not work properly, it ignores the version and evaluates it as if it were a draft-07 schema, which results in the kind of issues you're encountering.

Oh, thanks for the explanation.

**Comment by valerii15298** [comment]
I stumbled against this same problem. It is a shame that vs code does not support `JSON Schema 2020-12`, so I ended up patching the openapi json schema to make it work with vs code. Also needed. to substitute `$dynamicRef` with just `$ref`.

For this problem the solution is to patch schema `paths` like this so that `$ref` does not override `patternProperties`:
```json
    "paths": {
      "$comment": "https://spec.openapis.org/oas/v3.1#paths-object",
      "type": "object",
      "patternProperties": {
        "^/": {
          "$ref": "#/$defs/path-item"
        }
      },
      // instead of just "$ref": "#/$defs/specification-extensions"
      "allOf": [{ "$ref": "#/$defs/specification-extensions" }],
      "unevaluatedProperties": false
    },
```
