### ISSUE TITLE
schema updates for 3.0.4

### ISSUE THREAD

**Issue by karenetheridge** [OAI/OpenAPI-Specification#4125]
The 3.0.4 schemas need a review pass for accuracy.

- [ ] update `$comment`, `description` and `$id` URIs for v3.0.3->v3.0.4 (where can an html preview of the specification be viewed?)
  - will be available at https://spec.openapis.org/oas/v3.0.4.html
- [ ] ensure links in specification (referencing schema files) are correct
  - 3.0.4 and 3.1.1 will link to https://spec.openapis.org/ which now has a subsection "Non-Normative JSON Schemas" with "view" and "download" links
- [ ] compare specification and schema diffs from 3.0.3 and 3.0.4, thinking about any spec changes that haven't yet been reflected in the schemas, and what changes have been made to the schemas already and confirm they are accurate (this SHOULD be a no-op, but mistakes have occasionally happened before ;) )
- [x] ensure the .json and .yaml files are consistent
- [x] verify validity against the draft4 json metaschema  
  (I am converting locally to draft7 so as to allow: `apt-get libjson-schema-modern-perl; json-schema-eval --strict --validate-schema schemas/v3.0/schema.json`)

**Comment by handrews** [comment]
There are definitely improvements to be made to the 3.0 schemas, but there aren't any schema-impacting differences between 3.0.3 and 3.0.4.  The only version-ish thing that should change is the date in the `$id` of the schemas.

AFAIK, this is true across 3.0.0 - 3.0.4, and any schema applying to one applies to all and should only mention 3.0 in comments or other text (no patch release number).  Some might make an argument regarding `nullable` in 3.0.0 – 3.0.2 va 3.0.3 – 3.0.4.  However, the official position is that the clarifications to `nullable` in 3.0.3 were only clarifications (it made the relationship between `nullable` and `type` behave the same way as the relationship between draft-04 `exclusiveMinimum` and `minimum` (and `exclusiveMaximum` and `maximum`).

Schemas can be viewed [on the spec site](https://spec.openapis.org/#non-normative-json-schemas).  I didn't think to comment on it in the 3.1 schema issue, but I'm pretty certain the spec should just link to this page and not to anything specific.  (For those not familiar with the history of "latest" schemas, we should not have a "latest" schema symlink because refining the constraints to be more accurate could cause automated systems to suddenly invalidate previoulsy-valid OADs which is not a nice thing to do – we tried this several ways with the JSON Schema meta-schemas before deciding on the date-based `$id`s to avoid ever changing a schema in place).

**Comment by karenetheridge** [comment]
Note that the PR coming from this issue will be a blocker for 3.0.4. I have some of the more trivial fixes completed already, so please poke me if I should PR those now.

**Comment by handrews** [comment]
@karenetheridge how will it be a blocker?

Logically, I agree that we should have the schemas done for the release, but we never have in the past and the current 3.0 schemas won't be any worse for 3.0.4 than they are for 3.0.3.  So what would break so badly that we should consider it a blocker?

(If you want to argue that we should publish the schema fixes simultaneously with the patch release just on general principle, I'd support that, but I've never been successful with that argument here in the past).

**Comment by karenetheridge** [comment]
> I agree that we should have the schemas done for the release, but we never have in the past

I see; I wasn't aware of that.

> If you want to argue that we should publish the schema fixes simultaneously with the patch release just on general principle

Yes, it was my assumption that this was the case. Otherwise how can tooling vendors proceed with adding support for the new release?
