### ISSUE TITLE
No release includes the fixes to the cross-references

### ISSUE THREAD

**Issue by MikeSpreitzer** [OAI/OpenAPI-Specification#4135]
Recall that #3548 tracked a change in how GitHub renders markdown to HTML, 8 months ago. There is not yet any tagged commit in this repo that includes this fix.

**Comment by handrews** [comment]
@MikeSpreitzer that's because they're not re-releases and you can't really change tags in git (not without causing tons of problems).  For the `versions` directory, the markdown on the `main` branch is what's rendered as HTML on spec.openapis.org (for the `schemas` directory its more complicated and currently under review).

We made the changes in-place for convenience of people browsing in GitHub, because broken links are bad.  But it's not a change in the spec itself.

**Comment by handrews** [comment]
@MikeSpreitzer if that doesn't make sense, it would help to know what you're trying to do with the tags.  When we made that change, we couldn't really figure out how the tags were used (no one involved in deciding to make them was available and remembered).

**Comment by MikeSpreitzer** [comment]
I was not asking for a change in a tag, I was asking for a new tag. 3.1.1 fits the bill. Thanks!
