### ISSUE TITLE
Discrepency between types and description in discriminator mapping type

### ISSUE THREAD

**Issue by jgresty** [OAI/OpenAPI-Specification#4138]
The discriminator mapping type is defined as `Map[string]string` however in the description for that type some ref types are used: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#discriminator-object

Is this intentional?

**Comment by handrews** [comment]
A URI reference like `#/components/foo` is a string, and the other fields wtih similar referencing behavior (Reference Object and Path Item Object `$ref`, as well as Link Object `operationRef`) that take such values are all also defined as type `string`, so I think the current documentation is correct and consistent.  It just happens that `mapping` can take two types of strings:  A URI reference or a plain component name.

**Comment by jgresty** [comment]
Fair enough, I would argue that using a different logical type would prevent this ambiguity but at least it is consistent.

**Comment by handrews** [comment]
@jgresty thanks- I think the "type" column just uses JSON (or JSON Schema) types plus OAS-define "Object" types, which is why you don't see more specific type definitions.  Anything more specific is in the description.  Perhaps not the most precise, but it matches the main cross-platform technology (JSON Schema) used for type enforcement right now.
