### ISSUE TITLE
schema.json files were removed

### ISSUE THREAD

**Issue by leandrodamascena** [OAI/OpenAPI-Specification#4149]
Hello everyone! I saw in this [PR](https://github.com/OAI/OpenAPI-Specification/pull/4137) that the files https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json and https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json were removed because they should not be the source of truth. It turns out that I use these files a lot in my CI to compare and validate my OpenAPI schemas in many tests. I download and store them, but I update the file every 1 hour and now it's failing and breaking my CI.

I generate my OpenAPI schemas in JSON and not in YAML, which is a practice used by many and accepted by the specification.
Is there any chance to revert this change? 

Thanks.

**Comment by ThomasRooney** [comment]
Note: this also broke schemastore (reporting in the Slack at https://open-api.slack.com/archives/C0EDH2QKD/p1729499316054029) -- i.e. IDE type hinting globally for for OpenAPI.

1. Schemastore is how almost every IDE/editor gets intellisense/auto-complete for arbitrary json/yaml files. It's pointed at https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
2. When it's configured right, users of OpenAPI see auto-complete like the following (attached). This is a really nice DX.
3. Since that change got merged, developers will start to see some kind of "JSON Schema Error" error, and no auto-complete (attached) in their editors. There's usually a caching period / expiry but I'm personally seeing it now.
4. Schemastore URIs are in https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L3644-L3651. We could update that to point at somewhere else, but I think it's relatively clean to use this github repo's `main` branch as the "source of truth".

Can we bring them back 🙏

**Comment by ralfhandl** [comment]
The `id` or `$id` URI of these schemas is also the URL with which they can be fetched, for example
* https://spec.openapis.org/oas/3.0/schema/2021-09-28
* https://spec.openapis.org/oas/3.1/schema/2022-10-07
* https://spec.openapis.org/oas/3.1/meta/base
* https://spec.openapis.org/oas/3.1/dialect/base

See https://github.com/SchemaStore/schemastore/pull/4159

**Comment by ralfhandl** [comment]
@leandrodamascena Thanks for reporting this!

@ThomasRooney Thanks for pointing us to SchemaStore!

**Comment by handrews** [comment]
@leandrodamascena and others who might be reading, to explain why this happened:

We're working to make it more clear that the files on `main` are not intended for use, only the published files with URIs documented in `id`/`$id`.  The JSON files on `main` were removed because they were _intentionally_ out of sync because of a policy of only updating the YAML files directly.  This was very confusing, so we got rid of the misleading files, meaning that the only place you can find the JSON documents is the official place.

The YAML documents and README are being further updated in other open PRs right now.

**Comment by leandrodamascena** [comment]
Hi @handrews and @ralfhandl, thanks for clarifying this! I was able to get it working using the new URLs extracted from the base document, thanks.

Closing this issue.

**Comment by ralfhandl** [comment]
PR for Schema Store has been merged:
* https://github.com/SchemaStore/schemastore/pull/4159
