### ISSUE TITLE
Schema for 3.1 contains links to 3.1.0 specification

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#4181]
The current schema for v3.1 contains comments pointing to the 3.1.0 specification:

https://github.com/OAI/OpenAPI-Specification/blob/c2e94272864d202252e7a97ac5fca6811d13056d/schemas/v3.1/schema.yaml#L56

Should we
1. Update these comments with every minor version, or
2. Remove these comments`?

**Comment by karenetheridge** [comment]
As I am the person that added them, I would much prefer updating them rather than removing them. I found references linking the main parts of the schema to the section in the specirication that described them to be quite useful when implementing my validation tool.

However, a simple "3.1.0" -> "3.1.1" search/replace won't do because some sections may have moved around in the document during the revision. This is why I identified a task item to go through and check these in the 3.1.1-dev issue that is now closed.

**Comment by handrews** [comment]
We have a "latest" symlink (or copy?) for the spec, which is great because specs (unlike schemas) are primarily for humans.  So we can use the "latest" URLs and then we just have to worry about updating the fragments.  I did try to keep those as close to what they were as possible, and none of the Object sections will have changed.  So that should be fine.

Going forward, we might need a "v3-1-latest", "v3-2-latest", etc. to make this work, though.

**Comment by ralfhandl** [comment]
Should we use use symlinks instead of copies?

**Comment by handrews** [comment]
@ralfhandl I don't actually know what we use right now but it seems fine whatever it is.  I'm indifferent if someone wants to change it.

**Comment by ralfhandl** [comment]
Please check
* #4191

Not sure whether I prefer `v3.1.html` over `v3.1-latest.html` for the symlink name.

@karenetheridge @handrews Opinions?
