### ISSUE TITLE
Way to denote inactive/beta endpoint?

### ISSUE THREAD

**Issue by diogeneshamilton** [OAI/OpenAPI-Specification#432]
Hoping there is/will be a way to define the endpoint using Swagger, but denote that it has not been released yet. Have people thought of this already and just made the responses error out?

**Comment by webron** [comment]
There's only a way to denote an operation as deprecated, which is the post step, not the pre ;)

**Comment by diogeneshamilton** [comment]
Hmm, maybe it could be called `beta

**Comment by webron** [comment]
There's no direct way to do that in the spec right now. Would you like to mark it as a feature request for future consideration?

As a workaround for now, you can use your own vendor extension to specify that on an operation (`"x-beta": true` for example).

**Comment by diogeneshamilton** [comment]
@webron yes, I think it's something that could make sense in the next version. I'll use an extension for now.

**Comment by jasimmonsv** [comment]
a label as experimental is what I was looking for. Just for consideration.

**Comment by ChristianLutz** [comment]
I would prefer either `beta` or `experimental`, both express what the purpose is.

**Comment by bkabrda** [comment]
👍 to reopen and add this. This would be an extremely useful addition and IMO can be added in a backwards compatible way.

**Comment by BelfordZ** [comment]
We've adopted the MethodObject field `deprecated: Boolean`. Seems like a reasonable addition for the inactive portion.

**Comment by bkabrda** [comment]
@BelfordZ yeah, `deprecated` is useful, but for my usecase, I need to use both `deprecated` (old, not to be used) and `beta` (new, possibly unstable and changing) endpoints. For now, we're going with using something like `x-beta` or `x-unstable` on individual operations. Long term, we'd like to see this in the openapi spec because we're heavily using [openapi-generator](https://openapi-generator.tech/) and adding a code that would handle our custom specification extension is (understendably) no-go for that project.

**Comment by MikeRalphson** [comment]
@bkabrda Just for clarification, what changes in generated code would you expect for a beta or unstable operation? An annotation, logging etc?

**Comment by bkabrda** [comment]
@MikeRalphson what we do is quite opinionated - we do a downstream patch of openapi-generator templates that make the unstable operations raise exception unless they were explicitly enabled in the code that uses the generated client library. This is our mechanism of getting user consent on the fact that the unstable API might break. We also always log a warning when an unstable method is called (even when explicitly enabled).

I think the right approach to unstable operations is debatable, but openapi-generator allows parametrizing how the templates are rendered and that would give us enough space to do different things based on options given during code generation. So given how strict you want to be with your generated client library, you might want to use annotations or logging or requiring explicit user consent - or a combination of these.

**Comment by takato1314** [comment]
Hi. Are there any plans for introducing this notation into the specification? As @MikeRalphson said the usage should be opinionated.

For example, I would expect perhaps something like this in my swagger ui display to indicate that a particular version of the API is still `experimental` and some note/message should be displayed just under the main heading of the document.

![image](https://user-images.githubusercontent.com/10910968/109694903-436ead80-7bc6-11eb-9e70-a46305645914.png)

**Comment by pengying** [comment]
I'd like to have the granularity to mark paths or fields in objects as experimental or beta.  I don't expect it to impact the library but would be handy to highlight in documentation services.

IMO would be useful to formalize x-beta -> beta or experimental

**Comment by lashchev** [comment]
I would prefer "experimental" as the term for unstable items (paths, operations, properties).
"Beta" in a lot of cases is considered as a "preview," and people usually expect API to "graduate" from beta status eventually.
"Experimental" clearly indicates that the future of this element is unknown - it can change in any way or disappear entirely.

**Comment by fgabolde** [comment]
I still want this feature, at the operation, parameter and schema level. Wherever `deprecated` makes sense, `experimental` would also makes sense, and like `deprecated`, it doesn't need to have actual behavior behind it, but standardizing it would allow tools to make use of it.

In particular, we are using https://github.com/OpenAPITools/openapi-diff (somebody earlier in the thread mentioned swagger-brake which was its spiritual predecessor, I believe) and we would like it to skip alerting if an experimental operation has changed.

**Comment by bdunavant** [comment]
Noting that I also found this thread because I am trying to work out how to mark something at experimental, so customers know that field/endpoint may mutate until we decide to support it long-term.

**Comment by kr99** [comment]
For now, I will probably just document the endpoint as `GET /beta-2/things`

**Comment by Welchen** [comment]
This feature would be very helpful. Either a beta or experimental tag.

**Comment by kevinforrestconnors** [comment]
I am also in need of a "beta" feature (we call it "under construction")

**Comment by ssavkovic** [comment]
Same here, we really need "Beta" tag for the new unstable endpoints.

**Comment by fkreis** [comment]
👍 Upvote for a beta/experimental tag!

**Comment by thbar** [comment]
Experimental would also be helpful for us! We have a fully open-source app at https://transport.data.gouv.fr, and sometimes the internal APIs get gradually exposed on our SwaggerUI page (https://transport.data.gouv.fr/swaggerui), in which case we prefer to mark them explicitly as experimental/internal/unstable.

This issue is closed, I wonder if something else would fit the bill!

**Comment by crabvk** [comment]
With OpenAPI 3.0 I [just add tag](https://swagger.io/docs/specification/grouping-operations-with-tags/) `proposal` to a path. Using [Redocly](https://github.com/Redocly/redocly-cli) it shows at the bottom of the paths list as
![20240102_220858-DJBUOMNx](https://github.com/OAI/OpenAPI-Specification/assets/3273827/e8199153-2ef0-481a-87d0-27d22481a868)

**Comment by andrezszambrano** [comment]
It is a shame they keep closing this issue.

**Comment by handrews** [comment]
@crabvk 

> It is a shame they keep closing this issue.

"They" don't "keep closing" this issue.  The issue was closed _six years ago_ by the person who filed it.   Why do people keep commenting on closed issues?  BTW, a [proposal for an `experimental`](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2020-10-28-Experimental.md) has been accepted for consideration in a future version.  There are also other open issues about lifecycles and versioning.

If you want to discuss a different feature, open a new discussion or issue.  Don't comment on closed ones that we don't monitor, except to lock them when people won't stop commenting on them.  Which doesn't mean no one wants to talk about it, it just means that we don't recycle old issues that were correctly closed many years ago.
