### ISSUE TITLE
Spec 2.0, confusion for schema definition and content-type

### ISSUE THREAD

**Issue by weching** [OAI/OpenAPI-Specification#539]
Hi,

For response schema definition, spec says:
>A definition of the response structure. It can be a primitive, an array or an object. If this field does not    
>exist, it means no content is returned as part of the response

"It can be a primitive", that's mean I can define a schema like:
>{ "schema": 
>    {"type":"string"}
>   }

So the question is, if I only have a primitive type defined(like above 'string'), then what response content type should be, "text/plain"? Or can be "application/json" or "application/xml" also?
If can be "application/json", then what the value should be, some simple text like "abc..."? Then this not a json.

**Comment by webron** [comment]
The spec can't address all combinations that don't make sense and add restrictions to those. So yes, if you send primitives, you *should* set the mime type to `text/plain` or something similar. Just because the spec allows you to do something, doesn't mean you should.

JSON Schema is very similar in that sense. It allows you to define things that don't make sense - it's a tool to help you describe what you have. It's up to the user to use it to describe their content properly.

**Comment by weching** [comment]
@webron Thanks for your reply.
