### ISSUE TITLE
Spaces inside $ref

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#545]
Swagger spec reference JSON Schema for `$ref`, which in turn reference JSON Pointer:
http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
Which says:
```
The "$ref" string value contains a URI [RFC3986], which identifies
   the location of the JSON value being referenced.  It is an error
   condition if the string value does not conform to URI syntax rules.
```
According to [RFC3986](https://tools.ietf.org/html/rfc3986#appendix-A) **space** forbidden in URIs.

With that in mind, take a look at this Swagger sample:
```
{
  "definitions": {
     "name with space": {}
     "schemaWithReference": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/name with space"
        }
     }
  }
}
```
According to RFCs value of `$ref` should be `#/definitions/name%20with%20space`.
@webron Am I right?

It's really important issue because I see multiply occasion when people use spaces in names of schema objects. And it causing issues with libraries for example:  https://github.com/BigstickCarpet/swagger-parser/issues/31
We need to have official decision on how to handle such situations.

**Comment by whitlockjc** [comment]
The JSON Reference specification says that `$ref` must be a valid URI.  It is the responsibility of the tooling to enforce and validate the `$ref` value.  I don't see how the _"official decision"_ hasn't already been made because of the fact we're using JSON References and the JSON Reference specification clearly says what is valid and what is not.

**Comment by whitlockjc** [comment]
As for this _"causing issues with libraries"_, not all libraries are affected by this.  For example, [Sway](https://github.com/apigee-127/sway), via [json-refs](https://github.com/whitlockjc/json-refs), already handles identifying invalid `$ref` values.  *(To be fair, json-refs has not always done this and this came along in the `1.0.0` release.)*  The library json-refs uses is [uri-js](https://github.com/garycourt/uri-js).

**Comment by IvanGoncharov** [comment]
@whitlockjc My previous experience show that it's better to ask here before doing any PRs.
I also want to  add regex into JSON Schema for Swagger format to forbid spaces inside `$ref` in all validators even if they don't do any resolutions, like [validator-badge](https://github.com/swagger-api/validator-badge).

About support in `sway`, I tried online demo of `swagger-editor` and it fail to validate following spec:
```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths: {}
definitions:
  'name with space': {}
  schemaWithReference:
    type: array
    items:
      $ref: '#/definitions/name%20with%20space'
```

**Comment by whitlockjc** [comment]
Asking makes sense, as this is the proper venue for it.  I just think there are times where we don't have to go into a lot of extra detail because the technologies we use, like JSON Schema and JSON References, have their own rules that are already laid out.  But if we feel it makes sense to make our documentation better, I wouldn't push back on it.

As for your test, swagger-editor is out of date.  I think the plan is to update swagger-editor's Sway when 1.0.0 releases, which should address your test.  I did find a bug in json-refs verifying this and it will be included in Sway 1.0.0.  ;)

As for making things better, why couldn't we use `format: uri` in the JSON Schema for the `jsonReference` [definition](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L1578)?  JSON Schema validators should catch this, although I'm not guaranteeing they will.

**Comment by IvanGoncharov** [comment]
@whitlockjc `format: uri` mean it should be valid URI
But according to [RFC3986](https://tools.ietf.org/html/rfc3986#appendix-A) in ABNF notation:
```
URI = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
```
Or in [text](https://tools.ietf.org/html/rfc3986#section-1.1.1):
```
Each URI begins with a scheme name
```
So usual values like: `#/foo/bar` isn't valid URI.
It actually [Same-Document Reference](https://tools.ietf.org/html/rfc3986#section-4.4) which is belong to wider class of `URI references`.
So we can't use `format: uri`, but space is invalid both inside `URI` and `URI references` so we can do simple regex: `^[^ ]+$`.
It's not idea but help with validation, in `description` of `jsonReference` we can add note about how to properly encode `$ref` values.

IMHO, We shouldn't make Swagger users to read through JSON Schema, JSON Pointer and RFC3986.

**Comment by whitlockjc** [comment]
Ah, good point.  I didn't realize that the JSON Schema `uri` format did not cover all URIs.  As for making Swagger users read through specs, I agree with your opinion that they shouldn't have to.  Making the JSON Schema file for Swagger eliminate more invalid URIs at the JSON Schema validation level makes sense to me as it makes the tooling authors lives easier.  When it comes to documenting things, I don't know where the line is drawn.  There's a fine line between good documentation and overly verbose hand holding because you try to document every possible case where someone may not already be knowledgeable.

**Comment by IvanGoncharov** [comment]
Let's hear @webron decision.
Maybe we need some kind of FAQ for Swagger spec.
Or maybe it exist somewhere and I just don't know about it?

**Comment by webron** [comment]
Thanks @IvanGoncharov for bringing the issue to our attention.

Here's my take on the matter. The OpenAPI/Swagger specification uses other specifications as part of it, in many cases as-is. The spec itself documents (or at least attempts to) the variations from the original specs. For example, for JSON References it documents that it only canonical dereferencing, or for JSON Schema, that only a subset is supported (and there are others).

The goal of the JSON Schema for OpenAPI/Swagger is more about validating the structure. The schema alone cannot cover full validation anyways, due to restrictions in JSON Schema and the complexity of the spec. In fact, there are some things we deliberately decided to ease up in the schema, if only to clean it cleaner. For example, we had issues with mime-type value declarations, and a community member helped in creating this insane regex that checks for the ABNF notation of mime types. Eventually we decided to just not validate the value at all, because it is not really the main issue and concern.

Granted, JSON References do have an extra impact on using specs, but let's face it, in practice any tool could easily just escape the whitespaces according to the spec if it hits those and do its best. Just like any browser today deals with such small discrepancies whether an HTML is fully valid or not.

As a side note, as far as I know, the people behind JSON Schema are still debating whether `format: uri` has to be a full URI or a partial URI is supported as well (regardless of what may or may not be written in the spec itself). We used it ourselves in the JSON Schema but dropped it because it caused problems with some parsers.

As for the comment about whether OpenAPI users should read through JSON Schema, JSON Pointer and so on - I tend to disagree. Pretty much any specification out there uses other specifications, and references those specifications as part of their description. They don't re-describe these solutions but use them. And just like in the OpenAPI spec, they concentrate on the details that differ. For example, JSON Reference explains how its value is parsed, and explains under exactly what circumstances and what part of it is parsed as a JSON Pointer. This differs greatly than treating the whole value as a JSON Pointer as @whitlockjc has experienced himself in the past ;)

With all that in mind, I think it's absolutely valid to have an FAQ, or any number of written guides, and personally would welcome those into this repo. We do have one guide right now, which may be split into two, one of which will talk specifically about JSON References. Should that happen, I think it would make perfect sense to add that extra subtlety there.

**Comment by IvanGoncharov** [comment]
@webron Thank you for clarification.

I agree with @whitlockjc:
>I just think there are times where we don't have to go into a lot of extra detail because the technologies we use, like JSON Schema and JSON References, have their own rules that are already laid out.

So I close this issue.
