### ISSUE TITLE
JSON Schema future draft specifications

### ISSUE THREAD

**Issue by drobri** [OAI/OpenAPI-Specification#590]
How will OAI specification track future JSON Schema Drafts and Stanards?  https://github.com/json-schema/json-schema/issues/167

All  the of the existing IETF drafts have all expired (Draft 4).

**Comment by webron** [comment]
If we stick with a single model description language (JSON Schema in this case), a given version of the spec will declare a specific version of JSON Schema. As long as draft 5 is mutating, we can't support it. If we finalize the next version of the OpenAPI Spec before draft 5 is finalized, we won't be able to use it (even if it's finalized too deep into the process). It's even more complicated because it's not enough to have draft5 stable, there also needs to be proper tooling support which would take time.

Expired or not, it is defacto the standard right now.
