### ISSUE TITLE
Problem with SSL certificate on https://openapis.org/

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#617]
I think screenshot is self-explanatory:
![selection_029](https://cloud.githubusercontent.com/assets/8336157/14193919/cf202898-f7b1-11e5-971d-93c78854d67a.jpg)
I think it's common issue but I will still provide version of my browser:
Chromium Version 48.0.2564.82 Ubuntu 15.10 (64-bit)

**Comment by ePaul** [comment]
Just a bit of explanation about this:

SHA-1 is nowadays considered a weak hash function – we didn't yet see a collision, but there are algorithms known which make a break much easier than brute-force.
A hash function is used in most signature algorithms for certificates, and some of them rely on SHA-1. Using a weak hash function makes it possible for an attacker to forge a certificate, i.e. pretend being  a site which the attacker is not. (There were famous examples for this using MD5, which therefore is not used anymore for certificates.)

For this reason Google (i.e. the power behind Chrome + Chromium) decided to "phase it out", in the first phase by showing this warning for every certificate with long expiry times, later then it will refuse to connect to such sites at all.

If I currently browse the linked site, I see just signatures using SHA-265, though. Either that certificate got replaced since your screenshot, or there are multiple servers with different certificates active.

**Comment by IvanGoncharov** [comment]
I updated chromium and it looks like it fixed this issue.
