### ISSUE TITLE
Question: Using a local $ref to path item object

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#626]
The [path item object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject) allows the use of `$ref` to reference an external definition, with @darrelmiller we wonder if there's a ways to use a local reference.

When `$ref` references an external file it's OK.
```YAML
  /remote-include:
    $ref: https://gist.githubusercontent.com/arno-di-loreto/dab8501c9972597cebd74c2657b827b6/raw/0b1128317f854f60e86eb8ec25c7924b1cf64a3c/include_operation.yaml
```

But when we try to use a local reference it does not work in the editor (`Unknown error: Cannot read property 'consumes' of undefined`). It may be a bug of the editor but as we're not sure about the syntax or even if it's possible to do that.  

```YAML
/local-include:
    $ref: "#/x-operations/getLocalInclude" 
 
x-operations:
  getLocalInclude:
    get:
      consumes:
        - application/json
      responses:
        200: 
          description: Everything is OK with local include
```

Full gist: https://gist.github.com/arno-di-loreto/dab8501c9972597cebd74c2657b827b6

**Comment by webron** [comment]
It's a bug in the editor. The solution you're using is technically valid although it falls a bit under user abuse (no offense) as an attempt to work around a limitation (which is pretty much why it's a bug with the editor).

Originally, for some reason (and it's not necessarily the right decision), we decided to limit path item refs to external files only. This is done more by controlling the structure of spec itself, not allowing for a 'pathitemdefinitions' object like one exists for parameter and responses. But since we allow for vendor extensions and those are free-form, they are used for such a workaround - I admit I didn't think it was going to be used that way.

I *think* there's an open ticket on it on the editor project, but can't find it now. Feel free to open a new ticket though.

**Comment by arno-di-loreto** [comment]
Thanks I'll take a look in the editor project.

That would be interesting to have local reusable path item object because sometimes you have things like:

- `get /items`
- `get /users/{userId}/items`
Both could use the same path item(s) declared in something like `path-item-definitions`.

Is there already an issue in OpenAPI.next proposal about that? (I didn't find any  but maybe I missed it).

**Comment by arno-di-loreto** [comment]
Closing this issue. I'll create another one for reusable path in next version.

**Comment by ccarcaci** [comment]
@arno-di-loreto may I have the link to the issue for reusable path?
