### ISSUE TITLE
Create serialization strategy for non-body params

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#665]
Follow-up for #564, meta issue #565

**Comment by ePaul** [comment]
@fehguy I think the #564 should be #654 instead. (Feel free to delete this comment after fixing it in the initial comment.)

**Comment by ePaul** [comment]
I just found that there currently is an [Internet draft discussed in the HTTP working group](https://tools.ietf.org/html/draft-ietf-httpbis-jfv-00). This basically defines a format to transport JSON arrays (while omitting the brackets) in HTTP headers.

I guess this could work for custom headers with OpenAPI schema definitions for them, as well as for future official HTTP headers following an RFC coming out of this internet draft.

Note that this defines a serialization scheme just for arrays, not for objects, because that way it works nicely with multiple occurences of a Header, which is equivalent to putting the values together in one, separated by commas.

It will not work for most existing headers using different syntax, for that we would need some different serialization scheme.

*(originally posted at #652, but @fehguy pointed out it belongs here.)*

**Comment by dcolens** [comment]
I bet this was discussed before, but what about using something like http://api.jquery.com/jquery.param/ ?

**Comment by fehguy** [comment]
Covered in #878
