### ISSUE TITLE
Release candidate criteria?

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#984]
Can the core team please shed some light on what the criteria is for issuing release candidates? Is there an official release schedule of how long an RC should gestate before a new RC is issued? Some transparency around this process would be much appreciated, thanks :)

**Comment by darrelmiller** [comment]
There isn't an official schedule as far as I am aware.  The important part of the RC process for me is that we have time to actually build tools that prove the spec is sane.  I'm not too concerned as whether there will be only one more RC release or whether there are 3 more.  However, I am hoping the RC period will only be a couple months.  

I appreciate all the feedback that you and a number of other people are providing.  I've not been too involved in dealing with issues due to a vacation and all my spare time being spent on writing tooling against the spec.

What would work best for you with regard to the number of RCs?  More and frequent, or less?

**Comment by willdady** [comment]
I'm not too concerned about the frequency or number of release candidates. I can certainly accept _'when it's ready'_ as a perfectly valid answer :)

As someone who is dabbling in writing a tool I'm interested in knowing what the path might look like towards reaching 3.0 final. I'm hesitant to start working on implementing changes which have pull requests pending for example.

Is it worth [creating a milestone](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) for tracking what needs to be fixed?

Don't get me wrong, the progress I've seen so far has been great! Was just curious if the RC process has been formalized. Docker have [their release process documented](https://github.com/docker/docker/wiki) for example (not a fair comparison I know).

**Comment by ePaul** [comment]
@willdady I think currently most changes being discussed for 3.0 are just smaller changes (like `example`/`examples` – which needs to be changed by implementors, but should not be too hard to change, even if you already implemented the current logic), or even just clarifications/typos/organizational fixes.

I think you should be able to start implementing the spec ... though maybe not yet release anything which can't be updated easily when the fixes are done. (So don't burn your OpenAPI generator on a CD-ROM.)

Also, the point is that during implementation you might stumble upon issues with the spec which should better be corrected now than burned into the final spec.

(Just my personal opinion, I'm not in any position of decision power here.)

**Comment by webron** [comment]
As @darrelmiller said, we don't have anything official. This is the first time we're doing the process, and it's difficult to say. My guess is that there's going to be at least one more RC before a final version. 

While the feedback is important on all the changes, I believe we're curious on feedback on the bigger changes - callbacks, links and security.

Waiting on building tools because the spec might change defeats the purpose of the RC - it's called an Implementer's Draft for that reason. We want to learn the issues before we finalize the spec, not after.

**Comment by MikeRalphson** [comment]
@darrelmiller @DavidBiesack @webron @fehguy it might help reduce confusion if the version of the work-in-progress 3.0.md on the OpenAPI.next branch was changed to (for example) `3.0.0-RC2-pre` and only changed to `3.0.0-RC2` immediately before the rc2 tag is cut.

**Comment by handrews** [comment]
Since this was about the specifics of how we did releases in 2017, I'm going to close it as outdated.
